# Generated by Django 3.0.5 on 2021-01-19 05:43

import apps.parking_lot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0007_auto_20210105_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('status', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_items', to='country.Country', verbose_name='Country')),
                ('owner_sign_off', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_off_parking_lots', to=settings.AUTH_USER_MODEL, verbose_name='Owner Sign Off')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parking_lots', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
        ),
    ]
