# Generated by Django 3.0.5 on 2021-04-08 09:04

import apps.parking_lot.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_countrypopulation'),
        ('parking_lot', '0003_auto_20210127_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkeditem',
            name='source',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.parking_lot.models.ParkedItem.PARKING_LOT_SOURCE, null=True),
        ),
        migrations.AddField(
            model_name='parkeditem',
            name='source_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Uuid'),
        ),
        migrations.AlterField(
            model_name='parkeditem',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parked_items', to='country.Country', verbose_name='Country'),
        ),
    ]
