# Generated by Django 3.0.5 on 2021-04-12 11:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_countrypopulation'),
        ('parking_lot', '0004_auto_20210408_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkeditem',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parkeditem',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parked_items', to='country.Country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
