# Generated by Django 3.0.5 on 2021-04-18 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_countrypopulation'),
        ('parking_lot', '0004_auto_20210413_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkeditem',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parked_items', to='country.Country', verbose_name='Country'),
        ),
    ]
