# Generated by Django 3.0.5 on 2022-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0005_auto_20210418_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkeditem',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='URL'),
        ),
    ]
