# Generated by Django 3.2 on 2023-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0006_auto_20220629_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkeditem',
            name='meta_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
