# Generated by Django 3.2 on 2024-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0007_alter_parkeditem_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
