# Generated by Django 3.0.5 on 2020-11-05 05:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='boundingbox',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None, verbose_name='Bounding Box'),
        ),
        migrations.AddField(
            model_name='country',
            name='centroid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None, verbose_name='Centroid'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='idmc_full_name',
            field=models.CharField(max_length=256, null=True, verbose_name='IDMC Full Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='idmc_short_name',
            field=models.CharField(max_length=256, null=True, verbose_name='IDMC Short Name'),
        ),
        migrations.AddField(
            model_name='country',
            name='idmc_short_name_ar',
            field=models.CharField(max_length=256, null=True, verbose_name='IDMC Short Name Ar'),
        ),
        migrations.AddField(
            model_name='country',
            name='idmc_short_name_es',
            field=models.CharField(max_length=256, null=True, verbose_name='IDMC Short Name Es'),
        ),
        migrations.AddField(
            model_name='country',
            name='idmc_short_name_fr',
            field=models.CharField(max_length=256, null=True, verbose_name='IDMC Short Name Fr'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ISO3'),
        ),
        migrations.AddField(
            model_name='country',
            name='sub_region',
            field=models.CharField(max_length=256, null=True, verbose_name='Sub Region'),
        ),
        migrations.AddField(
            model_name='country',
            name='geographical_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.GeographicalGroup', verbose_name='Geographical Group'),
        ),
    ]
