# Generated by Django 3.0.5 on 2020-12-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_country_iso2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='boundingbox',
            new_name='bounding_box',
        ),
    ]
