# Generated by Django 3.0.5 on 2021-01-05 04:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_merge_20210104_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('size', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0, message='Should be positive')], verbose_name='Size')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_sizes', to='country.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
