# Generated by Django 3.0.5 on 2021-02-02 05:17

import apps.crisis.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20210105_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextualupdate',
            name='crisis_type',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.crisis.models.Crisis.CRISIS_TYPE, null=True),
        ),
        migrations.AddField(
            model_name='contextualupdate',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Published Date'),
        ),
    ]
