# Generated by Django 3.0.5 on 2021-03-10 07:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_auto_20210204_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.PositiveIntegerField(verbose_name='Population')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800, 'Invalid date'), django.core.validators.MaxValueValidator(9999, 'Invalid date')], verbose_name='Year')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='country.Country', verbose_name='Country')),
            ],
            options={
                'unique_together': {('country', 'year')},
            },
        ),
    ]
