# Generated by Django 3.0.5 on 2021-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_auto_20210423_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='sub_region',
        ),
    ]
