# Generated by Django 3.0.5 on 2021-06-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_auto_20210423_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='sub_region',
        ),
        migrations.AddField(
            model_name='country',
            name='monitoring_sub_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='country.MonitoringSubRegion', verbose_name='Monitoring Sub-Region'),
        ),
    ]
