# Generated by Django 3.0.5 on 2021-06-23 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_auto_20210423_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypopulation',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800, 'The date is invalid.'), django.core.validators.MaxValueValidator(9999, 'The date is invalid.')], verbose_name='Year'),
        ),
    ]
