# Generated by Django 3.0.5 on 2021-07-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_auto_20210623_0307'),
        ('country', '0013_country_sub_region'),
    ]

    operations = [
    ]
