# Generated by Django 3.0.14 on 2023-04-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    def update_country_name(apps, schema_editor):
        Country = apps.get_model('country', 'Country')
        iso3_country_map = {'BRN':'Brunei', 'RUS':'Russia', 'VIR':'Virgin Islands'}
        for iso3, idmc_short_name in iso3_country_map.items():
            Country.objects.filter(iso3=iso3).update(idmc_short_name=idmc_short_name)

    dependencies = [
        ('country', '0015_update_and_delete_geolocation_group'),
    ]

    operations = [
        migrations.RunPython(update_country_name, reverse_code=migrations.RunPython.noop),
    ]
