# Generated by Django 3.2 on 2026-01-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_alter_household_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdsize',
            name='source_link',
            field=models.CharField(max_length=2000, verbose_name='Source Link'),
        ),
    ]
