# Generated by Django 3.2 on 2026-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0020_alter_householdsize_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdsize',
            name='source_link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Source Link'),
        ),
    ]
