# Generated by Django 3.2 on 2026-03-15 16:26

import apps.country.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0021_alter_householdsize_source_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdSizeCarryOverTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.country.models.HouseholdSizeCarryOverTask.AHHS_COPY_OPERATION_STATUS)),
                ('target_year', models.SmallIntegerField(verbose_name='Target Year')),
                ('failure_reasons', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_householdsizecarryovertask', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='householdsize',
            options={'permissions': (('carry_over_householdsize', 'Can carry over householdsize'),)},
        ),
    ]
