# Generated by Django 3.2 on 2026-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0021_alter_householdsize_source_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['idmc_short_name'], name='country_cou_idmc_sh_58bf5a_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso3'], name='country_cou_iso3_ce34c7_idx'),
        ),
    ]
