# Generated by Django 3.2 on 2026-05-27 04:58

import apps.country.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_auto_20260310_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsize',
            name='gap_filling_method',
            field=django_enumfield.db.fields.EnumField(enum=apps.country.models.HouseholdSize.GAP_FILLING_METHOD, null=True),
        ),
        migrations.AddField(
            model_name='householdsize',
            name='reference_year',
            field=models.IntegerField(null=True, verbose_name='Reference year'),
        ),
    ]
