# Generated by Django 3.0.5 on 2020-11-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20201019_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organizationkind',
            old_name='title',
            new_name='name',
        ),
    ]
