# Generated by Django 3.0.5 on 2020-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20201109_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='source_detail_methodology',
        ),
        migrations.AddField(
            model_name='organization',
            name='breakdown',
            field=models.TextField(blank=True, null=True, verbose_name='Source Breakdown and Reliability'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='methodology',
            field=models.TextField(blank=True, null=True, verbose_name='Methodology'),
        ),
    ]
