# Generated by Django 3.0.5 on 2021-06-23 03:57

import apps.organization.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_auto_20210623_0307'),
        ('organization', '0006_auto_20201231_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.organization.models.Organization.ORGANIZATION_CATEGORY),
        ),
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(related_name='organizations', to='country.Country', verbose_name='Countries'),
        ),
    ]
