# Generated by Django 3.0.5 on 2022-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_merge_20210702_0747'),
        ('organization', '0008_auto_20220613_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='country.Country', verbose_name='Countries'),
        ),
    ]
