# Generated by Django 3.2 on 2026-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20240326_0824'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_2d216c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['short_name'], name='organizatio_short_n_bcd8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationkind',
            index=models.Index(fields=['name'], name='organizatio_name_9a8c31_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationkind',
            index=models.Index(fields=['reliability'], name='organizatio_reliabi_d1880e_idx'),
        ),
    ]
