"""
Regenerate pyhelix's generated files from the helix-server Django enums and
``schema.graphql``.

pyhelix is a standalone library (different Python version + dependency set, no
Django) so it cannot import from apps.*. To keep its enum clones and GraphQL
response types in lockstep with the helix-server source-of-truth, this command
renders both files. CI runs ``--check`` to fail the build if either generated
file is stale.

Generated files:

* ``libs/pyhelix/pyhelix/constants.py`` — enum clones (from Django enums).
* ``libs/pyhelix/pyhelix/api_types.py`` — pydantic models for GraphQL
  response types (from ``schema.graphql``).
"""

import dataclasses
import difflib
import enum as _enum
import io
import os
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.utils.translation import override
from graphql.language.parser import parse as graphql_parse
from graphql.type import (
    GraphQLEnumType,
    GraphQLList,
    GraphQLNonNull,
    GraphQLObjectType,
    GraphQLScalarType,
)
from graphql.utils.build_ast_schema import build_ast_schema

from apps.contrib.commons import DATE_ACCURACY
from apps.contrib.models import Attachment
from apps.crisis.models import Crisis
from apps.entry.models import Figure, FigureLocation
from apps.event.models import EventCode
from apps.hulk.models import HulkBulkImport
from utils.validations import MAX_FUTURE_YEARS

PYHELIX_CONSTANTS_REL_PATH = "libs/pyhelix/pyhelix/constants.py"
PYHELIX_API_TYPES_REL_PATH = "libs/pyhelix/pyhelix/api_types.py"
SCHEMA_REL_PATH = "schema.graphql"

# Members of Figure.FIGURE_CATEGORY_TYPES marked `# deprecated` in
# apps/entry/models.py. Kept here because the deprecation marker is a source
# comment, not data on the enum. Update this set when the Django source changes.
DEPRECATED_FIGURE_CATEGORY_TYPES: Set[str] = {
    "RETURNEES",
    "RETURN",
    "LOCALLY_INTEGRATED_IDPS",
    "IDPS_SETTLED_ELSEWHERE",
    "PEOPLE_DISPLACED_ACROSS_BORDERS",
    "MULTIPLE_DISPLACEMENT",
    "PARTIAL_STOCK",
    "PARTIAL_FLOW",
    "CROSS_BORDER_FLIGHT",
    "CROSS_BORDER_RETURN",
    "RELOCATION_ELSEWHERE",
    "DEATHS",
    "PROVISIONAL_SOLUTIONS",
    "FAILED_LOCAL_INTEGRATION",
    "LOCAL_INTEGRATION",
    "FAILED_RETURN_RETURNEE_DISPLACEMENT",
    "UNVERIFIED_STOCK",
    "UNVERIFIED_FLOW",
    "BIRTH",
    "FAILED_RELOCATION_ELSEWHERE",
    "PEOPLE_DISPLACED_ACROSS_BORDERS_FLOW",
}

# (pyhelix_output_name, source_label_for_comment, source_enum_cls, deprecated_member_names)
EnumSpec = Tuple[str, str, type, Set[str]]

ENUM_SPECS: List[EnumSpec] = [
    ("DATE_ACCURACY", "DATE_ACCURACY", DATE_ACCURACY, set()),
    ("CRISIS_TYPE", "Crisis.CRISIS_TYPE", Crisis.CRISIS_TYPE, set()),
    ("EVENT_CODE_TYPE", "EventCode.EVENT_CODE_TYPE", EventCode.EVENT_CODE_TYPE, set()),
    (
        "FIGURE_CATEGORY_TYPES",
        "Figure.FIGURE_CATEGORY_TYPES",
        Figure.FIGURE_CATEGORY_TYPES,
        DEPRECATED_FIGURE_CATEGORY_TYPES,
    ),
    ("FIGURE_TERMS", "Figure.FIGURE_TERMS", Figure.FIGURE_TERMS, set()),
    ("FIGURE_QUANTIFIER", "Figure.QUANTIFIER", Figure.QUANTIFIER, set()),
    ("FIGURE_UNIT", "Figure.UNIT", Figure.UNIT, set()),
    ("FIGURE_ROLE", "Figure.ROLE", Figure.ROLE, set()),
    (
        "FIGURE_DISPLACEMENT_OCCURRED",
        "Figure.DISPLACEMENT_OCCURRED",
        Figure.DISPLACEMENT_OCCURRED,
        set(),
    ),
    (
        "FIGURE_LOCATION_IDENTIFIER",
        "FigureLocation.IDENTIFIER",
        FigureLocation.IDENTIFIER,
        set(),
    ),
    (
        "FIGURE_LOCATION_GEOCODER",
        "FigureLocation.GEOCODER",
        FigureLocation.GEOCODER,
        set(),
    ),
    (
        "FIGURE_LOCATION_ACCURACY",
        "FigureLocation.ACCURACY",
        FigureLocation.ACCURACY,
        set(),
    ),
    (
        "PCODE_ACCURACY",
        "FigureLocation.PCODE_ACCURACY",
        FigureLocation.PCODE_ACCURACY,
        set(),
    ),
    (
        "ATTACHMENT_FOR_CHOICES",
        "Attachment.FOR_CHOICES",
        Attachment.FOR_CHOICES,
        set(),
    ),
    (
        "HULK_BULK_IMPORT_STATUS",
        "HulkBulkImport.HULK_BULK_IMPORT_STATUS",
        HulkBulkImport.HULK_BULK_IMPORT_STATUS,
        set(),
    ),
]

# Plain scalar constants shared with pyhelix. Django is the single source of
# truth; pyhelix (no Django) receives the value via the generated constants.py.
# (pyhelix_output_name, source_label_for_comment, value)
ScalarSpec = Tuple[str, str, Any]

SCALAR_SPECS: List[ScalarSpec] = [
    ("MAX_FUTURE_YEARS", "utils.validations.MAX_FUTURE_YEARS", MAX_FUTURE_YEARS),
]

HEADER = (
    "# AUTOGENERATED - do not edit.\n"
    "# Regenerate via: ./manage.py update_pyhelix_constants\n"
    "# Source of truth: helix-server Django enums (see apps.*).\n"
    "from __future__ import annotations\n"
    "\n"
    "import enum\n"
    "\n"
    "\n"
    "def _(v):\n"
    "    return v\n"
)


def _label_text(label: Any) -> str:
    """Resolve a gettext_lazy proxy (or plain str) to its English msgid."""
    with override("en"):
        text = str(label)
    if '"' in text:
        raise CommandError(f"Label {text!r} contains a double-quote; generator needs escaping support.")
    return text


def _labels_in_source_order(
    enum_cls: type,
) -> Optional[List[Tuple[str, Any]]]:
    """Return [(member_name, label_value), ...] preserving __labels__ key order.

    Handles both shapes seen in the codebase: __labels__ keyed by member value
    (int) or by the member itself.
    """
    labels: Optional[Dict] = getattr(enum_cls, "__labels__", None)
    if not labels:
        return None
    by_value = {m.value: m for m in enum_cls}  # type: ignore[attr-defined]
    out: List[Tuple[str, Any]] = []
    for key, value in labels.items():
        if isinstance(key, _enum.Enum):
            member = key
        else:
            member = by_value.get(key)
        if member is None:
            raise CommandError(f"{enum_cls.__name__}.__labels__ has key {key!r} with no matching member")
        out.append((member.name, value))
    return out


def _render_enum(spec: EnumSpec) -> str:
    out_name, source_label, enum_cls, deprecated = spec
    members: Iterable[Any] = list(enum_cls)  # type: ignore[arg-type]
    buf = io.StringIO()
    buf.write(f"# Clone of {source_label}\n")
    buf.write(f"class {out_name}(enum.Enum):\n")
    for member in members:
        buf.write(f"    {member.name} = {member.value}\n")

    labelled = _labels_in_source_order(enum_cls)
    if labelled is not None:
        buf.write("\n")
        buf.write("    __labels__ = {\n")
        for member_name, label in labelled:
            text = _label_text(label)
            suffix = "  # deprecated" if member_name in deprecated else ""
            buf.write(f'        {member_name}: _("{text}"),{suffix}\n')
        buf.write("    }\n")
    return buf.getvalue()


def _render_int_list(name: str, source_label: str, values: List[int]) -> str:
    by_value = {m.value: m.name for m in Figure.FIGURE_CATEGORY_TYPES}
    buf = io.StringIO()
    buf.write(f"# Clone of {source_label}\n")
    buf.write(f"{name} = [\n")
    for v in values:
        if v not in by_value:
            raise CommandError(f"{source_label} contains value {v} not in FIGURE_CATEGORY_TYPES")
        buf.write(f"    FIGURE_CATEGORY_TYPES.{by_value[v]}.value,\n")
    buf.write("]\n")
    return buf.getvalue()


def _render_scalar(spec: ScalarSpec) -> str:
    out_name, source_label, value = spec
    # bool is a subclass of int; both round-trip cleanly through repr().
    if not isinstance(value, (int, float, str)):
        raise CommandError(f"{source_label} value {value!r} is not a supported scalar (int/float/str)")
    buf = io.StringIO()
    buf.write(f"# Clone of {source_label}\n")
    buf.write(f"{out_name} = {value!r}\n")
    return buf.getvalue()


def render() -> str:
    # PEP-8: two blank lines between top-level class blocks; the related
    # flow/stock lists are kept one blank line apart to match the existing file.
    blocks: List[str] = [HEADER.rstrip("\n")]
    for spec in ENUM_SPECS:
        blocks.append(_render_enum(spec).rstrip("\n"))
    body = "\n\n\n".join(blocks)
    flow = _render_int_list("FIGURE_FLOW_LIST", "Figure.flow_list()", Figure.flow_list()).rstrip("\n")
    stock = _render_int_list("FIGURE_STOCK_LIST", "Figure.stock_list()", Figure.stock_list()).rstrip("\n")
    scalars = "\n".join(_render_scalar(spec).rstrip("\n") for spec in SCALAR_SPECS)
    return body + "\n\n\n" + flow + "\n\n" + stock + "\n\n\n" + scalars + "\n"


# ---------------------------------------------------------------------------
# api_types.py: pydantic models cloned from schema.graphql response types
# ---------------------------------------------------------------------------

# GraphQL scalar -> rendered python type. ``GenericScalar`` / ``JSONString``
# come back as opaque structures; ``EnumDescription`` is a display string the
# server stamps on enums. Anything not in this map raises so the operator
# notices new scalars instead of silently widening to str.
SCALAR_TO_PY: Dict[str, str] = {
    "ID": "str",
    "String": "str",
    "Int": "int",
    "Float": "float",
    "Boolean": "bool",
    "DateTime": "datetime.datetime",
    "Date": "datetime.date",
    "EnumDescription": "str",
    "JSONString": "str",
    "GenericScalar": "typing.Any",
    "Upload": "str",
}

# GraphQL enum type name -> pyhelix constants enum name. Enums in this map
# become ``Annotated[<constant>, enum_parser(<constant>)]`` so the wire-format
# enum *name* (e.g. ``"PENDING"``) is parsed into the typed enum. Enums not in
# this map fall back to ``str``.
GRAPHQL_ENUM_TO_PYHELIX_CONSTANT: Dict[str, str] = {
    "HULK_BULK_IMPORT_STATUS": "HULK_BULK_IMPORT_STATUS",
}


@dataclasses.dataclass
class GraphqlTypeSpec:
    """One graphql object type to clone into pyhelix as a pydantic model."""

    graphql_name: str
    py_name: str
    # graphql field names (camelCase) to render — limits the model to the
    # selection set used by pyhelix queries so unused fields don't pollute
    # the generated model.
    fields: List[str]


# Order matters: types referenced by later entries (e.g. ``HulkBulkImportType``
# references ``HulkBulkImportDatasetType``) must appear first. Forward refs work
# via ``from __future__ import annotations`` so ordering is not strictly
# required, but we keep dependents-after-deps for readability.
GRAPHQL_TYPE_SPECS: List[GraphqlTypeSpec] = [
    GraphqlTypeSpec(
        graphql_name="HulkBulkImportDatasetType",
        py_name="HulkBulkImportDatasetState",
        fields=[
            "id",
            "importType",
            "successCount",
            "failureCount",
            "skipCount",
            "importFile",
            "successFile",
            "failureFile",
            "skipFile",
        ],
    ),
    GraphqlTypeSpec(
        graphql_name="HulkBulkImportType",
        py_name="HulkBulkImportState",
        fields=[
            "id",
            "name",
            "status",
            "statusDisplay",
            "successCount",
            "failureCount",
            "skipCount",
            "startedAt",
            "completedAt",
            "datasets",
        ],
    ),
]


@dataclasses.dataclass
class _FieldRenderInfo:
    uses_datetime: bool = False
    uses_typing_extensions: bool = False
    enum_constants: Set[str] = dataclasses.field(default_factory=set)


def _camel_to_snake(name: str) -> str:
    out: List[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def _render_inner_type(t: Any, type_map: Dict[str, str], info: _FieldRenderInfo) -> str:
    if isinstance(t, GraphQLNonNull):
        return _render_inner_type(t.of_type, type_map, info)
    if isinstance(t, GraphQLList):
        return f"typing.List[{_render_inner_type(t.of_type, type_map, info)}]"
    if isinstance(t, GraphQLScalarType):
        py = SCALAR_TO_PY.get(t.name)
        if py is None:
            raise CommandError(f"Unmapped GraphQL scalar: {t.name}")
        if py.startswith("datetime."):
            info.uses_datetime = True
        return py
    if isinstance(t, GraphQLEnumType):
        const = GRAPHQL_ENUM_TO_PYHELIX_CONSTANT.get(t.name)
        if const:
            info.enum_constants.add(const)
            return const
        return "str"
    if isinstance(t, GraphQLObjectType):
        py = type_map.get(t.name)
        if py is None:
            raise CommandError(
                f"GraphQL object type {t.name!r} referenced but not declared in GRAPHQL_TYPE_SPECS",
            )
        return py
    raise CommandError(f"Unhandled GraphQL type at field render time: {t!r}")


def _innermost_named_type(t: Any) -> Any:
    while isinstance(t, (GraphQLNonNull, GraphQLList)):
        t = t.of_type
    return t


def _render_field(field_name: str, field_type: Any, type_map: Dict[str, str]) -> Tuple[str, _FieldRenderInfo]:
    info = _FieldRenderInfo()
    nullable = not isinstance(field_type, GraphQLNonNull)
    inner = _render_inner_type(field_type, type_map, info)

    bottom = _innermost_named_type(field_type)
    if isinstance(bottom, GraphQLEnumType) and bottom.name in GRAPHQL_ENUM_TO_PYHELIX_CONSTANT:
        const = GRAPHQL_ENUM_TO_PYHELIX_CONSTANT[bottom.name]
        info.uses_typing_extensions = True
        inner = f"typing_extensions.Annotated[{inner}, enum_parser({const})]"

    py_name = _camel_to_snake(field_name)
    alias_needed = py_name != field_name

    rendered_type = f"typing.Optional[{inner}]" if nullable else inner

    field_args: List[str] = []
    if nullable:
        field_args.append("default=None")
    if alias_needed:
        field_args.append(f'alias="{field_name}"')

    if not field_args:
        line = f"    {py_name}: {rendered_type}"
    else:
        line = f"    {py_name}: {rendered_type} = Field({', '.join(field_args)})"
    return line, info


API_TYPES_HEADER_PREFIX = (
    "# AUTOGENERATED - do not edit.\n"
    "# Regenerate via: ./manage.py update_pyhelix_constants\n"
    "# Source of truth: helix-server schema.graphql.\n"
    "from __future__ import annotations\n"
)


def _build_api_types_header(
    uses_datetime: bool,
    uses_typing_extensions: bool,
    enum_constants: Set[str],
) -> str:
    lines: List[str] = [API_TYPES_HEADER_PREFIX.rstrip("\n"), ""]
    if uses_datetime:
        lines.append("import datetime")
    lines.append("import typing")
    if uses_typing_extensions:
        lines.append("")
        lines.append("import typing_extensions")
    lines.append("from pydantic import BaseModel, ConfigDict, Field")
    if enum_constants:
        lines.append("")
        lines.append(f"from .constants import {', '.join(sorted(enum_constants))}")
        lines.append("from .parsers import enum_parser")
    return "\n".join(lines)


def render_api_types() -> str:
    schema_path = os.path.join(settings.BASE_DIR, SCHEMA_REL_PATH)
    with open(schema_path, "r", encoding="utf-8") as f:
        schema = build_ast_schema(graphql_parse(f.read()))

    type_map = {spec.graphql_name: spec.py_name for spec in GRAPHQL_TYPE_SPECS}

    blocks: List[str] = []
    total = _FieldRenderInfo()
    for spec in GRAPHQL_TYPE_SPECS:
        gtype = schema.get_type(spec.graphql_name)
        if gtype is None:
            raise CommandError(f"GraphQL type {spec.graphql_name!r} not found in {SCHEMA_REL_PATH}")
        if not isinstance(gtype, GraphQLObjectType):
            raise CommandError(f"{spec.graphql_name} is not an object type")

        buf = io.StringIO()
        buf.write(f"# Clone of {spec.graphql_name}\n")
        buf.write(f"class {spec.py_name}(BaseModel):\n")
        buf.write("    model_config = ConfigDict(populate_by_name=True)\n")
        buf.write("\n")
        for field_name in spec.fields:
            if field_name not in gtype.fields:
                raise CommandError(f"Field {field_name!r} not on GraphQL type {spec.graphql_name}")
            line, info = _render_field(field_name, gtype.fields[field_name].type, type_map)
            buf.write(line + "\n")
            total.uses_datetime = total.uses_datetime or info.uses_datetime
            total.uses_typing_extensions = total.uses_typing_extensions or info.uses_typing_extensions
            total.enum_constants.update(info.enum_constants)
        blocks.append(buf.getvalue().rstrip("\n"))

    header = _build_api_types_header(total.uses_datetime, total.uses_typing_extensions, total.enum_constants)
    return header + "\n\n\n" + "\n\n\n".join(blocks) + "\n"


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


def _check_or_write(
    target_rel_path: str,
    generated: str,
    check: bool,
    stderr,
    stdout,
    style,
) -> None:
    target = os.path.join(settings.BASE_DIR, target_rel_path)
    if check:
        try:
            with open(target, "r", encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            raise CommandError(f"{target_rel_path} is missing.")
        if current != generated:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=f"{target_rel_path} (on disk)",
                tofile=f"{target_rel_path} (expected)",
            )
            stderr.write("".join(diff))
            raise CommandError(f"{target_rel_path} is stale. Run: ./manage.py update_pyhelix_constants")
        stdout.write(style.SUCCESS(f"{target_rel_path} is up to date."))
        return

    with open(target, "w", encoding="utf-8") as f:
        f.write(generated)
    stdout.write(style.SUCCESS(f"Wrote {target_rel_path}"))


class Command(BaseCommand):
    help = "Regenerate pyhelix's constants.py (Django enums) and api_types.py (schema.graphql response types)."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Exit 1 if any generated content differs from the file on disk (for CI).",
        )

    def handle(self, *args, **options):
        check = options["check"]
        _check_or_write(PYHELIX_CONSTANTS_REL_PATH, render(), check, self.stderr, self.stdout, self.style)
        _check_or_write(PYHELIX_API_TYPES_REL_PATH, render_api_types(), check, self.stderr, self.stdout, self.style)
