"""
Regenerate libs/pyhelix/pyhelix/constants.py from helix-server Django enums.

pyhelix is a standalone library (different Python version + dependency set, no
Django) so it cannot import from apps.*. To keep its enum clones in lockstep
with the Django source-of-truth, this command renders the file from the Django
enums. CI runs `--check` to fail the build if pyhelix constants are stale.
"""

import difflib
import enum as _enum
import io
import os
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.utils.translation import override

from apps.contrib.commons import DATE_ACCURACY
from apps.contrib.models import Attachment
from apps.crisis.models import Crisis
from apps.entry.models import Figure, FigureLocation
from apps.event.models import EventCode

PYHELIX_CONSTANTS_REL_PATH = "libs/pyhelix/pyhelix/constants.py"

# Members of Figure.FIGURE_CATEGORY_TYPES marked `# deprecated` in
# apps/entry/models.py. Kept here because the deprecation marker is a source
# comment, not data on the enum. Update this set when the Django source changes.
DEPRECATED_FIGURE_CATEGORY_TYPES: Set[str] = {
    "RETURNEES",
    "RETURN",
    "LOCALLY_INTEGRATED_IDPS",
    "IDPS_SETTLED_ELSEWHERE",
    "PEOPLE_DISPLACED_ACROSS_BORDERS",
    "MULTIPLE_DISPLACEMENT",
    "PARTIAL_STOCK",
    "PARTIAL_FLOW",
    "CROSS_BORDER_FLIGHT",
    "CROSS_BORDER_RETURN",
    "RELOCATION_ELSEWHERE",
    "DEATHS",
    "PROVISIONAL_SOLUTIONS",
    "FAILED_LOCAL_INTEGRATION",
    "LOCAL_INTEGRATION",
    "FAILED_RETURN_RETURNEE_DISPLACEMENT",
    "UNVERIFIED_STOCK",
    "UNVERIFIED_FLOW",
    "BIRTH",
    "FAILED_RELOCATION_ELSEWHERE",
    "PEOPLE_DISPLACED_ACROSS_BORDERS_FLOW",
}

# (pyhelix_output_name, source_label_for_comment, source_enum_cls, deprecated_member_names)
EnumSpec = Tuple[str, str, type, Set[str]]

ENUM_SPECS: List[EnumSpec] = [
    ("DATE_ACCURACY", "DATE_ACCURACY", DATE_ACCURACY, set()),
    ("CRISIS_TYPE", "Crisis.CRISIS_TYPE", Crisis.CRISIS_TYPE, set()),
    ("EVENT_CODE_TYPE", "EventCode.EVENT_CODE_TYPE", EventCode.EVENT_CODE_TYPE, set()),
    (
        "FIGURE_CATEGORY_TYPES",
        "Figure.FIGURE_CATEGORY_TYPES",
        Figure.FIGURE_CATEGORY_TYPES,
        DEPRECATED_FIGURE_CATEGORY_TYPES,
    ),
    ("FIGURE_TERMS", "Figure.FIGURE_TERMS", Figure.FIGURE_TERMS, set()),
    ("FIGURE_QUANTIFIER", "Figure.QUANTIFIER", Figure.QUANTIFIER, set()),
    ("FIGURE_UNIT", "Figure.UNIT", Figure.UNIT, set()),
    ("FIGURE_ROLE", "Figure.ROLE", Figure.ROLE, set()),
    (
        "FIGURE_DISPLACEMENT_OCCURRED",
        "Figure.DISPLACEMENT_OCCURRED",
        Figure.DISPLACEMENT_OCCURRED,
        set(),
    ),
    (
        "FIGURE_LOCATION_IDENTIFIER",
        "FigureLocation.IDENTIFIER",
        FigureLocation.IDENTIFIER,
        set(),
    ),
    (
        "FIGURE_LOCATION_GEOCODER",
        "FigureLocation.GEOCODER",
        FigureLocation.GEOCODER,
        set(),
    ),
    (
        "FIGURE_LOCATION_ACCURACY",
        "FigureLocation.ACCURACY",
        FigureLocation.ACCURACY,
        set(),
    ),
    (
        "ATTACHMENT_FOR_CHOICES",
        "Attachment.FOR_CHOICES",
        Attachment.FOR_CHOICES,
        set(),
    ),
]

HEADER = (
    "# AUTOGENERATED - do not edit.\n"
    "# Regenerate via: ./manage.py update_pyhelix_constants\n"
    "# Source of truth: helix-server Django enums (see apps.*).\n"
    "from __future__ import annotations\n"
    "\n"
    "import enum\n"
    "\n"
    "\n"
    "def _(v):\n"
    "    return v\n"
)


def _label_text(label: Any) -> str:
    """Resolve a gettext_lazy proxy (or plain str) to its English msgid."""
    with override("en"):
        text = str(label)
    if '"' in text:
        raise CommandError(f"Label {text!r} contains a double-quote; generator needs escaping support.")
    return text


def _labels_in_source_order(
    enum_cls: type,
) -> Optional[List[Tuple[str, Any]]]:
    """Return [(member_name, label_value), ...] preserving __labels__ key order.

    Handles both shapes seen in the codebase: __labels__ keyed by member value
    (int) or by the member itself.
    """
    labels: Optional[Dict] = getattr(enum_cls, "__labels__", None)
    if not labels:
        return None
    by_value = {m.value: m for m in enum_cls}  # type: ignore[attr-defined]
    out: List[Tuple[str, Any]] = []
    for key, value in labels.items():
        if isinstance(key, _enum.Enum):
            member = key
        else:
            member = by_value.get(key)
        if member is None:
            raise CommandError(f"{enum_cls.__name__}.__labels__ has key {key!r} with no matching member")
        out.append((member.name, value))
    return out


def _render_enum(spec: EnumSpec) -> str:
    out_name, source_label, enum_cls, deprecated = spec
    members: Iterable[Any] = list(enum_cls)  # type: ignore[arg-type]
    buf = io.StringIO()
    buf.write(f"# Clone of {source_label}\n")
    buf.write(f"class {out_name}(enum.Enum):\n")
    for member in members:
        buf.write(f"    {member.name} = {member.value}\n")

    labelled = _labels_in_source_order(enum_cls)
    if labelled is not None:
        buf.write("\n")
        buf.write("    __labels__ = {\n")
        for member_name, label in labelled:
            text = _label_text(label)
            suffix = "  # deprecated" if member_name in deprecated else ""
            buf.write(f'        {member_name}: _("{text}"),{suffix}\n')
        buf.write("    }\n")
    return buf.getvalue()


def _render_int_list(name: str, source_label: str, values: List[int]) -> str:
    by_value = {m.value: m.name for m in Figure.FIGURE_CATEGORY_TYPES}
    buf = io.StringIO()
    buf.write(f"# Clone of {source_label}\n")
    buf.write(f"{name} = [\n")
    for v in values:
        if v not in by_value:
            raise CommandError(f"{source_label} contains value {v} not in FIGURE_CATEGORY_TYPES")
        buf.write(f"    FIGURE_CATEGORY_TYPES.{by_value[v]}.value,\n")
    buf.write("]\n")
    return buf.getvalue()


def render() -> str:
    # PEP-8: two blank lines between top-level class blocks; the related
    # flow/stock lists are kept one blank line apart to match the existing file.
    blocks: List[str] = [HEADER.rstrip("\n")]
    for spec in ENUM_SPECS:
        blocks.append(_render_enum(spec).rstrip("\n"))
    body = "\n\n\n".join(blocks)
    flow = _render_int_list("FIGURE_FLOW_LIST", "Figure.flow_list()", Figure.flow_list()).rstrip("\n")
    stock = _render_int_list("FIGURE_STOCK_LIST", "Figure.stock_list()", Figure.stock_list()).rstrip("\n")
    return body + "\n\n\n" + flow + "\n\n" + stock + "\n"


class Command(BaseCommand):
    help = "Regenerate libs/pyhelix/pyhelix/constants.py from helix-server Django enums."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Exit 1 if the generated content differs from the file on disk (for CI).",
        )

    def handle(self, *args, **options):
        target = os.path.join(settings.BASE_DIR, PYHELIX_CONSTANTS_REL_PATH)
        generated = render()

        if options["check"]:
            try:
                with open(target, "r", encoding="utf-8") as f:
                    current = f.read()
            except FileNotFoundError:
                raise CommandError(f"{PYHELIX_CONSTANTS_REL_PATH} is missing.")
            if current != generated:
                diff = difflib.unified_diff(
                    current.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=f"{PYHELIX_CONSTANTS_REL_PATH} (on disk)",
                    tofile=f"{PYHELIX_CONSTANTS_REL_PATH} (expected)",
                )
                self.stderr.write("".join(diff))
                raise CommandError(f"{PYHELIX_CONSTANTS_REL_PATH} is stale. Run: ./manage.py update_pyhelix_constants")
            self.stdout.write(self.style.SUCCESS(f"{PYHELIX_CONSTANTS_REL_PATH} is up to date."))
            return

        with open(target, "w", encoding="utf-8") as f:
            f.write(generated)
        self.stdout.write(self.style.SUCCESS(f"Wrote {PYHELIX_CONSTANTS_REL_PATH}"))
