default_language_version:
  python: python3

# NOTE: Update in pyproject.toml as well
exclude: |
    (?x)^(
      \.git|
      __pycache__|
      \.venv|
      schema.graphql
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^helm/snapshots/
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
        exclude: ^helm/snapshots/
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      # Linter
      - id: ruff-check
        args: [ --fix ]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.1
    hooks:
      - id: gitleaks

  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.398
  #   hooks:
  #     - id: pyright
  #       additional_dependencies:
  #         [
  #           beartype,
  #           einops,
  #           jax,
  #           jaxtyping,
  #           optax,
  #           pytest,
  #           typing_extensions,
  #           wadler_lindig,
  #         ]

# TODO: Setup https://pre-commit.ci/
# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
# ci:
#   autoupdate_schedule: weekly
#   skip: []
#   submodules: false
