
x-s3: &s3-env
  USE_S3_BUCKET: ${USE_S3_BUCKET:-true}
  AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID:-dev_user}
  AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY:-dev_pass}
  AWS_S3_REGION: ${AWS_S3_REGION:-us-east-1}
  EXTERNAL_S3_BUCKET_NAME: ${EXTERNAL_S3_BUCKET_NAME:-helix-data}
  S3_BUCKET_NAME : ${S3_BUCKET_NAME:-helix-data}
  AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-http://minio:9000}
  AWS_S3_BUCKET_NAME_STATIC: ${AWS_S3_BUCKET_NAME_STATIC:-my-static-bucket}
  AWS_S3_BUCKET_NAME_MEDIA: ${AWS_S3_BUCKET_NAME_MEDIA:-my-media-bucket}
  AWS_S3_ADDRESSING_STYLE: ${AWS_S3_ADDRESSING_STYLE:-path}
  AWS_S3_SIGNATURE_VERSION: ${AWS_S3_SIGNATURE_VERSION:-s3v4}
  S3_OBJECT_PRESIGNED_URL_TTL: ${S3_OBJECT_PRESIGNED_URL_TTL:-3600}

x-minio: &minio-env
  MINIO_ROOT_USER: ${AWS_S3_ACCESS_KEY_ID:-dev_user}
  MINIO_ROOT_PASSWORD: ${AWS_S3_SECRET_ACCESS_KEY:-dev_pass}

x-server: &base_server_setup
  environment: &base_server_environment
    <<: [*s3-env, *minio-env]
    HELIX_ENVIRONMENT: development
    DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
    ENABLE_DEBUG_TOOLBAR: ${ENABLE_DEBUG_TOOLBAR:-False}  # Used for DEBUG TOOLBAR, TODO: REMOVE
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-STATIC-INSECURE-KEY-PLEASE-DONT-USE-IN-PRODUCTION}
    DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST:-localhost,host.docker.internal}
    BACKEND_BASE_URL: ${BACKEND_BASE_URL:-http://localhost:9000}
    FRONTEND_BASE_URL: ${FRONTEND_BASE_URL:-http://localhost:3080}
    # Database (Default from db container)
    POSTGRES_HOST: ${POSTGRES_HOST:-db}
    POSTGRES_DB: ${POSTGRES_DB:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    # REDIS (Default from redis container)
    DJANGO_CACHE_REDIS_URL: ${DJANGO_CACHE_REDIS_URL:-redis://redis:6379/1}
    DJANGO_EXTERNAL_API_CACHE_REDIS_URL: ${DJANGO_EXTERNAL_API_CACHE_REDIS_URL:-redis://redis:6379/3}
    CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
    CELERY_RESULT_BACKEND_URL: ${CELERY_RESULT_BACKEND_URL:-redis://redis:6379/2}
    # Cookie config
    SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN:-localhost}
    CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN:-localhost}
    CORS_ORIGIN_REGEX_WHITELIST: ${CORS_ORIGIN_REGEX_WHITELIST:-^http://localhost:[\d\-]+$$|^http://localhost$$}
    # MISC
    HCAPTCHA_SECRET: ${HCAPTCHA_SECRET:-0x0000000000000000000000000000000000000000}
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./:/code
    - ipython_data_local:/root/.ipython/profile_default   # persist ipython data, including ipython history
  # restart: 'on-failure'
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
    minio:
      condition: service_healthy
    createbuckets:
      condition: service_completed_successfully
services:
  db:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    command: postgres -c log_statement=all
    volumes:
      - helix-db-17-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:6050:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p $$POSTGRES_PORT"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - helix-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 2s
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    <<: *base_server_setup
    image: helix/helix-server:latest
    restart: on-failure
    build:
      context: ./
      target: api
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - '9000:9000'
  celery:
    <<: *base_server_setup
    image: helix/helix-worker:latest
    restart: on-failure
    build:
      context: ./
      target: worker
    command: python manage.py run_celery_dev
    # Fix 100% CPU usage on archlinux (https://github.com/goauthentik/authentik/pull/7762)
    ulimits:
      nofile:
        soft: 10240
        hard: 10240

  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z.fips
    command: minio server /data --console-address ":9001"
    restart: on-failure
    ports:
      - "9002:9001"
      - "9003:9000"
    environment:
      <<: *minio-env
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9001/minio/health/live"]
      start_period: 2s
      interval: 30s
      timeout: 20s
      retries: 5

  createbuckets:
    image: minio/mc
    entrypoint: ["/bin/bash", "/usr/local/bin/createbuckets.sh"]
    restart: "no"
    environment:
      <<: [*minio-env, *s3-env]
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./scripts/createbuckets.sh:/usr/local/bin/createbuckets.sh:ro

volumes:
  helix-db-17-data:
  helix-redis-data:
  ipython_data_local:
  miniodata:
