services:
  server:
    image: $DOCKER_IMAGE_SERVER
    environment:
      CI: "true"
      USE_S3_BUCKET: ${USE_S3_BUCKET:-true}
      PYTEST_ADDOPTS: "--color=yes"
      HELIX_ENVIRONMENT: development
    volumes:
      - ./ci-share/:/ci-share/
  minio:
      volumes:
        - /data
