# Generated by Django 3.0.5 on 2020-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201201_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='body',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
    ]
