# Generated by Django 3.0.5 on 2021-05-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='strata_id',
        ),
    ]
