# Generated by Django 3.0.5 on 2021-10-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_merge_20211008_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='age_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='strata_id',
        ),
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Age'),
        ),
    ]
