# Generated by Django 3.0.5 on 2022-10-28 05:21

import apps.review.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0074_auto_20220823_0535'),
        ('event', '0022_auto_20221028_0521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0008_auto_20211020_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('field', django_enumfield.db.fields.EnumField(blank=True, enum=apps.review.models.UnifiedReviewComment.ReviewFieldType, null=True)),
                ('comment_type', django_enumfield.db.fields.EnumField(default=2, enum=apps.review.models.UnifiedReviewComment.ReviewCommentStatus)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is edited?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unifiedreviewcomment', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reviews', to='event.Event', verbose_name='Event')),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figure_review_comments', to='entry.Figure', verbose_name='Figure')),
                ('geo_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_location_review_comments', to='entry.OSMName', verbose_name='Geolocation/OSM')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
