# Generated by Django 3.0.5 on 2022-10-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20221031_1155'),
        ('entry', '0074_auto_20220823_0535'),
        ('review', '0009_unifiedreviewcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedreviewcomment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to='event.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='unifiedreviewcomment',
            name='figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figure_review_comments', to='entry.Figure', verbose_name='Figure'),
        ),
    ]
