# Generated by Django 3.0.5 on 2022-11-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0076_auto_20221103_0340'),
        ('review', '0010_auto_20221031_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figure_reviews', to='review.ReviewComment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_reviews', to='entry.Entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='review',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figure_reviews', to='entry.OSMName', verbose_name='Geolocation/OSM'),
        ),
    ]
