# Generated by Django 3.2 on 2025-03-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0103_auto_20250331_0625'),
        ('review', '0012_auto_20240326_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figure_reviews', to='entry.figurelocation', verbose_name='Geolocation'),
        ),
        migrations.AlterField(
            model_name='unifiedreviewcomment',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_location_review_comments', to='entry.figurelocation', verbose_name='Geolocation'),
        ),
    ]
