# Generated by Django 3.0.5 on 2021-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextualupdate', '0002_auto_20210323_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualupdate',
            name='article_title',
            field=models.TextField(verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='contextualupdate',
            name='idmc_analysis',
            field=models.TextField(null=True, verbose_name='Trends and patterns of displacement to be highlighted'),
        ),
    ]
