# Generated by Django 3.0.5 on 2021-10-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contextualupdate', '0003_auto_20210928_0747'),
        ('contextualupdate', '0003_auto_20211008_0732'),
    ]

    operations = [
    ]
