# Generated by Django 3.0.5 on 2021-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextualupdate', '0004_merge_20211008_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualupdate',
            name='article_title',
            field=models.TextField(verbose_name='Event Title'),
        ),
    ]
