# Generated by Django 3.0.5 on 2022-07-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0011_enable_unaccent_extension'),
        ('contextualupdate', '0005_auto_20211009_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualupdate',
            name='preview',
            field=models.ForeignKey(blank=True, help_text='After the preview has been generated pass its id along during entry creation, so that during entry update the preview can be obtained.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextual_update', to='contrib.SourcePreview'),
        ),
    ]
