# Generated by Django 3.2 on 2024-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contextualupdate', '0006_auto_20220703_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
