# /// script
# requires-python = "~=3.8.0"
# dependencies = [
#   "pydantic-settings",
#   "pyhelix",
#   "openpyxl",
#   "colorlog",
# ]
#
# [tool.uv.sources]
# pyhelix = { path = "../", editable = true }
#
# ///

from __future__ import annotations

import itertools
import json
import logging
import logging.config
import pathlib
import sys
import typing
import uuid

import typing_extensions
from openpyxl import load_workbook
from openpyxl.worksheet.worksheet import Worksheet
from pydantic import ValidationError
from pydantic_settings import BaseSettings, SettingsConfigDict

from pyhelix.api.api import HelixClient, HelixEndpoint
from pyhelix.api_types import HulkBulkImportState
from pyhelix.constants import CRISIS_TYPE
from pyhelix.hulk import HulkDataHandler
from pyhelix.models import (
    HulkAttachmentImport,
    HulkEntryImport,
    HulkEntryImportTypeEnum,
    HulkEventImport,
    HulkFigureImport,
    HulkFigureImportLocation,
    HulkSourcePreviewImport,
)
from pyhelix.parsers import validate_and_parse_enum

logger = logging.getLogger(__name__)


BASE_DIR = pathlib.Path(__file__).parent
IMPORT_DATASET_DIR = BASE_DIR / "dataset"
OUTPUT_DATASET_DIR = BASE_DIR / "generated"
OUTPUT_DATASET_DIR.mkdir(exist_ok=True)

ENTRY_RAW_FILE = IMPORT_DATASET_DIR / "entry.json"
EVENTS_RAW_FILE = IMPORT_DATASET_DIR / "events.xlsx"
FIGURES_RAW_FILE = IMPORT_DATASET_DIR / "figures.xlsx"


LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "colored": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s[%(levelname)s]%(reset)s %(red)s%(name)-8s%(reset)s %(message)s",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_red",
            },
        },
    },
    "handlers": {
        "console": {
            "class": "colorlog.StreamHandler",
            "formatter": "colored",
            "level": "INFO",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


logging.config.dictConfig(LOGGING_CONFIG)


def _force_utf8_console() -> None:
    """
    The dataset carries place names and narratives in any script. A console whose
    encoding cannot represent them (cp1252 on a default Windows install) turns
    every log line quoting one into a logging error, so force UTF-8 output and
    degrade unrepresentable characters instead of failing.
    """
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="backslashreplace")


_force_utf8_console()


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=BASE_DIR / ".env", env_file_encoding="utf-8")

    HELIX_BASE_DOMAIN: str = HelixEndpoint.BaseDomain.PRODUCTION
    HELIX_EMAIL: str
    HELIX_PASSWORD: str
    # Trigger triggerHulkBulkImport and download success/failure artifacts
    # after the JSONL files are generated. Disable to do a dry-run that only
    # writes local JSONL.
    HELIX_SEND_TO_HELIX: bool = True
    HELIX_BULK_TIMEOUT: float = 10 * 60  # 10min (Make sure to keep this higher as possible)
    HELIX_BULK_POLL_INTERVAL: float = 5.0
    # Optional: comma-separated emails of existing active helix users. When set,
    # rows generated by this run are round-robin tagged with these users' PKs in
    # ``impersonate_as`` so helix attributes the created records to them instead
    # of HELIX_EMAIL. Example: ``HELIX_IMPERSONATE_EMAILS=a@x.org,b@x.org``.
    HELIX_IMPERSONATE_EMAILS: str = ""

    def impersonate_emails(self) -> typing.List[str]:
        return [e.strip() for e in self.HELIX_IMPERSONATE_EMAILS.split(",") if e.strip()]


def read_from_sheet(sheet: Worksheet, header_row=1, max_col=None) -> typing.Generator[dict[typing.Any, typing.Any]]:
    iter_rows = sheet.iter_rows(min_row=header_row, max_col=max_col, values_only=True)
    headers = next(iter_rows)
    for row in iter_rows:
        yield {header: row[i] for i, header in enumerate(headers)}


class ImportContext(typing.NamedTuple):
    helix_client: HelixClient
    entries_map: dict[str, uuid.UUID] = {}
    events_map: dict[str, typing.Tuple[uuid.UUID, CRISIS_TYPE]] = {}
    # Returns the User PK to set on the next row's ``impersonate_as``. Default
    # always returns None — helix then falls back to the user who triggered the
    # bulk import (HELIX_EMAIL). When HELIX_IMPERSONATE_EMAILS is set, ``main``
    # wires this to round-robin across the configured users so rows are
    # distributed across them.
    next_impersonate_as: typing.Callable[[], typing.Optional[int]] = lambda: None


class MainTriggerResult(typing.TypedDict):
    violence_sub_type_id: int | None
    disaster_sub_type_id: int | None
    other_sub_type_id: int | None


def parse_main_trigger(context: ImportContext, cause: CRISIS_TYPE, main_trigger) -> MainTriggerResult:
    violence_sub_type_id = None
    disaster_sub_type_id = None
    other_sub_type_id = None

    if cause == CRISIS_TYPE.CONFLICT:
        violence_sub_type = context.helix_client.violence_sub_type_manager.search(main_trigger)
        violence_sub_type_id = violence_sub_type.id if violence_sub_type else None
    elif cause == CRISIS_TYPE.DISASTER:
        disaster_sub_type = context.helix_client.disaster_sub_type_manager.search(main_trigger)
        disaster_sub_type_id = disaster_sub_type.id if disaster_sub_type else None
    elif cause == CRISIS_TYPE.OTHER:
        other_sub_type = context.helix_client.other_sub_type_manager.search(main_trigger)
        other_sub_type_id = other_sub_type.id if other_sub_type else None
    else:
        typing_extensions.assert_never(cause)

    return {
        "violence_sub_type_id": violence_sub_type_id,
        "disaster_sub_type_id": disaster_sub_type_id,
        "other_sub_type_id": other_sub_type_id,
    }


def import_entry(hulk_handler: HulkDataHandler, context: ImportContext):
    with ENTRY_RAW_FILE.open("r", encoding="utf-8") as fp:
        entry_data = json.load(fp)

    for hulk_import_type in [
        HulkEntryImportTypeEnum.URL,
        HulkEntryImportTypeEnum.DOCUMENT,
    ]:
        publishers_id = []
        for publisher in entry_data["publishers"].split(","):
            publisher_entity = context.helix_client.organization_manager.search(publisher)
            if publisher_entity:
                publishers_id.append(publisher_entity.id)
                continue
            # TODO: Do we treat this as error
            logger.warning("Organization not found for <%s>", publisher)

        source_preview_uuid = None
        attachment_uuid = None
        url = None
        if hulk_import_type == HulkEntryImportTypeEnum.URL:
            # TODO: Use separate uuid for source_preview to avoid conflict?
            source_preview_uuid = entry_data["uuid"]
            url = entry_data["url"]
            try:
                source_preview_import = HulkSourcePreviewImport(
                    uuid=source_preview_uuid,
                    file_url=entry_data["url"],
                    impersonate_as=context.next_impersonate_as(),
                )
                hulk_handler.handle_import_object(source_preview_import)
            except ValidationError as e:
                hulk_handler.handle_import_error(HulkSourcePreviewImport, e)
                continue
        else:
            # TODO: Use separate uuid for source_preview to avoid conflict?
            attachment_uuid = entry_data["uuid"]
            try:
                attachment_import = HulkAttachmentImport(
                    uuid=attachment_uuid,
                    file_url=entry_data["url"],  # XXX: This should be a s3 url
                    impersonate_as=context.next_impersonate_as(),
                )
                hulk_handler.handle_import_object(attachment_import)
            except ValidationError as e:
                hulk_handler.handle_import_error(HulkAttachmentImport, e)
                return

        try:
            entry_import = HulkEntryImport(
                uuid=entry_data["uuid"],
                hulk_import_type=hulk_import_type,
                source_preview_uuid=source_preview_uuid,
                attachment_uuid=attachment_uuid,
                url=url,
                entry_title=entry_data["entry_title"],
                is_confidential=entry_data["confidential_source"] == 1,
                publish_date=entry_data["publication_date"],
                publishers_id=publishers_id,
                impersonate_as=context.next_impersonate_as(),
                extra_context={
                    "publishers": entry_data["publishers"],
                },
            )
            hulk_handler.handle_import_object(entry_import)
        except ValidationError as e:
            hulk_handler.handle_import_error(HulkEntryImport, e)
            return

        context.entries_map.update(
            {
                entry_import.entry_title: entry_import.uuid,
            }
        )


def import_events(hulk_handler: HulkDataHandler, context: ImportContext):
    with EVENTS_RAW_FILE.open("rb") as payload:
        workbook = load_workbook(payload, data_only=True, read_only=True)

        sheet = workbook.active
        assert sheet is not None, f"There is no sheet in {EVENTS_RAW_FILE}"

        for event_data in read_from_sheet(sheet):
            event_cause = validate_and_parse_enum(CRISIS_TYPE, event_data["event_cause"])

            if event_cause is None:
                logger.error("Event cause should be valid: %s", event_cause)
                continue

            main_trigger_metadata = parse_main_trigger(context, event_cause, event_data["main_trigger"])

            countries_id = []
            for country in event_data["countries"].split(","):
                country_entity = context.helix_client.country_manager.search(country)
                if country_entity:
                    countries_id.append(country_entity.id)
                    continue
                # TODO: Treat this as error?
                logger.warning("Country not found for <%s>", country)

            try:
                event_import = HulkEventImport(
                    uuid=event_data["uuid"],
                    event_name=event_data["event_name"],
                    event_cause=event_cause,
                    violence_sub_type_id=main_trigger_metadata["violence_sub_type_id"],
                    disaster_sub_type_id=main_trigger_metadata["disaster_sub_type_id"],
                    other_sub_type_id=main_trigger_metadata["other_sub_type_id"],
                    start_date=event_data["start_date"],
                    start_date_accuracy=event_data["start_date_accuracy"],
                    end_date=event_data["end_date"],
                    end_date_accuracy=event_data["end_date_accuracy"],
                    event_narrative=event_data["event_narrative"],
                    countries_id=countries_id,
                    event_codes=[],  # TODO
                    impersonate_as=context.next_impersonate_as(),
                    extra_context={
                        "countries": event_data["countries"],
                        "main_trigger": event_data["main_trigger"],
                    },
                )
                hulk_handler.handle_import_object(event_import)
            except ValidationError as e:
                hulk_handler.handle_import_error(HulkEventImport, e)
                continue

            context.events_map.update(
                {
                    event_import.event_name: (
                        event_import.uuid,
                        event_cause,
                    ),
                }
            )


def import_figures(hulk_handler: HulkDataHandler, context: ImportContext):
    with FIGURES_RAW_FILE.open("rb") as payload:
        workbook = load_workbook(payload, data_only=True, read_only=True)

        sheet = workbook.active
        assert sheet is not None, f"There is no sheet in {FIGURES_RAW_FILE}"

        entry_uuid = list(context.entries_map.values())[0]

        assert entry_uuid is not None, "entry not found"

        for figure_data in read_from_sheet(sheet):
            figure_uuid = figure_data["uuid"]

            event_raw = figure_data["event"]
            event_metadata = context.events_map.get(event_raw)
            if event_metadata is None:
                hulk_handler.handle_import_error_raw(
                    HulkFigureImport,
                    {
                        "uuid": figure_uuid,
                        "error": f"event_uuid not found for: {event_raw}",
                    },
                )
                continue

            figure_cause_raw = figure_data["figure_cause"]
            figure_cause = validate_and_parse_enum(CRISIS_TYPE, figure_cause_raw)
            if figure_cause is None:
                hulk_handler.handle_import_error_raw(
                    HulkFigureImport,
                    {
                        "uuid": figure_uuid,
                        "error": f"figure_cause not found for: {figure_cause_raw}",
                    },
                )
                continue

            main_trigger_metadata = parse_main_trigger(context, figure_cause, figure_data["main_trigger_figure"])

            country_raw = figure_data["country"]
            country_entity = context.helix_client.country_manager.search(country_raw)
            if country_entity is None:
                hulk_handler.handle_import_error_raw(
                    HulkFigureImport,
                    {
                        "uuid": figure_uuid,
                        "error": f"country not found for: {country_raw}",
                    },
                )
                continue
            country_iso2 = country_entity.iso2
            if country_iso2 is None:
                hulk_handler.handle_import_error_raw(
                    HulkFigureImport,
                    {
                        "uuid": figure_uuid,
                        "error": f"country iso2 not found for: {country_raw}",
                    },
                )
                continue

            organizations_raw = json.loads(figure_data["sources"])
            organizations_id = []
            for organization_raw in organizations_raw:
                organization_entity = context.helix_client.organization_manager.search(organization_raw)
                if organization_entity:
                    organizations_id.append(organization_entity.id)
                    continue
                # TODO: Treat this as error?
                logger.warning("Organization not found for <%s>", organization_raw)

            figure_tags_raw = json.loads(figure_data["tags"])
            figure_tags_id = []
            for figure_tag_raw in figure_tags_raw:
                figure_tag_entity = context.helix_client.figure_tag_manager.search(figure_tag_raw)
                if figure_tag_entity:
                    figure_tags_id.append(figure_tag_entity.id)
                    continue
                # TODO: Treat this as error?
                logger.warning("FigureTag not found for <%s>", figure_tag_raw)

            try:
                figure_locations = [
                    HulkFigureImportLocation(
                        uuid=loc_uuid,
                        bounding_box=None,
                        display_name=loc_display_name,
                        country_name=country_raw,
                        country_code=country_iso2,
                        identifier=loc_identifier,
                        accuracy=loc_accuracy,
                        geocoder=loc_geocoder,
                        latitude=loc_latitude,
                        longitude=loc_longitude,
                        # p-code fields (optional). This example has no gazetteer, so
                        # these are illustrative: pcode_source is free text, and
                        # pcode_accuracy is one of PCODE_ACCURACY (ADM0..ADM5).
                        pcode=f"{country_iso2}-SAMPLE",
                        pcode_source="OCHA_COD",
                        pcode_accuracy="ADM0",
                    )
                    for (
                        loc_uuid,
                        loc_display_name,
                        loc_identifier,
                        loc_accuracy,
                        _,
                        loc_latitude,
                        loc_longitude,
                        loc_geocoder,
                    ) in json.loads(figure_data["location"])
                ]

                figure_import = HulkFigureImport(
                    uuid=figure_uuid,
                    entry_uuid=entry_uuid,
                    event_uuid=event_metadata[0],
                    figure_cause=figure_cause,
                    violence_sub_type_id=main_trigger_metadata["violence_sub_type_id"],
                    context_of_violences_id=[],  # TODO
                    osv_sub_type_id=None,  # TODO
                    disaster_sub_type_id=main_trigger_metadata["disaster_sub_type_id"],
                    other_sub_type_id=main_trigger_metadata["other_sub_type_id"],
                    category=figure_data["category"],
                    term=figure_data["term"],
                    quantifier=figure_data["quantifier"],
                    unit=figure_data["unit"],
                    figure_role=figure_data["figure_role"],
                    country_id=country_entity.id,
                    start_date=figure_data["start_date"],
                    start_date_accuracy=figure_data["start_date_accuracy"],
                    end_date=figure_data["end_date"],
                    end_date_accuracy=figure_data["end_date_accuracy"],
                    stock_date=figure_data["stock_date"],
                    stock_date_accuracy=figure_data["stock_date_accuracy"],
                    stock_reporting_date=figure_data["stock_reporting_date"],
                    reported_figure=figure_data["reported_figure"],
                    is_housing_destruction=int(figure_data["housing_destruction_toggle"] or 0) == 1,
                    household_size=figure_data["household_size"],
                    displacement_occurred=figure_data["displacement_occured"],
                    is_disaggregated=figure_data["disaggregation_available"],
                    analysis_text=figure_data["analysis_text"],
                    source_excerpt_text=figure_data["source_excerpt_text"],
                    include_idu=figure_data["include_IDU"],
                    idu_text=figure_data["idu_text"],
                    tags_id=figure_tags_id,
                    sources_id=organizations_id,
                    locations=figure_locations,
                    impersonate_as=context.next_impersonate_as(),
                    extra_context={
                        "main_trigger": figure_data["main_trigger_figure"],
                    },
                )
                hulk_handler.handle_import_object(figure_import)
            except ValidationError as e:
                hulk_handler.handle_import_error(HulkFigureImport, e)
                continue


def _log_bulk_progress(state: HulkBulkImportState) -> None:
    logger.info(
        "HulkBulkImport %s status=%s success=%s failure=%s",
        state.id,
        state.status_display or state.status.name,
        state.success_count,
        state.failure_count,
    )


def send_to_helix(hulk_handler: HulkDataHandler, settings: Settings) -> None:
    try:
        run = hulk_handler.send_to_helix()
    except RuntimeError as e:
        # Raised when every JSONL is empty — nothing to upload.
        logger.error("Skipping helix upload: %s", e)
        return

    logger.info("Triggered HulkBulkImport id=%s; polling until terminal status…", run.bulk_id)
    final_state = run.wait(
        timeout=settings.HELIX_BULK_TIMEOUT,
        poll_interval=settings.HELIX_BULK_POLL_INTERVAL,
        progress_cb=_log_bulk_progress,
    )
    logger.info(
        "HulkBulkImport %s finished with status=%s",
        run.bulk_id,
        final_state.status_display or final_state.status.name,
    )

    for dataset in final_state.datasets or []:
        print(f"{dataset.import_type} success={dataset.success_count} failure={dataset.failure_count}")

    artifacts = run.download_artifacts(OUTPUT_DATASET_DIR / f"helix_{run.bulk_id}")
    artifacts_serializable = {
        resource: {kind: str(path) if path else None for kind, path in entry.items()}
        for resource, entry in artifacts.items()
    }
    print(json.dumps({"bulk_id": run.bulk_id, "artifacts": artifacts_serializable}, indent=2))


def main():
    settings = Settings()

    helix_client = HelixClient(
        endpoint=HelixEndpoint(
            base_domain=settings.HELIX_BASE_DOMAIN,
            email=settings.HELIX_EMAIL,
            password=settings.HELIX_PASSWORD,
        ),
    )
    helix_client.login()

    def next_impersonate_as() -> typing.Optional[int]:
        return None

    impersonate_emails = settings.impersonate_emails()
    if impersonate_emails:
        resolved: typing.List[typing.Tuple[str, int]] = []
        for email in impersonate_emails:
            pk = helix_client.user_manager.search_by_email(email)
            if pk is None:
                raise RuntimeError(f"HELIX_IMPERSONATE_EMAILS entry {email!r} did not match any active helix user")
            resolved.append((email, pk))
        logger.info("Round-robin impersonating helix users: %s", resolved)
        cycle = itertools.cycle(pk for _, pk in resolved)

        def next_impersonate_as() -> typing.Optional[int]:
            return next(cycle)

    with HulkDataHandler(export_dir=OUTPUT_DATASET_DIR, helix_client=helix_client) as hulk_handler:
        context = ImportContext(helix_client=helix_client, next_impersonate_as=next_impersonate_as)

        data_generators: list[typing.Callable[[HulkDataHandler, ImportContext],]] = [
            # Order matters
            import_entry,
            import_events,
            import_figures,
        ]
        for data_generator in data_generators:
            data_generator(hulk_handler, context)

        # NOTE: Just for verbose information about the outputs
        print(json.dumps(hulk_handler.debug_metadata(), indent=2))

        if settings.HELIX_SEND_TO_HELIX:
            send_to_helix(hulk_handler, settings)
        else:
            logger.info("HELIX_SEND_TO_HELIX is false; skipping upload to helix.")


main()
