# Generated by Django 3.0.5 on 2021-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210220_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('sign_off_report', 'Can sign off the report'),)},
        ),
        migrations.AlterField(
            model_name='report',
            name='figure_end_before',
            field=models.DateField(null=True, verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='figure_start_after',
            field=models.DateField(null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Reported Figures'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='masterfact_reports', to='report.Report', verbose_name='Reports (old groups)'),
        ),
    ]
