# Generated by Django 3.0.5 on 2021-02-26 06:41

import apps.report.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210225_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_from',
            field=django_enumfield.db.fields.EnumField(blank=True, editable=False, enum=apps.report.models.Report.REPORT_TYPE, null=True),
        ),
    ]
