# Generated by Django 3.0.5 on 2021-03-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210227_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('sign_off_report', 'Can sign off the report'), ('approve_report', 'Can approve the report'))},
        ),
    ]
