# Generated by Django 3.0.5 on 2021-03-02 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_auto_20210302_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSignOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('full_report', utils.fields.CachedFileField(blank=True, null=True, upload_to='reports/full', verbose_name='full report')),
                ('snapshot', utils.fields.CachedFileField(blank=True, null=True, upload_to='reports/snaps', verbose_name='report snapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reportsignoff', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_offs', to='report.Report', verbose_name='Report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
