# Generated by Django 3.0.5 on 2021-03-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_auto_20210304_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_off_reports', to=settings.AUTH_USER_MODEL, verbose_name='Last signed off by'),
        ),
        migrations.CreateModel(
            name='ReportApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='report.ReportGeneration', verbose_name='Report')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'unique_together': {('generation', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='approvers',
            field=models.ManyToManyField(related_name='approved_generations', through='report.ReportApproval', to=settings.AUTH_USER_MODEL, verbose_name='Approvers'),
        ),
    ]
