# Generated by Django 3.0.5 on 2021-03-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_reportgeneration_status'),
        ('report', '0010_reportgeneration_is_signed_off_on'),
    ]

    operations = [
    ]
