# Generated by Django 3.0.5 on 2021-03-17 08:11

import apps.report.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_merge_20210315_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportgeneration',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='include_history',
            field=models.BooleanField(default=False, help_text='Including history will take good amount of time.', verbose_name='Include History'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_from',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.report.models.Report.REPORT_TYPE, null=True),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.report.models.ReportGeneration.REPORT_GENERATION_STATUS),
        ),
    ]
