# Generated by Django 3.0.5 on 2021-03-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_merge_20210315_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportgeneration',
            options={'ordering': ('-created_at',)},
        ),
    ]
