# Generated by Django 3.0.5 on 2021-03-16 05:30

import apps.report.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20210316_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_from',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.report.models.Report.REPORT_TYPE, null=True),
        ),
    ]
