# Generated by Django 3.0.5 on 2021-03-17 11:22

import apps.report.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20210317_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_from',
            field=django_enumfield.db.fields.EnumField(blank=True, editable=False, enum=apps.report.models.Report.REPORT_TYPE, null=True),
        ),
    ]
