# Generated by Django 3.0.5 on 2021-03-26 04:40

import apps.report.models
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210317_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgeneration',
            name='full_report',
            field=utils.fields.CachedFileField(blank=True, null=True, upload_to=apps.report.models.full_report_upload_to, verbose_name='full report'),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='snapshot',
            field=utils.fields.CachedFileField(blank=True, null=True, upload_to=apps.report.models.snapshot_report_upload_to, verbose_name='report snapshot'),
        ),
    ]
