# Generated by Django 3.0.5 on 2021-03-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_countrypopulation'),
        ('report', '0014_auto_20210326_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_figure_geographical_groups',
            field=models.ManyToManyField(blank=True, related_name='_report_filter_figure_geographical_groups_+', to='country.GeographicalGroup', verbose_name='Geographical Group'),
        ),
    ]
