# Generated by Django 3.0.5 on 2021-03-17 05:04

import apps.report.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_reportgeneration_include_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgeneration',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.report.models.ReportGeneration.REPORT_GENERATION_STATUS),
        ),
    ]
