# Generated by Django 3.0.5 on 2021-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210330_0905'),
        ('organization', '0006_auto_20201231_0707'),
        ('report', '0015_report_filter_figure_geographical_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_entry_publishers',
            field=models.ManyToManyField(blank=True, related_name='published_report', to='organization.Organization', verbose_name='Publishers'),
        ),
        migrations.AddField(
            model_name='report',
            name='filter_entry_sources',
            field=models.ManyToManyField(blank=True, related_name='sourced_report', to='organization.Organization', verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='report',
            name='filter_events',
            field=models.ManyToManyField(blank=True, to='event.Event', verbose_name='Events'),
        ),
    ]
