# Generated by Django 3.0.5 on 2021-05-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_report_filter_entry_review_status'),
        ('report', '0016_auto_20210429_1009'),
    ]

    operations = [
    ]
