# Generated by Django 3.0.5 on 2021-05-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_merge_20210512_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='disaggregation_strata_json',
        ),
    ]
