# Generated by Django 3.0.5 on 2021-08-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_report_filter_figure_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='disaggregation_disability',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Disability'),
        ),
        migrations.AddField(
            model_name='report',
            name='disaggregation_indigenous_people',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Indigenous people'),
        ),
        migrations.AddField(
            model_name='report',
            name='disaggregation_lgbtiq',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='LGBTIQ+'),
        ),
    ]
