# Generated by Django 3.0.5 on 2021-09-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20210830_0623'),
        ('report', '0020_auto_20210824_0416'),
    ]

    operations = [
    ]
