# Generated by Django 3.0.5 on 2021-10-01 05:30

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20210929_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False),
        )
    ]
