# Generated by Django 3.0.5 on 2021-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20211002_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filter_entry_article_title',
            field=models.TextField(blank=True, null=True, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_event_glide_number',
            field=models.TextField(blank=True, null=True, verbose_name='Event Code'),
        ),
    ]
