# Generated by Django 3.0.5 on 2021-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_merge_20211008_0953'),
        ('report', '0028_auto_20211008_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_event_violence_sub_types',
            field=models.ManyToManyField(blank=True, to='event.ViolenceSubType', verbose_name='Violence Sub Type'),
        ),
        migrations.AddField(
            model_name='report',
            name='filter_event_violence_types',
            field=models.ManyToManyField(blank=True, to='event.Violence', verbose_name='Violence Type'),
        ),
    ]
