# Generated by Django 3.0.5 on 2021-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0059_auto_20211019_0701'),
        ('report', '0030_auto_20211009_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='disaggregation_age_json',
        ),
        migrations.AddField(
            model_name='report',
            name='disaggregation_age',
            field=models.ManyToManyField(blank=True, related_name='report_report_related', to='entry.DisaggregatedAge', verbose_name='Disaggregated age'),
        ),
    ]
