# Generated by Django 3.0.5 on 2021-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_report_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_entry_has_disaggregated_data',
            field=models.NullBooleanField(default=None, verbose_name='Has disaggregated data'),
        ),
    ]
