# Generated by Django 3.0.5 on 2021-10-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_report_filter_entry_has_disaggregated_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filter_figure_sex_types',
        ),
    ]
