# Generated by Django 3.0.5 on 2022-04-07 06:51

import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_remove_report_filter_figure_sex_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filter_figure_categories',
        ),
        migrations.AddField(
            model_name='report',
            name='filter_figure_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES), blank=True, null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='report',
            name='filter_figure_terms',
        ),
        migrations.AddField(
            model_name='report',
            name='filter_figure_terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.FIGURE_TERMS), blank=True, null=True, size=None),
        ),
    ]
