# Generated by Django 3.0.5 on 2021-11-16 04:51

import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0036_auto_20211112_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filter_figure_terms',
        ),
        migrations.AddField(
            model_name='report',
            name='filter_figure_terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.FIGURE_TERMS), blank=True, null=True, size=None),
        ),
    ]
