# Generated by Django 3.0.5 on 2022-05-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0036_report_filter_context_of_violence'),
        ('report', '0036_auto_20220519_1046'),
    ]

    operations = [
    ]
