# Generated by Django 3.0.5 on 2022-06-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_merge_20220524_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='filter_entry_has_disaggregated_data',
            new_name='filter_figure_has_disaggregated_data',
        ),
    ]
