# Generated by Django 3.0.5 on 2022-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0005_auto_20210330_0905'),
        ('report', '0038_auto_20220601_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_crisis_types',
            new_name='filter_figure_crisis_types',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_disaster_categories',
            new_name='filter_figure_disaster_categories',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_disaster_sub_categories',
            new_name='filter_figure_disaster_sub_categories',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_disaster_sub_types',
            new_name='filter_figure_disaster_sub_types',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_disaster_types',
            new_name='filter_figure_disaster_types',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_glide_number',
            new_name='filter_figure_glide_number',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_violence_sub_types',
            new_name='filter_figure_violence_sub_types',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='filter_event_violence_types',
            new_name='filter_figure_violence_types',
        ),
        migrations.RemoveField(
            model_name='report',
            name='filter_event_crises',
        ),
        migrations.AddField(
            model_name='report',
            name='filter_figure_crises',
            field=models.ManyToManyField(blank=True, related_name='_report_filter_figure_crises_+', to='crisis.Crisis', verbose_name='Crises'),
        ),
    ]
