# Generated by Django 3.0.14 on 2023-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_auto_20220613_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
    ]
