# Generated by Django 3.0.5 on 2022-07-04 01:10

import apps.report.models
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_auto_20220613_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgeneration',
            name='full_report',
            field=utils.fields.CachedFileField(blank=True, max_length=256, null=True, upload_to=apps.report.models.full_report_upload_to, verbose_name='full report'),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='snapshot',
            field=utils.fields.CachedFileField(blank=True, max_length=256, null=True, upload_to=apps.report.models.snapshot_report_upload_to, verbose_name='report snapshot'),
        ),
    ]
