# Generated by Django 3.0.5 on 2022-12-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0044_auto_20221130_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_is_figure_to_be_reviewed',
            field=models.NullBooleanField(default=None, verbose_name='Filter to be reviewed'),
        ),
    ]
