# Generated by Django 3.0.14 on 2023-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0045_report_filter_is_figure_to_be_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='public_figure_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Public figure analysis'),
        ),
    ]
