# Generated by Django 3.0.14 on 2023-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20230216_0726'),
        ('report', '0046_report_public_figure_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filter_figure_disaster_categories',
            field=models.ManyToManyField(blank=True, to='event.DisasterCategory', verbose_name='Filter Hazard Category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_disaster_sub_categories',
            field=models.ManyToManyField(blank=True, to='event.DisasterSubCategory', verbose_name='Filter Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_disaster_sub_types',
            field=models.ManyToManyField(blank=True, to='event.DisasterSubType', verbose_name='Filter Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_disaster_types',
            field=models.ManyToManyField(blank=True, to='event.DisasterType', verbose_name='Filter Hazard Type'),
        ),
    ]
