# Generated by Django 3.0.14 on 2023-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0047_auto_20230221_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_pfa_visible_in_gidd',
            field=models.BooleanField(default=False, verbose_name='Is public figure analysis visible in Gidd'),
        ),
    ]
