# Generated by Django 3.2 on 2023-04-04 04:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0047_auto_20230221_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disaggregation_strata_json',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(verbose_name='Stratum'), blank=True, null=True, size=None, verbose_name='Strata Disaggregation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_has_disaggregated_data',
            field=models.BooleanField(default=None, null=True, verbose_name='Has disaggregated data'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_is_figure_to_be_reviewed',
            field=models.BooleanField(default=None, null=True, verbose_name='Filter to be reviewed'),
        ),
    ]
