# Generated by Django 3.2 on 2023-04-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0048_auto_20230404_0458'),
        ('report', '0048_auto_20230424_0615'),
    ]

    operations = [
    ]
