# Generated by Django 3.2 on 2023-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0049_merge_0048_auto_20230404_0458_0048_auto_20230424_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gidd_report_year',
            field=models.PositiveIntegerField(null=True, verbose_name='Gidd report year'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_gidd_report',
            field=models.BooleanField(default=False, verbose_name='Is GIDD report'),
        ),
    ]
