# Generated by Django 3.2 on 2023-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_auto_20230425_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='gidd_report_year',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Gidd report year'),
        ),
    ]
