# Generated by Django 3.2 on 2023-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0051_alter_report_gidd_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_gidd_report',
            field=models.BooleanField(default=False, verbose_name='Is GIDD report?'),
        ),
    ]
