# Generated by Django 3.2 on 2023-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0052_alter_report_is_gidd_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='gidd_report_year',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='GIDD report year'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_pfa_visible_in_gidd',
            field=models.BooleanField(default=False, verbose_name='Is public figure analysis visible in GIDD'),
        ),
    ]
