# Generated by Django 4.0 on 2023-06-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_organization_created_by_and_more'),
        ('users', '0006_alter_user_first_name'),
        ('entry', '0092_alter_entry_created_by_and_more'),
        ('country', '0017_alter_contextualanalysis_created_by_and_more'),
        ('crisis', '0006_alter_crisis_created_by'),
        ('report', '0053_auto_20230429_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='disaggregation_age',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='entry.DisaggregatedAge', verbose_name='Disaggregated age'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_entry_publishers',
            field=models.ManyToManyField(blank=True, related_name='published_%(class)s', to='organization.Organization', verbose_name='Publishers'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_countries',
            field=models.ManyToManyField(blank=True, related_name='+', to='country.Country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_crises',
            field=models.ManyToManyField(blank=True, related_name='+', to='crisis.Crisis', verbose_name='Crises'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_geographical_groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='country.GeographicalGroup', verbose_name='Geographical Group'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_regions',
            field=models.ManyToManyField(blank=True, related_name='+', to='country.CountryRegion', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_sources',
            field=models.ManyToManyField(blank=True, related_name='sourced_%(class)s', to='organization.Organization', verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filter_figure_tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='entry.FigureTag', verbose_name='Figure Tags'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
    ]
