# Generated by Django 3.2 on 2023-08-17 05:17

from django.db import migrations

def update_new_gidd_fields(apps, schema_editor):
    Report = apps.get_model('report', 'Report')
    ReleaseMetadata = apps.get_model('gidd', 'ReleaseMetadata')
    PublicFigureAnalysis = apps.get_model('gidd', 'PublicFigureAnalysis')

    # Update gidd_published_date
    last_release_meta_data = ReleaseMetadata.objects.last()
    if last_release_meta_data:
        last_release_meta_data_date = last_release_meta_data.modified_at
        Report.objects.filter(is_gidd_report=True).update(gidd_published_date=last_release_meta_data_date)

        # Update is_pfa_visible_in_gidd
        for pfa in PublicFigureAnalysis.objects.all():
            pfa.report.gidd_published_date = last_release_meta_data_date
            pfa.report.is_pfa_published_in_gidd = True
            pfa.report.save(update_fields=['is_pfa_published_in_gidd'])


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0054_auto_20230817_0438'),
    ]

    operations = [
        migrations.RunPython(update_new_gidd_fields, reverse_code=migrations.RunPython.noop),
    ]
