# Generated by Django 3.2 on 2023-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0056_remove_report_filter_figure_displacement_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_figure_has_excerpt_idu',
            field=models.BooleanField(default=None, null=True, verbose_name='Has excerpt IDU'),
        ),
        migrations.AddField(
            model_name='report',
            name='filter_figure_has_housing_destruction',
            field=models.BooleanField(default=None, null=True, verbose_name='Has housing destruction'),
        ),
    ]
