# Generated by Django 3.2 on 2024-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0058_auto_20231208_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='change_in_data_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='change_in_methodology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='change_in_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='retroactive_change',
            field=models.BooleanField(default=False),
        ),
    ]
