# Generated by Django 3.2 on 2026-06-20 06:19

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0060_merge_0059_auto_20240326_0824_0059_auto_20240327_0937'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=True), name='report_created_at_desc_idx'),
        ),
    ]
