# Generated by Django 3.2 on 2024-05-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0060_merge_0059_auto_20240326_0824_0059_auto_20240327_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filter_figure_glide_number',
        ),
    ]
