kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "helix-backend.envConfigMapName" . }}
  labels:
    app: {{ include "helix-backend.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  APP_RELEASE: {{ .Values.image.tag | quote }}
  HELIX_ENVIRONMENT: {{ .Values.environment | quote | upper }}
  DJANGO_DEBUG: {{ required "env.DJANGO_DEBUG" .Values.env.DJANGO_DEBUG | quote }}

  # App Domain
  APP_DOMAIN: {{ required "env.APP_DOMAIN" .Values.env.APP_DOMAIN | quote }}
  DJANGO_ALLOWED_HOST: {{ required "env.DJANGO_ALLOWED_HOST" .Values.env.DJANGO_ALLOWED_HOST | quote }}
  SESSION_COOKIE_DOMAIN: {{ required "env.SESSION_COOKIE_DOMAIN" .Values.env.SESSION_COOKIE_DOMAIN | quote }}
  CSRF_COOKIE_DOMAIN: {{ required "env.CSRF_COOKIE_DOMAIN" .Values.env.CSRF_COOKIE_DOMAIN | quote }}
  BACKEND_BASE_URL: {{ required "env.BACKEND_BASE_URL" .Values.env.BACKEND_BASE_URL | quote }}
  FRONTEND_BASE_URL: {{ required "env.FRONTEND_BASE_URL" .Values.env.FRONTEND_BASE_URL | quote }}

  # Sentry
  SENTRY_SAMPLE_RATE: {{ required "env.SENTRY_SAMPLE_RATE" .Values.env.SENTRY_SAMPLE_RATE | quote }}
  SENTRY_PROFILES_SAMPLE_RATE: {{ required "env.SENTRY_PROFILES_SAMPLE_RATE" .Values.env.SENTRY_PROFILES_SAMPLE_RATE | quote }}

  # Additional configs
  {{- range $name, $value := .Values.envAdditional }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
