kind: Secret
apiVersion: v1
metadata:
  name: {{ template "helix-backend.secretname" . }}
  labels:
    app: {{ include "helix-backend.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY" .Values.secrets.DJANGO_SECRET_KEY | quote }}

  # Sentry
  SENTRY_DSN: {{ required "secrets.SENTRY_DSN" .Values.secrets.SENTRY_DSN | quote }}

  # Hcaptcha
  HCAPTCHA_SECRET: {{ required "secrets.HCAPTCHA_SECRET" .Values.secrets.HCAPTCHA_SECRET | quote }}

  # Redis
  {{- if .Values.redis.enabled }}
  CELERY_BROKER_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/0"
  DJANGO_CACHE_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/1"
  CELERY_RESULT_BACKEND_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/2"
  DJANGO_EXTERNAL_API_CACHE_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/3"
  {{- else }}
  CELERY_BROKER_URL: {{ required "env.CELERY_BROKER_URL" .Values.env.CELERY_BROKER_URL | quote }}
  DJANGO_CACHE_REDIS_URL: {{ required "env.DJANGO_CACHE_REDIS_URL" .Values.env.DJANGO_CACHE_REDIS_URL | quote }}
  CELERY_RESULT_BACKEND_URL: {{ required "env.CELERY_RESULT_BACKEND_URL" .Values.env.CELERY_RESULT_BACKEND_URL | quote }}
  DJANGO_EXTERNAL_API_CACHE_REDIS_URL: {{ required "env.DJANGO_EXTERNAL_API_CACHE_REDIS_URL" .Values.env.DJANGO_EXTERNAL_API_CACHE_REDIS_URL | quote }}
  {{- end }}

  # Database
  {{- if .Values.postgresql.enabled }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  POSTGRES_PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | quote }}
  {{- else }}
  POSTGRES_DB: {{ required "secrets.POSTGRES_DB" .Values.secrets.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ required "secrets.POSTGRES_USER" .Values.secrets.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ required "secrets.POSTGRES_PASSWORD" .Values.secrets.POSTGRES_PASSWORD | quote }}
  POSTGRES_HOST: {{ required "secrets.POSTGRES_HOST" .Values.secrets.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ required "secrets.POSTGRES_PORT" .Values.secrets.POSTGRES_PORT | quote }}
  {{- end }}

  # Minio
  {{- if .Values.minio.enabled }}
  USE_S3_BUCKET: "true"
  AWS_S3_AWS_ENDPOINT_URL: "https://{{ .Values.minio.apiIngress.hostname }}/"
  AWS_S3_ACCESS_KEY_ID: {{ required ".Values.minio.auth.rootUser" .Values.minio.auth.rootUser }}
  AWS_S3_SECRET_ACCESS_KEY: {{ required ".Values.minio.auth.rootPassword" .Values.minio.auth.rootPassword }}
  AWS_S3_REGION: "us-east-1"
  S3_BUCKET_NAME: "helix-data"
  EXTERNAL_S3_BUCKET_NAME: "helix-external-data"
  {{- end }}

  # Additional secrets
  {{- range $name, $value := .Values.secretsAdditional }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
