"""
codename will be built as <action>_<model> and used as...
Permission.objects.get(codename=<codename>)
"""

from .enums import ACTION, MODEL, ROLE

ROLES = [ROLE.ADMIN, ROLE.IT_HEAD, ROLE.MONITORING_EXPERT_EDITOR,
         ROLE.MONITORING_EXPERT_REVIEWER, ROLE.GUEST]

# All except user
ALL_MODELS = {MODEL.CRISIS, MODEL.EVENT, MODEL.ENTRY, MODEL.ORGANIZATION,
              MODEL.ORGANIZATION_KIND, MODEL.CONTACT, MODEL.COMMUNICATION,
              MODEL.FIGURE, MODEL.SUMMARY, MODEL.CONTEXTUAL_UPDATE,
              MODEL.RESOURCE}

# NOTE: To add custom permissions, add `bla_model` like `sign_off_model`.
PERMISSIONS = {
    ROLE.ADMIN: {
        ACTION.ADD: ALL_MODELS | {ROLE.USER},
        ACTION.CHANGE: ALL_MODELS | {ROLE.USER},
        ACTION.DELETE: ALL_MODELS | {ROLE.USER},
    },
    ROLE.IT_HEAD: {
        ACTION.ADD: ALL_MODELS,
        ACTION.CHANGE: ALL_MODELS,
        ACTION.DELETE: ALL_MODELS,
        ACTION.SIGN_OFF: {ROLE.ENTRY},
    },
    ROLE.MONITORING_EXPERT_EDITOR: {
        ACTION.ADD: ALL_MODELS,
        ACTION.CHANGE: ALL_MODELS,
        ACTION.DELETE: ALL_MODELS,
    },
    ROLE.MONITORING_EXPERT_REVIEWER: {
        ACTION.ADD: ALL_MODELS - {MODEL.ENTRY, MODEL.FIGURE},
        ACTION.CHANGE: ALL_MODELS - {MODEL.ENTRY, MODEL.FIGURE},
        ACTION.DELETE: ALL_MODELS - {MODEL.ENTRY, MODEL.FIGURE},
    },
    ROLE.GUEST: {
        ACTION.ADD: set(),
        ACTION.CHANGE: set(),
        ACTION.DELETE: set(),
    }
}
