# Generated by Django 3.2 on 2024-05-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_auto_20240326_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='glide_numbers',
        ),
    ]
