# Generated by Django 3.2 on 2026-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_auto_20240326_0824'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='event_event_name_f993f2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='event_event_event_t_df5a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='event_event_start_d_d4a35f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_date'], name='event_event_end_dat_18315b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date_accuracy'], name='event_event_start_d_35da07_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_date_accuracy'], name='event_event_end_dat_4006dc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['review_status'], name='event_event_review__d2f50c_idx'),
        ),
         migrations.AddIndex(
            model_name='contextofviolence',
            index=models.Index(fields=['name'], name='event_conte_name_2fb088_idx'),
        ),
    ]
