# Generated by Django 3.0.5 on 2020-10-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201019_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggersubtype',
            name='trigger',
        ),
    ]
