# Generated by Django 3.0.5 on 2020-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201118_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='old_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key'),
        ),
    ]
