# Generated by Django 3.0.5 on 2021-01-04 07:36
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201118_0445'),
    ]

    # Fix migration after moving EVENT_OTHER_SUB_TYPE to model
    # operations = [
    #     migrations.AddField(
    #         model_name='event',
    #         name='other_sub_type',
    #         # Fix migration after moving EVENT_OTHER_SUB_TYPE to common app
    #         field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.common.enums.EVENT_OTHER_SUB_TYPE, null=True),
    #     ),
    # ]
