# Generated by Django 3.0.5 on 2021-01-04 07:36

import apps.event.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201118_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_sub_type',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.event.models.Event.EVENT_OTHER_SUB_TYPE, null=True),
        ),
    ]
