# Generated by Django 3.0.5 on 2021-01-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_old_id'),
        ('event', '0006_auto_20201217_0544'),
    ]

    operations = [
    ]
