# Generated by Django 3.0.5 on 2021-01-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_merge_20210104_0920'),
        ('event', '0006_event_other_sub_type'),
    ]

    operations = [
    ]
