# Generated by Django 3.0.5 on 2021-08-03 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20210822_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='glide_number',
        ),
        migrations.AddField(
            model_name='event',
            name='glide_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Glide Number'), blank=True, default=[], null=True, size=None),
        ),
    ]
