# Generated by Django 3.0.5 on 2021-09-28 07:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20210825_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='disaster_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterSubCategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='disaster_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterSubType', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='glide_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Event Ids'), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='trigger_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.TriggerSubType', verbose_name='Trigger Sub Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='violence_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.ViolenceSubType', verbose_name='Violence Sub Type'),
        ),
    ]
