# Generated by Django 3.0.5 on 2022-04-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20220415_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trigger_sub_type',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.DeleteModel(
            name='TriggerSubType',
        ),
    ]
