# Generated by Django 3.0.5 on 2022-10-19 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0022_auto_20221013_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='event',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_assigner', to=settings.AUTH_USER_MODEL, verbose_name='Assigner'),
        ),
    ]
