# Generated by Django 3.0.5 on 2022-10-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20221028_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('assign_event', 'Can assign on event level'), ('self_assign_event', 'Can assign self on event level'))},
        ),
    ]
