# Generated by Django 3.0.5 on 2022-10-31 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0023_auto_20221031_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_assignee', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_assigner', to=settings.AUTH_USER_MODEL, verbose_name='Assigner'),
        ),
    ]
