# Generated by Django 3.0.5 on 2022-11-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20221031_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('assign_event', 'Can assign on event level'), ('self_assign_event', 'Can assign self on event level'), ('clear_assignee_event', 'Can clear any assignee from event'), ('clear_self_assignee_event', 'Can clear self assigned event'))},
        ),
    ]
