# Generated by Django 3.0.5 on 2022-11-03 03:40

import apps.event.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20221101_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review_status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.event.models.Event.EventReviewStatus),
        ),
    ]
