# Generated by Django 3.0.5 on 2022-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_event_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='include_triangulation_in_qa',
            field=models.BooleanField(default=False, verbose_name='Include triangulation in qa?'),
        ),
    ]
