# Generated by Django 3.0.5 on 2022-11-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_event_include_triangulation_in_qa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('assign_event', 'Can assign on event level'), ('self_assign_event', 'Can assign self on event level'), ('clear_assignee_event', 'Can clear any assignee from event'), ('clear_self_assignee_event', 'Can clear self assigned event'), ('sign_off_event', 'Can sign-off event'))},
        ),
    ]
