# Generated by Django 3.0.14 on 2023-02-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_update_parent_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disastersubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='event.DisasterCategory', verbose_name='Hazard Category'),
        ),
        migrations.AlterField(
            model_name='disastersubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='event.DisasterType', verbose_name='Hazard Type'),
        ),
        migrations.AlterField(
            model_name='disastertype',
            name='disaster_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='event.DisasterSubCategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='disaster_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterCategory', verbose_name='Hazard Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='disaster_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterSubCategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='disaster_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterSubType', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='disaster_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterType', verbose_name='Hazard Type'),
        ),
    ]
