# Generated by Django 3.2 on 2023-12-13 09:41

import apps.event.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_update_country_centroids'),
        ('event', '0032_delete_event_with_zero_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code_type', django_enumfield.db.fields.EnumField(enum=apps.event.models.EventCode.EVENT_CODE_TYPE)),
                ('event_code', models.CharField(max_length=256, verbose_name='Event Code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_code_country', to='country.country', verbose_name='Country')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_code', to='event.event', verbose_name='Event')),
            ],
            options={
                'ordering': ['event_code'],
            },
        ),
    ]
