# Generated by Django 3.2 on 2024-01-05 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_eventcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcode',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
