# Generated by Django 3.2 on 2026-06-20 05:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_alter_eventcode_uuid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=True), name='event_created_at_desc_idx'),
        ),
    ]
