# Generated by Django 3.2 on 2026-08-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_event_code_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='disastersubtype',
            name='idu_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='IDU name'),
        ),
        migrations.AddField(
            model_name='othersubtype',
            name='idu_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='IDU name'),
        ),
        migrations.AddField(
            model_name='violencesubtype',
            name='idu_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='IDU name'),
        ),
    ]
