# Generated by Django 3.0.5 on 2020-12-01 05:07

import apps.review.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=django_enumfield.db.fields.EnumField(default=2, enum=apps.review.models.Review.ENTRY_REVIEW_STATUS),
        ),
    ]
