# Generated by Django 3.0.5 on 2021-01-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_merge_20210104_0911'),
        ('review', '0004_auto_20201231_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='entry.OSMName', verbose_name='Geolocation/OSM'),
        ),
    ]
