# Generated by Django 3.0.5 on 2021-01-20 10:01

import apps.contrib.models
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_auto_20201106_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=utils.fields.CachedFileField(upload_to=apps.contrib.models.attachment_upload_to, verbose_name='Attachment'),
        ),
    ]
