# Generated by Django 3.0.5 on 2021-02-09 04:23

import apps.contrib.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0005_sourcepreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcepreview',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='sourcepreview',
            name='reason',
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.contrib.models.SourcePreview.PREVIEW_STATUS),
        ),
    ]
