# Generated by Django 3.0.5 on 2021-01-04 09:47

import apps.entry.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crisis', '0002_auto_20201019_0758'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0019_auto_20210104_0947'),
        ('country', '0002_auto_20201105_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('districts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('event_after', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('event_before', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('figure_roles', django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.ROLE), blank=True, size=None)),
                ('countries', models.ManyToManyField(blank=True, related_name='_extractionquery_countries_+', to='country.Country', verbose_name='Countries')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extractionquery', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('crises', models.ManyToManyField(blank=True, related_name='_extractionquery_crises_+', to='crisis.Crisis', verbose_name='Crises')),
                ('figure_categories', models.ManyToManyField(blank=True, related_name='_extractionquery_figure_categories_+', to='entry.FigureCategory', verbose_name='figure categories')),
                ('figure_tags', models.ManyToManyField(to='entry.FigureTag', verbose_name='Figure Tags')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('regions', models.ManyToManyField(blank=True, related_name='_extractionquery_regions_+', to='country.CountryRegion', verbose_name='Regions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
