# Generated by Django 3.0.5 on 2021-01-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0004_remove_extractionquery_districts'),
        ('extraction', '0004_extractionquery_article_title'),
    ]

    operations = [
    ]
