# Generated by Django 3.0.5 on 2021-02-17 03:09

import apps.crisis.models
import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0006_auto_20210205_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionquery',
            name='event_crisis_type',
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='event_crisis_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE), blank=True, null=True, size=None),
        ),
    ]
