# Generated by Django 3.0.5 on 2021-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0035_auto_20210222_1118'),
        ('country', '0009_auto_20210204_0458'),
        ('crisis', '0003_auto_20210127_0845'),
        ('extraction', '0007_auto_20210217_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionquery',
            old_name='entry_article_title',
            new_name='filter_entry_article_title',
        ),
        migrations.RenameField(
            model_name='extractionquery',
            old_name='event_crisis_types',
            new_name='filter_event_crisis_types',
        ),
        migrations.RenameField(
            model_name='extractionquery',
            old_name='figure_end_before',
            new_name='filter_figure_end_before',
        ),
        migrations.RenameField(
            model_name='extractionquery',
            old_name='figure_roles',
            new_name='filter_figure_roles',
        ),
        migrations.RenameField(
            model_name='extractionquery',
            old_name='figure_start_after',
            new_name='filter_figure_start_after',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='entry_tags',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='event_countries',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='event_crises',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='event_regions',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='figure_categories',
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_entry_tags',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_filter_entry_tags_+', to='entry.FigureTag', verbose_name='Figure Tags'),
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_event_crises',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_filter_event_crises_+', to='crisis.Crisis', verbose_name='Crises'),
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_categories',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_filter_figure_categories_+', to='entry.FigureCategory', verbose_name='figure categories'),
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_countries',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_filter_figure_countries_+', to='country.Country', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_regions',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_filter_figure_regions_+', to='country.CountryRegion', verbose_name='Regions'),
        ),
    ]
