# Generated by Django 3.0.5 on 2021-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_countrypopulation'),
        ('extraction', '0008_auto_20210305_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_geographical_groups',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_filter_figure_geographical_groups_+', to='country.GeographicalGroup', verbose_name='Geographical Group'),
        ),
    ]
