# Generated by Django 3.0.5 on 2021-05-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0010_extractionquery_filter_entry_review_status'),
        ('extraction', '0010_auto_20210429_0950'),
    ]

    operations = [
    ]
