# Generated by Django 3.0.5 on 2021-09-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0014_auto_20210830_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_category_types',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Type'),
        ),
    ]
