# Generated by Django 3.0.5 on 2021-09-28 07:47

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0017_auto_20210921_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_entry_article_title',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_event_glide_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True, verbose_name='Glide Number'), blank=True, null=True, size=None),
        ),
    ]
