# Generated by Django 3.0.5 on 2021-10-08 07:32

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0018_auto_20211002_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_entry_article_title',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_event_glide_number',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='Event Code'),
        ),
    ]
