# Generated by Django 3.0.5 on 2021-10-08 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0020_merge_20211008_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_event_glide_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True, verbose_name='Event Code'), blank=True, null=True, size=None),
        ),
    ]
