# Generated by Django 3.0.5 on 2021-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0023_auto_20211009_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionquery',
            name='filter_entry_has_disaggregated_data',
            field=models.NullBooleanField(default=None, verbose_name='Has disaggregated data'),
        ),
    ]
