# Generated by Django 3.0.5 on 2022-04-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20220415_0544'),
        ('extraction', '0026_auto_20220407_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionquery',
            name='filter_context_of_violence',
            field=models.ManyToManyField(blank=True, to='event.ContextOfViolence', verbose_name='Context of violence'),
        ),
    ]
