# Generated by Django 3.0.5 on 2021-11-12 04:36

import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0026_auto_20211103_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionquery',
            name='filter_figure_categories',
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES), blank=True, null=True, size=None),
        ),
    ]
