# Generated by Django 3.0.5 on 2022-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0030_auto_20220601_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionquery',
            old_name='filter_entry_sources',
            new_name='filter_figure_sources',
        ),
    ]
