# Generated by Django 3.0.5 on 2022-10-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0031_auto_20220613_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionquery',
            name='filter_entry_has_review_comments',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='filter_entry_review_status',
        ),
    ]
