# Generated by Django 3.2 on 2023-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0036_auto_20230221_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_figure_has_disaggregated_data',
            field=models.BooleanField(default=None, null=True, verbose_name='Has disaggregated data'),
        ),
        migrations.AlterField(
            model_name='extractionquery',
            name='filter_is_figure_to_be_reviewed',
            field=models.BooleanField(default=None, null=True, verbose_name='Filter to be reviewed'),
        ),
    ]
