# Generated by Django 3.2 on 2023-10-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0037_auto_20230404_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionquery',
            name='filter_figure_displacement_types',
        ),
    ]
