# Generated by Django 3.2 on 2023-12-08 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0032_delete_event_with_zero_figure'),
        ('extraction', '0039_auto_20231030_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionquery',
            old_name='filter_context_of_violence',
            new_name='filter_figure_context_of_violence',
        ),
        migrations.RenameField(
            model_name='extractionquery',
            old_name='filter_is_figure_to_be_reviewed',
            new_name='filter_figure_is_to_be_reviewed',
        ),
        migrations.RemoveField(
            model_name='extractionquery',
            name='filter_created_by',
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_approved_by',
            field=models.ManyToManyField(blank=True, related_name='_extraction_extractionquery_filter_figure_approved_by_+', to=settings.AUTH_USER_MODEL, verbose_name='Figure Approved by'),
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_created_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Figure Created by'),
        ),
        migrations.AddField(
            model_name='extractionquery',
            name='filter_figure_osv_sub_types',
            field=models.ManyToManyField(blank=True, to='event.OsvSubType', verbose_name='Osv Sub Type'),
        ),
    ]
