# Generated by Django 3.2 on 2024-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0040_auto_20231208_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
