# Generated by Django 3.2 on 2024-05-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0041_alter_extractionquery_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionquery',
            name='filter_figure_glide_number',
        ),
    ]
