# Generated by Django 3.0.5 on 2021-01-06 10:31

import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_merge_20210106_0651'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionquery',
            name='districts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='extractionquery',
            name='figure_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.ROLE), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='extractionquery',
            name='figure_tags',
            field=models.ManyToManyField(blank=True, related_name='_extractionquery_figure_tags_+', to='entry.FigureTag', verbose_name='Figure Tags'),
        ),
    ]
