# Generated by Django 3.0.5 on 2021-01-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_extractionquery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionquery',
            name='districts',
        ),
    ]
