# Generated by Django 3.0.5 on 2021-02-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0006_auto_20210205_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionquery',
            old_name='event_article_title',
            new_name='entry_article_title',
        ),
    ]
