# Generated by Django 3.0.5 on 2020-10-19 07:58

import apps.contact.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_time', models.DateTimeField(blank=True, help_text='Date on which communication occurred.', null=True, verbose_name='Date')),
                ('medium', django_enumfield.db.fields.EnumField(enum=apps.contact.models.Communication.COMMUNICATION_MEDIUM)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/attachments', verbose_name='attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('designation', django_enumfield.db.fields.EnumField(enum=apps.contact.models.Contact.DESIGNATION)),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('gender', django_enumfield.db.fields.EnumField(enum=apps.contact.models.Contact.GENDER)),
                ('job_title', models.CharField(max_length=256, verbose_name='Job Title')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('countries_of_operation', models.ManyToManyField(blank=True, help_text='In which countries does this contact person operate?', related_name='operating_contacts', to='country.Country', verbose_name='Countries of Operation')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='country.Country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
