# Generated by Django 3.0.5 on 2020-11-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201019_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='communication',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contact.CommunicationMedium'),
        ),
    ]
