# Generated by Django 3.0.5 on 2020-08-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('contact', '0002_auto_20200814_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='communication',
            name='date_time',
            field=models.DateTimeField(blank=True, help_text='Date on which communication occurred.', null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='communication',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='contact',
            name='countries_of_operation',
            field=models.ManyToManyField(help_text='In which countries does this contact person operate?', related_name='operating_contacts', to='country.Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=256, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=2, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=256, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='country.Country'),
        ),
    ]
