# Generated by Django 3.0.5 on 2020-08-19 06:28

import apps.contact.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200819_0628'),
        ('organization', '0007_auto_20200819_0628'),
        ('contact', '0004_auto_20200818_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contact.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='medium',
            field=django_enumfield.db.fields.EnumField(enum=apps.contact.models.Communication.COMMUNICATION_MEDIUM),
        ),
        migrations.AlterField(
            model_name='contact',
            name='countries_of_operation',
            field=models.ManyToManyField(blank=True, help_text='In which countries does this contact person operate?', related_name='operating_contacts', to='country.Country', verbose_name='Countries of Operation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='country.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='designation',
            field=django_enumfield.db.fields.EnumField(enum=apps.contact.models.Contact.DESIGNATION),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=django_enumfield.db.fields.EnumField(enum=apps.contact.models.Contact.GENDER),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.Organization', verbose_name='Organization'),
        ),
    ]
