# Generated by Django 3.0.5 on 2021-01-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20201231_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='attachment',
        ),
    ]
