# Generated by Django 3.0.5 on 2021-02-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210127_0432'),
        ('contact', '0008_auto_20210201_0620'),
    ]

    operations = [
    ]
