# Generated by Django 3.0.5 on 2021-02-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20210202_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='title',
        ),
    ]
