# Generated by Django 3.0.5 on 2020-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='medium',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MAIL'), (1, 'PHONE')], verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='designation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MR'), (1, 'MS')], verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
