# Generated by Django 3.0.5 on 2021-01-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_auto_20210120_1001'),
        ('contact', '0005_auto_20201231_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contrib.Attachment', verbose_name='Attachment'),
        ),
    ]
