# Generated by Django 3.0.5 on 2021-01-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20210105_0431'),
        ('contact', '0005_auto_20201231_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='country.Country', verbose_name='Country'),
        ),
    ]
