# Generated by Django 3.0.5 on 2021-01-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_auto_20210121_1047'),
        ('contact', '0006_remove_communication_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contrib.Attachment', verbose_name='Attachment'),
        ),
    ]
