# Generated by Django 3.0.5 on 2020-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200824_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='communication/attachments', verbose_name='attachment'),
        ),
    ]
