# Generated by Django 3.0.5 on 2020-08-26 06:44

import apps.entry.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    replaces = [('entry', '0001_initial'), ('entry', '0002_auto_20200824_0925'), ('entry', '0003_auto_20200824_0926'), ('entry', '0004_auto_20200824_1009'), ('entry', '0005_auto_20200826_0642')]

    initial = True

    dependencies = [
        ('event', '0001_squashed_0003_auto_20200820_1139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('article_title', models.TextField(verbose_name='Article Title')),
                ('source', models.CharField(max_length=256, verbose_name='Source')),
                ('publisher', models.CharField(max_length=256, verbose_name='Publisher')),
                ('publish_date', models.DateField(verbose_name='Published Date')),
                ('source_methodology', models.TextField(blank=True, null=True, verbose_name='Source Methodology')),
                ('source_excerpt', models.TextField(blank=True, null=True, verbose_name='Excerpt from Source')),
                ('source_breakdown', models.TextField(blank=True, null=True, verbose_name='Source Breakdown and Reliability')),
                ('idmc_analysis', models.TextField(null=True, verbose_name='IDMC Analysis')),
                ('methodology', models.TextField(null=True, verbose_name='Methodology')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, verbose_name='Tag'), blank=True, null=True, size=None)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='event.Event', verbose_name='Event')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='review_entries', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entry', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.TextField(verbose_name='District(s)')),
                ('town', models.CharField(max_length=256, verbose_name='Town/Village')),
                ('quantifier', django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.QUANTIFIER)),
                ('reported', models.PositiveIntegerField(verbose_name='Reported Figures')),
                ('unit', django_enumfield.db.fields.EnumField(default=0, enum=apps.entry.models.Figure.UNIT)),
                ('term', django_enumfield.db.fields.EnumField(default=0, enum=apps.entry.models.Figure.TERM)),
                ('type', django_enumfield.db.fields.EnumField(default=0, enum=apps.entry.models.Figure.TYPE)),
                ('role', django_enumfield.db.fields.EnumField(default=0, enum=apps.entry.models.Figure.ROLE)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('include_idu', models.BooleanField(verbose_name='Include in IDU')),
                ('excerpt_idu', models.TextField(blank=True, null=True, verbose_name='Excerpt for IDU')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='entry.Entry', verbose_name='Entry')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_figure', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
            ],
        ),
    ]
