# Generated by Django 3.0.5 on 2020-08-24 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20200824_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, verbose_name='Tag'), blank=True, null=True, size=None),
        ),
    ]
