# Generated by Django 3.0.5 on 2020-10-30 10:38

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20201029_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepreview',
            name='pdf',
            field=utils.fields.CachedFileField(blank=True, null=True, upload_to='source/previews', verbose_name='Rendered Pdf'),
        ),
    ]
