# Generated by Django 3.0.5 on 2020-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20200828_0833_squashed_0004_auto_20200828_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='household_size',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Household Size'),
        ),
        migrations.AddField(
            model_name='figure',
            name='total_figures',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Figures'),
        ),
    ]
