# Generated by Django 3.0.5 on 2020-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('entry', '0005_merge_20200902_0850'), ('entry', '0006_auto_20200902_0851')]

    dependencies = [
        ('entry', '0004_auto_20200902_0704'),
        ('entry', '0004_merge_20200831_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='total_figures',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total Figures'),
        ),
    ]
