# Generated by Django 3.0.5 on 2020-09-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_merge_20200907_0438'),
        ('entry', '0006_sourcepreview_squashed_0007_entry_preview'),
    ]

    operations = [
    ]
