# Generated by Django 3.0.5 on 2020-11-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_entry_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='source',
        ),
    ]
