# Generated by Django 3.0.5 on 2020-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_merge_20200909_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepreview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Pdf URL'),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='reason',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Error Reason'),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='sourcepreview',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='source/previews', verbose_name='Rendered Pdf'),
        ),
    ]
