# Generated by Django 3.0.5 on 2020-11-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20201111_1050'),
        ('entry', '0010_auto_20201111_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='confidential',
            new_name='is_confidential',
        ),
        migrations.AlterField(
            model_name='entry',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_entires', to='organization.Organization', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_entries', to='organization.Organization', verbose_name='Source'),
        ),
    ]
