# Generated by Django 3.0.5 on 2020-11-19 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0014_remove_entry_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_entries', through='entry.EntryReviewer', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
    ]
