# Generated by Django 3.0.5 on 2020-12-09 06:49

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_auto_20201208_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryreviewer',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=3, enum=apps.entry.models.EntryReviewer.REVIEW_STATUS),
        ),
    ]
