# Generated by Django 3.0.5 on 2020-12-30 04:26

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_auto_20201229_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmname',
            name='identifier',
            field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.OSMName.IDENTIFIER),
        ),
    ]
