# Generated by Django 3.0.5 on 2021-01-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0027_auto_20210112_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='district',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='town',
        ),
    ]
