# Generated by Django 3.0.5 on 2021-01-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_auto_20210113_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='district',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='town',
        ),
    ]
