# Generated by Django 3.0.5 on 2021-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20210122_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='sourcepreview',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='Source URL'),
        ),
    ]
