# Generated by Django 3.0.5 on 2021-02-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0005_sourcepreview'),
        ('entry', '0032_merge_20210203_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='preview',
            field=models.OneToOneField(blank=True, help_text='After the preview has been generated pass its id along during entry creation, so that during entry update the preview can be obtained.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry', to='contrib.SourcePreview'),
        ),
        migrations.DeleteModel(
            name='SourcePreview',
        ),
    ]
