# Generated by Django 3.0.5 on 2021-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name is auto generated.', max_length=512, null=True, verbose_name='Full Name'),
        ),
    ]
