# Generated by Django 3.0.5 on 2021-06-14 06:41

import apps.users.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_auto_20210614_0641'),
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_enumfield.db.fields.EnumField(enum=apps.users.enums.USER_ROLE)),
                ('monitoring_sub_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='country.MonitoringSubRegion', verbose_name='Monitoring Sub-region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'monitoring_sub_region'), name='unique_with_region'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(monitoring_sub_region=None), fields=('user', 'role'), name='unique_without_region'),
        ),
    ]
