# Generated by Django 3.0.5 on 2021-09-29 05:41

import apps.users.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210619_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='role',
            field=django_enumfield.db.fields.EnumField(default=3, enum=apps.users.enums.USER_ROLE),
        ),
    ]
