# Generated by Django 3.0.5 on 2021-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_country_sub_region'),
        ('users', '0003_auto_20210614_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='countries',
            field=models.ManyToManyField(related_name='portfolios', to='country.Country', verbose_name='Countries'),
        ),
    ]
