# Generated by Django 3.0.5 on 2022-06-01 17:58

import apps.users.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210929_0541'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='unique_with_country',
        ),
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='unique_without_region',
        ),
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='unique_without_country',
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(role=apps.users.enums.USER_ROLE(1)), fields=('role', 'monitoring_sub_region'), name='unique_for_monitoring_sub_region'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(role=apps.users.enums.USER_ROLE(2)), fields=('role', 'country'), name='unique_for_country'),
        ),
    ]
