# Generated by Django 3.0.5 on 2021-01-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20201228_0836'),
        ('country', '0003_auto_20201231_0707'),
    ]

    operations = [
    ]
