# Generated by Django 3.0.5 on 2020-08-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('methodology', models.TextField(verbose_name='Methodology')),
                ('source_detail_methodology', models.TextField(verbose_name='Source detail and methodology')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organizations', to='organization.Organization')),
            ],
        ),
    ]
