# Generated by Django 3.0.5 on 2020-08-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200814_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationType',
            new_name='OrganizationKind',
        ),
    ]
