# Generated by Django 3.0.5 on 2020-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_deleted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='old_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key'),
        ),
        migrations.AddField(
            model_name='organizationkind',
            name='old_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Old primary key'),
        ),
    ]
