# Generated by Django 3.0.5 on 2020-08-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200814_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organization.OrganizationKind'),
        ),
    ]
