# Generated by Django 3.0.5 on 2020-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20200819_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='methodology',
            field=models.TextField(help_text='', verbose_name='Methodology'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='source_detail_methodology',
            field=models.TextField(help_text='', verbose_name='Source detail and methodology'),
        ),
    ]
