# Generated by Django 3.0.5 on 2022-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'Figure approved'), (1, 'Figure re-requested review'), (2, 'Figure un-approved'), (3, 'Figure created'), (4, 'Figure updated'), (5, 'Figure deleted'), (6, 'Figure unapproved in signed event'), (101, 'Event assigned'), (102, 'Event assignee cleared'), (103, 'Event signed off'), (104, 'Event self assigned'), (105, 'Event approved'), (106, 'Event include triangulation changed'), (201, 'Comment created')], verbose_name='Notification Type'),
        ),
    ]
