# Generated by Django 3.0.5 on 2022-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20221124_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Raw text'),
        ),
    ]
