# Generated by Django 3.0.5 on 2022-12-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0077_auto_20221114_0425'),
        ('notification', '0003_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entry.Entry', verbose_name='Entry'),
        ),
    ]
