"""Figure revision rounds published in the GIDD export READMEs."""

import typing

RevisionRow = typing.Tuple[str, str, str, str, str, str]
Rows = typing.List[typing.List[str]]

REVISION_TABLE_HEADER = ["ISO3", "Country", "Geographical region", "Year", "Figure cause", "Figure category"]

REVISIONS_HEADING = "HISTORICAL DATA REVISIONS AND CORRECTIONS"

METHODOLOGY_ROW = "Methodology: https://www.internal-displacement.org/monitoring-tools"

REVISIONS_INTRO = (
    "As part of our ongoing commitment to providing accurate and reliable internal displacement data, "
    "IDMC periodically releases updated figures for several countries and years where data was previously "
    "unavailable or required corrections. These revisions result from comprehensive methodological reviews "
    "and address discrepancies in earlier figures published in GIDD. All figures undergo expert validation. "
)

CONTEXT_TAB_SENTENCE = "A detailed account of changes is provided in tab {tab}. "

REVISIONS_CONTACT = "For inquiries: ch.datainfo@idmc.ch."


SEPTEMBER_2026_NOTE = (
    "All IDP stock figures for 2008–2016 were updated in this release as part of the Historical data "
    "revision project. Because every IDPs figure was updated, only Internal Displacements changes are "
    "listed below."
)


def revision_block(
    heading: str,
    rows: typing.List[RevisionRow],
    cause: typing.Optional[str] = None,
    category: typing.Optional[str] = None,
    note: typing.Optional[str] = None,
) -> Rows:
    """Render one revision round as README rows, narrowed to what an export reports.

    An export that reports a single cause or metric must not advertise revisions it does
    not carry: the disaster workbook holds only disaster flows, so passing cause and
    category keeps its table to the rows a reader can actually find in the data.
    """
    selected = [row for row in rows if (cause is None or row[4] == cause) and (category is None or row[5] == category)]
    block = [[], [heading]]
    if note:
        block.append([note])
    block.append(list(REVISION_TABLE_HEADER))
    return [*block, *[list(row) for row in selected]]


def historical_revisions_block(
    cause: typing.Optional[str] = None,
    category: typing.Optional[str] = None,
    context_tab: typing.Optional[str] = None,
) -> Rows:
    """Render every published revision round, narrowed to what an export reports.

    `context_tab` names the sheet carrying the per-figure account of the changes; an export
    without such a sheet must not point a reader at one. The September 2026 note explains why
    no IDPs rows are listed, so it is rendered only for an export that reports IDPs at all --
    a workbook narrowed to one category carries no IDPs metric for the note to be about.
    """
    intro = REVISIONS_INTRO
    if context_tab:
        intro += CONTEXT_TAB_SENTENCE.format(tab=context_tab)
    intro += REVISIONS_CONTACT

    return [
        [REVISIONS_HEADING],
        [],
        [METHODOLOGY_ROW],
        [intro],
        *revision_block("FIGURES REVIEWED IN JANUARY 2025", REVISIONS_JANUARY_2025, cause, category),
        *revision_block("FIGURES REVIEWED IN MAY 2025", REVISIONS_MAY_2025, cause, category),
        *revision_block("FIGURES REVIEWED IN MAY 2026", REVISIONS_MAY_2026, cause, category),
        *revision_block(
            "FIGURES REVIEWED IN SEPTEMBER 2026",
            REVISIONS_SEPTEMBER_2026,
            cause,
            category,
            note=SEPTEMBER_2026_NOTE if category is None else None,
        ),
    ]


REVISIONS_JANUARY_2025: typing.List[RevisionRow] = [
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2023", "Conflict", "Internal Displacements"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2021", "Disaster", "Internal Displacements"),
    ("COD", "Dem. Rep. Congo", "Sub-Saharan Africa", "2023", "Conflict", "IDPs"),
    ("GRC", "Greece", "Europe and Central Asia", "2023", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2021", "Disaster", "IDPs"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2023", "Disaster", "IDPs"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2023", "Disaster", "Internal Displacements"),
    ("LSO", "Lesotho", "Sub-Saharan Africa", "2023", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2023", "Conflict", "Internal Displacements"),
    ("MEX", "Mexico", "The Americas", "2023", "Conflict", "IDPs"),
    ("MAR", "Morocco", "Middle East and North Africa", "2023", "Disaster", "IDPs"),
    ("MAR", "Morocco", "Middle East and North Africa", "2023", "Disaster", "Internal Displacements"),
    ("MOZ", "Mozambique", "Sub-Saharan Africa", "2022", "Conflict", "Internal Displacements"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2023", "Disaster", "IDPs"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2023", "Disaster", "Internal Displacements"),
    ("PHL", "Philippines", "East Asia and Pacific", "2023", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2017", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2018", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2023", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2021", "Disaster", "IDPs"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2022", "Disaster", "IDPs"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2022", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2023", "Disaster", "IDPs"),
    ("USA", "United States", "The Americas", "2023", "Disaster", "Internal Displacements"),
]


REVISIONS_MAY_2025: typing.List[RevisionRow] = [
    ("IDN", "Indonesia", "East Asia and Pacific", "2016", "Conflict", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2016", "Conflict", "IDPs"),
    ("PRI", "Puerto Rico", "The Americas", "2017", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2017", "Disaster", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2017", "Conflict", "IDPs"),
    ("IND", "India", "South Asia", "2017", "Conflict", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2018", "Conflict", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2018", "Conflict", "IDPs"),
    ("ESP", "Spain", "Europe and Central Asia", "2018", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2018", "Conflict", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2018", "Conflict", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2018", "Conflict", "Internal Displacements"),
    ("IND", "India", "South Asia", "2018", "Conflict", "Internal Displacements"),
    ("PRI", "Puerto Rico", "The Americas", "2019", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2019", "Disaster", "IDPs"),
    ("BGD", "Bangladesh", "South Asia", "2019", "Conflict", "IDPs"),
    ("PAK", "Pakistan", "South Asia", "2019", "Conflict", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2019", "Disaster", "IDPs"),
    ("PAK", "Pakistan", "South Asia", "2019", "Conflict", "IDPs"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2019", "Disaster", "IDPs"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2019", "Conflict", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2019", "Conflict", "IDPs"),
    ("IND", "India", "South Asia", "2019", "Conflict", "Internal Displacements"),
    ("IND", "India", "South Asia", "2019", "Disaster", "IDPs"),
    ("BGD", "Bangladesh", "South Asia", "2020", "Disaster", "IDPs"),
    ("BGD", "Bangladesh", "South Asia", "2020", "Conflict", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2020", "Conflict", "IDPs"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2021", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2021", "Disaster", "IDPs"),
    ("IND", "India", "South Asia", "2021", "Disaster", "IDPs"),
    ("PAK", "Pakistan", "South Asia", "2022", "Conflict", "IDPs"),
    ("COL", "Colombia", "The Americas", "2022", "Conflict", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2022", "Conflict", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2022", "Conflict", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2022", "Conflict", "Internal Displacements"),
    ("TUR", "Türkiye", "Europe and Central Asia", "2022", "Conflict", "IDPs"),
    ("MDG", "Madagascar", "Sub-Saharan Africa", "2022", "Conflict", "IDPs"),
    ("IND", "India", "South Asia", "2022", "Conflict", "IDPs"),
    ("LKA", "Sri Lanka", "South Asia", "2022", "Conflict", "IDPs"),
    ("PHL", "Philippines", "East Asia and Pacific", "2022", "Conflict", "IDPs"),
    ("GEO", "Georgia", "Europe and Central Asia", "2022", "Conflict", "IDPs"),
    ("PAK", "Pakistan", "South Asia", "2023", "Conflict", "IDPs"),
    ("COL", "Colombia", "The Americas", "2023", "Conflict", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2023", "Conflict", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2023", "Conflict", "IDPs"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2023", "Conflict", "Internal Displacements"),
    ("TUR", "Türkiye", "Europe and Central Asia", "2023", "Conflict", "IDPs"),
    ("PSE", "Palestine", "Middle East and North Africa", "2023", "Conflict", "IDPs"),
    ("PSE", "Palestine", "Middle East and North Africa", "2023", "Conflict", "Internal Displacements"),
    ("MDG", "Madagascar", "Sub-Saharan Africa", "2023", "Conflict", "IDPs"),
    ("IND", "India", "South Asia", "2023", "Conflict", "IDPs"),
    ("KAZ", "Kazakhstan", "Europe and Central Asia", "2023", "Conflict", "IDPs"),
    ("LKA", "Sri Lanka", "South Asia", "2023", "Conflict", "IDPs"),
    ("BIH", "Bosnia and Herzegovina", "Europe and Central Asia", "2023", "Conflict", "IDPs"),
    ("PER", "Peru", "The Americas", "2023", "Disaster", "IDPs"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2023", "Conflict", "IDPs"),
    ("PHL", "Philippines", "East Asia and Pacific", "2023", "Conflict", "IDPs"),
    ("PHL", "Philippines", "East Asia and Pacific", "2023", "Conflict", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2023", "Conflict", "IDPs"),
    ("GEO", "Georgia", "Europe and Central Asia", "2023", "Conflict", "IDPs"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa", "2023", "Conflict", "IDPs"),
]


REVISIONS_MAY_2026: typing.List[RevisionRow] = [
    ("GTM", "Guatemala", "The Americas", "2022", "Conflict", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2023", "Conflict", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2023", "Conflict", "IDPs"),
    ("SYR", "Syria", "Middle East and North Africa", "2024", "Conflict", "IDPs"),
    ("PHL", "Philippines", "East Asia and Pacific", "2024", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2023", "Conflict", "Internal Displacements"),
    ("ZAF", "South Africa", "Sub-Saharan Africa", "2024", "Disaster", "Internal Displacements"),
    ("COD", "Dem. Rep. Congo", "Sub-Saharan Africa", "2024", "Conflict", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2024", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2024", "Conflict", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2024", "Disaster", "IDPs"),
    ("LBR", "Liberia", "Sub-Saharan Africa", "2017", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2017", "Disaster", "Internal Displacements"),
]


REVISIONS_SEPTEMBER_2026: typing.List[RevisionRow] = [
    ("AFG", "Afghanistan", "South Asia", "2008", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2009", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2010", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2011", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2012", "Conflict", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2012", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2013", "Conflict", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2013", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2014", "Conflict", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2014", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2015", "Conflict", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2015", "Disaster", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2016", "Conflict", "Internal Displacements"),
    ("AFG", "Afghanistan", "South Asia", "2016", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("AGO", "Angola", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("AIA", "Anguilla", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2008", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("ALB", "Albania", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("ARG", "Argentina", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("ASM", "American Samoa", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("ASM", "American Samoa", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("ATG", "Antigua and Barbuda", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("ATG", "Antigua and Barbuda", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("AUS", "Australia", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("AZE", "Azerbaijan", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("AZE", "Azerbaijan", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("AZE", "Azerbaijan", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("BDI", "Burundi", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("BEN", "Benin", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("BEN", "Benin", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("BEN", "Benin", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("BEN", "Benin", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("BEN", "Benin", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("BFA", "Burkina Faso", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2008", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2009", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2010", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2011", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2012", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2013", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2014", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2015", "Disaster", "Internal Displacements"),
    ("BGD", "Bangladesh", "South Asia", "2016", "Disaster", "Internal Displacements"),
    ("BGR", "Bulgaria", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("BGR", "Bulgaria", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("BHS", "Bahamas", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("BHS", "Bahamas", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("BHS", "Bahamas", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("BIH", "Bosnia and Herzegovina", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("BIH", "Bosnia and Herzegovina", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("BIH", "Bosnia and Herzegovina", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("BLZ", "Belize", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("BLZ", "Belize", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("BLZ", "Belize", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("BLZ", "Belize", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("BOL", "Bolivia", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("BRA", "Brazil", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("BTN", "Bhutan", "South Asia", "2009", "Disaster", "Internal Displacements"),
    ("BTN", "Bhutan", "South Asia", "2011", "Disaster", "Internal Displacements"),
    ("BWA", "Botswana", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("BWA", "Botswana", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("BWA", "Botswana", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("BWA", "Botswana", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("BWA", "Botswana", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("BWA", "Botswana", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("CAF", "Central African Republic", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("CHL", "Chile", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("CHN", "China", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("CIV", "Côte d'Ivoire", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("CIV", "Côte d'Ivoire", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("CIV", "Côte d'Ivoire", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("CMR", "Cameroon", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("CMR", "Cameroon", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("CMR", "Cameroon", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("CMR", "Cameroon", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("CMR", "Cameroon", "Sub-Saharan Africa", "2016", "Conflict", "Internal Displacements"),
    ("COG", "Congo", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("COG", "Congo", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("COG", "Congo", "Sub-Saharan Africa", "2016", "Conflict", "Internal Displacements"),
    ("COK", "Cook Islands", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("COL", "Colombia", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("COL", "Colombia", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("COL", "Colombia", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("COM", "Comoros", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("COM", "Comoros", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("CPV", "Cabo Verde", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("CRI", "Costa Rica", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("CUB", "Cuba", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("CUB", "Cuba", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("CUB", "Cuba", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("CUB", "Cuba", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("CUB", "Cuba", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("CZE", "Czech Republic", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("CZE", "Czech Republic", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("DEU", "Germany", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("DJI", "Djibouti", "Middle East and North Africa", "2012", "Disaster", "Internal Displacements"),
    ("DJI", "Djibouti", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("DMA", "Dominica", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("DMA", "Dominica", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("DMA", "Dominica", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("DMA", "Dominica", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("DMA", "Dominica", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("DOM", "Dominican Republic", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("DZA", "Algeria", "Middle East and North Africa", "2011", "Disaster", "Internal Displacements"),
    ("DZA", "Algeria", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("DZA", "Algeria", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("ECU", "Ecuador", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("EGY", "Egypt", "Middle East and North Africa", "2008", "Disaster", "Internal Displacements"),
    ("EGY", "Egypt", "Middle East and North Africa", "2010", "Disaster", "Internal Displacements"),
    ("EGY", "Egypt", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("ERI", "Eritrea", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("ERI", "Eritrea", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("ERI", "Eritrea", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("ERI", "Eritrea", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2008", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("ESP", "Spain", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("ETH", "Ethiopia", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("FJI", "Fiji", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("FRA", "France", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("FRA", "France", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("FRA", "France", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("FRA", "France", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("FSM", "Micronesia", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("GAB", "Gabon", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("GAB", "Gabon", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("GAB", "Gabon", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("GAB", "Gabon", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("GBR", "United Kingdom", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("GBR", "United Kingdom", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("GBR", "United Kingdom", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("GBR", "United Kingdom", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("GBR", "United Kingdom", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("GEO", "Georgia", "Europe and Central Asia", "2008", "Conflict", "Internal Displacements"),
    ("GEO", "Georgia", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("GEO", "Georgia", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("GEO", "Georgia", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("GEO", "Georgia", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("GEO", "Georgia", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("GHA", "Ghana", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("GHA", "Ghana", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("GHA", "Ghana", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("GHA", "Ghana", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("GHA", "Ghana", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("GIN", "Guinea", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("GIN", "Guinea", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("GIN", "Guinea", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("GIN", "Guinea", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("GLP", "Guadeloupe", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("GMB", "Gambia", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("GMB", "Gambia", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("GMB", "Gambia", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("GMB", "Gambia", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("GMB", "Gambia", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("GNB", "Guinea-Bissau", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("GRC", "Greece", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("GRC", "Greece", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("GRC", "Greece", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("GTM", "Guatemala", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("GUM", "Guam", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("GUY", "Guyana", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("GUY", "Guyana", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("GUY", "Guyana", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("GUY", "Guyana", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("HKG", "Hong Kong, China", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("HKG", "Hong Kong, China", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("HKG", "Hong Kong, China", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("HKG", "Hong Kong, China", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("HKG", "Hong Kong, China", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("HND", "Honduras", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("HTI", "Haiti", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("HTI", "Haiti", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("HTI", "Haiti", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("HUN", "Hungary", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("HUN", "Hungary", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("HUN", "Hungary", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2008", "Conflict", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2010", "Conflict", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2013", "Conflict", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("IDN", "Indonesia", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2008", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2009", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2010", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2011", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2012", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2013", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2014", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2015", "Disaster", "Internal Displacements"),
    ("IND", "India", "South Asia", "2016", "Disaster", "Internal Displacements"),
    ("IRL", "Ireland", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("IRL", "Ireland", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2010", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2011", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2012", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2014", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("IRN", "Iran", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2008", "Disaster", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2011", "Disaster", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2014", "Conflict", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2014", "Disaster", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2015", "Conflict", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2016", "Conflict", "Internal Displacements"),
    ("IRQ", "Iraq", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("ISR", "Israel", "Middle East and North Africa", "2010", "Disaster", "Internal Displacements"),
    ("ISR", "Israel", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("ITA", "Italy", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("ITA", "Italy", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("ITA", "Italy", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("ITA", "Italy", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("ITA", "Italy", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("ITA", "Italy", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("JAM", "Jamaica", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("JAM", "Jamaica", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("JAM", "Jamaica", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("JOR", "Jordan", "Middle East and North Africa", "2008", "Disaster", "Internal Displacements"),
    ("JOR", "Jordan", "Middle East and North Africa", "2009", "Disaster", "Internal Displacements"),
    ("JOR", "Jordan", "Middle East and North Africa", "2010", "Disaster", "Internal Displacements"),
    ("JOR", "Jordan", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("JOR", "Jordan", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("JOR", "Jordan", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("JPN", "Japan", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("JPN", "Japan", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("JPN", "Japan", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("JPN", "Japan", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("JPN", "Japan", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("JPN", "Japan", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("KAZ", "Kazakhstan", "Europe and Central Asia", "2008", "Disaster", "Internal Displacements"),
    ("KAZ", "Kazakhstan", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("KAZ", "Kazakhstan", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("KAZ", "Kazakhstan", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("KAZ", "Kazakhstan", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("KGZ", "Kyrgyzstan", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("KHM", "Cambodia", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("KHM", "Cambodia", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("KHM", "Cambodia", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("KHM", "Cambodia", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("KHM", "Cambodia", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("KIR", "Kiribati", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("KIR", "Kiribati", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("KNA", "St. Kitts and Nevis", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("KOR", "Korea", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("KOR", "Korea", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("LAO", "Lao PDR", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("LAO", "Lao PDR", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("LAO", "Lao PDR", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("LBN", "Lebanon", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("LBN", "Lebanon", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("LBR", "Liberia", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("LBR", "Liberia", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("LBY", "Libya", "Middle East and North Africa", "2016", "Conflict", "Internal Displacements"),
    ("LCA", "St. Lucia", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("LCA", "St. Lucia", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("LSO", "Lesotho", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("LSO", "Lesotho", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("LSO", "Lesotho", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("MAR", "Morocco", "Middle East and North Africa", "2008", "Disaster", "Internal Displacements"),
    ("MAR", "Morocco", "Middle East and North Africa", "2009", "Disaster", "Internal Displacements"),
    ("MAR", "Morocco", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("MDA", "Moldova", "Europe and Central Asia", "2008", "Disaster", "Internal Displacements"),
    ("MDA", "Moldova", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("MDV", "Maldives", "South Asia", "2009", "Disaster", "Internal Displacements"),
    ("MDV", "Maldives", "South Asia", "2012", "Disaster", "Internal Displacements"),
    ("MEX", "Mexico", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("MHL", "Marshall Islands", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("MHL", "Marshall Islands", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("MHL", "Marshall Islands", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("MKD", "North Macedonia", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("MKD", "North Macedonia", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("MKD", "North Macedonia", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2014", "Conflict", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2015", "Conflict", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2016", "Conflict", "Internal Displacements"),
    ("MLI", "Mali", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("MMR", "Myanmar", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("MNE", "Montenegro", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("MNE", "Montenegro", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("MNG", "Mongolia", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("MNG", "Mongolia", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("MNG", "Mongolia", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("MNG", "Mongolia", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("MNP", "Northern Mariana Islands", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("MOZ", "Mozambique", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("MOZ", "Mozambique", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("MOZ", "Mozambique", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("MOZ", "Mozambique", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("MRT", "Mauritania", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("MRT", "Mauritania", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("MRT", "Mauritania", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("MRT", "Mauritania", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("MRT", "Mauritania", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("MUS", "Mauritius", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("MUS", "Mauritius", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("MUS", "Mauritius", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("MWI", "Malawi", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("MWI", "Malawi", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("MYS", "Malaysia", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("NAM", "Namibia", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("NER", "Niger", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("NGA", "Nigeria", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("NGA", "Nigeria", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("NGA", "Nigeria", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("NGA", "Nigeria", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("NGA", "Nigeria", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("NGA", "Nigeria", "Sub-Saharan Africa", "2016", "Conflict", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("NIC", "Nicaragua", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("NOR", "Norway", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("NPL", "Nepal", "South Asia", "2011", "Disaster", "Internal Displacements"),
    ("NPL", "Nepal", "South Asia", "2012", "Disaster", "Internal Displacements"),
    ("NPL", "Nepal", "South Asia", "2015", "Disaster", "Internal Displacements"),
    ("NZL", "New Zealand", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("NZL", "New Zealand", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2008", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2009", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2010", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2011", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2012", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2013", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2014", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2015", "Disaster", "Internal Displacements"),
    ("PAK", "Pakistan", "South Asia", "2016", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("PAN", "Panama", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("PER", "Peru", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("PHL", "Philippines", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("PHL", "Philippines", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("PHL", "Philippines", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("PLW", "Palau", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2010", "Conflict", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2013", "Conflict", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2015", "Conflict", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("PNG", "Papua New Guinea", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("POL", "Poland", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("PRI", "Puerto Rico", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("PRI", "Puerto Rico", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("PRI", "Puerto Rico", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("PRI", "Puerto Rico", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("PRK", "Dem. People's Rep. Korea", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("PRK", "Dem. People's Rep. Korea", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("PRK", "Dem. People's Rep. Korea", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("PRK", "Dem. People's Rep. Korea", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("PRK", "Dem. People's Rep. Korea", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("PRK", "Dem. People's Rep. Korea", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("PRY", "Paraguay", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2009", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2010", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2010", "Disaster", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2011", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2012", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2012", "Disaster", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2013", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2014", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2014", "Disaster", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2015", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2016", "Conflict", "Internal Displacements"),
    ("PSE", "Palestine", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("PYF", "French Polynesia", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2008", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("ROU", "Romania", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("RUS", "Russia", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("RUS", "Russia", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("RUS", "Russia", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("RUS", "Russia", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("RUS", "Russia", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("RUS", "Russia", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("RWA", "Rwanda", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("SAU", "Saudi Arabia", "Middle East and North Africa", "2009", "Disaster", "Internal Displacements"),
    ("SAU", "Saudi Arabia", "Middle East and North Africa", "2011", "Disaster", "Internal Displacements"),
    ("SAU", "Saudi Arabia", "Middle East and North Africa", "2012", "Disaster", "Internal Displacements"),
    ("SEN", "Senegal", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("SEN", "Senegal", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("SEN", "Senegal", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("SEN", "Senegal", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("SEN", "Senegal", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("SEN", "Senegal", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("SLB", "Solomon Islands", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("SLE", "Sierra Leone", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("SLV", "El Salvador", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("SOM", "Somalia", "Sub-Saharan Africa", "2016", "Conflict", "Internal Displacements"),
    ("SOM", "Somalia", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("SRB", "Serbia", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("SUR", "Suriname", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("SVK", "Slovakia", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("SVN", "Slovenia", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("SYC", "Seychelles", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("SYC", "Seychelles", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("SYR", "Syria", "Middle East and North Africa", "2009", "Disaster", "Internal Displacements"),
    ("SYR", "Syria", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("SYR", "Syria", "Middle East and North Africa", "2014", "Disaster", "Internal Displacements"),
    ("SYR", "Syria", "Middle East and North Africa", "2016", "Disaster", "Internal Displacements"),
    ("TCA", "Turks and Caicos Islands", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("TCA", "Turks and Caicos Islands", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2008", "Conflict", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("TCD", "Chad", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("TGO", "Togo", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("TGO", "Togo", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("TGO", "Togo", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("TGO", "Togo", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("TGO", "Togo", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("THA", "Thailand", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2011", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2014", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("TJK", "Tajikistan", "Europe and Central Asia", "2016", "Disaster", "Internal Displacements"),
    ("TLS", "Timor-Leste", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("TLS", "Timor-Leste", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("TLS", "Timor-Leste", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("TLS", "Timor-Leste", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("TLS", "Timor-Leste", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("TON", "Tonga", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("TON", "Tonga", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("TON", "Tonga", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("TON", "Tonga", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("TON", "Tonga", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("TTO", "Trinidad and Tobago", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("TTO", "Trinidad and Tobago", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("TUN", "Tunisia", "Middle East and North Africa", "2009", "Disaster", "Internal Displacements"),
    ("TUN", "Tunisia", "Middle East and North Africa", "2012", "Disaster", "Internal Displacements"),
    ("TUN", "Tunisia", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("TUR", "Türkiye", "Europe and Central Asia", "2009", "Disaster", "Internal Displacements"),
    ("TUR", "Türkiye", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("TUR", "Türkiye", "Europe and Central Asia", "2012", "Disaster", "Internal Displacements"),
    ("TUR", "Türkiye", "Europe and Central Asia", "2015", "Disaster", "Internal Displacements"),
    ("TUV", "Tuvalu", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("TWN", "Taiwan, China", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("TWN", "Taiwan, China", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("TWN", "Taiwan, China", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("TWN", "Taiwan, China", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("TZA", "Tanzania", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("UGA", "Uganda", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("UKR", "Ukraine", "Europe and Central Asia", "2008", "Disaster", "Internal Displacements"),
    ("UKR", "Ukraine", "Europe and Central Asia", "2010", "Disaster", "Internal Displacements"),
    ("UKR", "Ukraine", "Europe and Central Asia", "2013", "Disaster", "Internal Displacements"),
    ("UKR", "Ukraine", "Europe and Central Asia", "2016", "Conflict", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("URY", "Uruguay", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2009", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("USA", "United States", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("VCT", "St. Vincent and the Grenadines", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("VCT", "St. Vincent and the Grenadines", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2008", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2010", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2011", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2012", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2013", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2014", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2015", "Disaster", "Internal Displacements"),
    ("VEN", "Venezuela", "The Americas", "2016", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2008", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2010", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2013", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("VNM", "Viet Nam", "East Asia and Pacific", "2016", "Disaster", "Internal Displacements"),
    ("VUT", "Vanuatu", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("VUT", "Vanuatu", "East Asia and Pacific", "2011", "Disaster", "Internal Displacements"),
    ("VUT", "Vanuatu", "East Asia and Pacific", "2012", "Disaster", "Internal Displacements"),
    ("VUT", "Vanuatu", "East Asia and Pacific", "2014", "Disaster", "Internal Displacements"),
    ("VUT", "Vanuatu", "East Asia and Pacific", "2015", "Disaster", "Internal Displacements"),
    ("WSM", "Samoa", "East Asia and Pacific", "2009", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2008", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2009", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2010", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2011", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2013", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2015", "Disaster", "Internal Displacements"),
    ("YEM", "Yemen", "Middle East and North Africa", "2016", "Conflict", "Internal Displacements"),
    ("ZAF", "South Africa", "Sub-Saharan Africa", "2008", "Conflict", "Internal Displacements"),
    ("ZAF", "South Africa", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("ZAF", "South Africa", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("ZAF", "South Africa", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2008", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2009", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
    ("ZMB", "Zambia", "Sub-Saharan Africa", "2016", "Disaster", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2008", "Conflict", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2010", "Disaster", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2011", "Disaster", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2012", "Disaster", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2013", "Disaster", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2014", "Disaster", "Internal Displacements"),
    ("ZWE", "Zimbabwe", "Sub-Saharan Africa", "2015", "Disaster", "Internal Displacements"),
]
