# Generated by Django 3.0.5 on 2020-11-06 08:34

import apps.contrib.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_for',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.contrib.models.Attachment.FOR_CHOICES, help_text='The type of instance for which attachment was uploaded for', null=True),
        ),
    ]
