# Generated by Django 3.0.5 on 2021-02-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0004_auto_20210121_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('url', models.URLField(max_length=2000, verbose_name='Source URL')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Token')),
                ('pdf', utils.fields.CachedFileField(blank=True, null=True, upload_to='source/previews', verbose_name='Rendered Pdf')),
                ('completed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Error Reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sourcepreview', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
