# Generated by Django 3.0.5 on 2021-03-26 04:40

import apps.contrib.models
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0006_auto_20210209_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=utils.fields.CachedFileField(upload_to=apps.contrib.models.global_upload_to, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='sourcepreview',
            name='pdf',
            field=utils.fields.CachedFileField(blank=True, null=True, upload_to=apps.contrib.models.global_upload_to, verbose_name='Rendered Pdf'),
        ),
    ]
