# Generated by Django 3.0.5 on 2021-03-28 10:14

import apps.contrib.models
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0007_auto_20210326_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepreview',
            name='pdf',
            field=utils.fields.CachedFileField(blank=True, max_length=256, null=True, upload_to=apps.contrib.models.global_upload_to, verbose_name='Rendered Pdf'),
        ),
    ]
