# Generated by Django 3.0.5 on 2021-04-09 10:12

import apps.contrib.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0008_auto_20210328_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('download_type', django_enumfield.db.fields.EnumField(enum=apps.contrib.models.ExcelDownload.DOWNLOAD_TYPES)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.contrib.models.ExcelDownload.EXCEL_GENERATION_STATUS)),
                ('file', utils.fields.CachedFileField(blank=True, null=True, upload_to=apps.contrib.models.excel_upload_to, verbose_name='Excel File')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Filters')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exceldownload', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
