# Generated by Django 3.0.5 on 2021-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0009_exceldownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldownload',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
    ]
