# Generated by Django 3.0.5 on 2021-09-21 07:29

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0010_exceldownload_file_size'),
    ]

    operations = [
        UnaccentExtension()
    ]
