# Generated by Django 3.0.5 on 2022-07-04 01:10

import apps.contrib.models
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0011_enable_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=utils.fields.CachedFileField(max_length=256, upload_to=apps.contrib.models.global_upload_to, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='exceldownload',
            name='file',
            field=utils.fields.CachedFileField(blank=True, max_length=256, null=True, upload_to=apps.contrib.models.excel_upload_to, verbose_name='Excel File'),
        ),
    ]
