# Generated by Django 3.0.5 on 2022-08-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0013_client_clienttrackinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrackinfo',
            name='api_type',
            field=models.CharField(choices=[('idus', 'Idus'), ('idus-all', 'Idus all'), ('idus-all-disaster', 'Idus all disaster')], max_length=40),
        ),
    ]
