# Generated by Django 3.2 on 2023-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0015_auto_20230207_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldownload',
            name='filters',
            field=models.JSONField(blank=True, null=True, verbose_name='Filters'),
        ),
    ]
