# Generated by Django 3.2 on 2023-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0016_alter_exceldownload_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrackinfo',
            name='api_type',
            field=models.CharField(choices=[('idus', 'Idus'), ('idus-all', 'Idus all'), ('idus-all-disaster', 'Idus all disaster'), ('gidd-countries-disaster-export-rest', 'Countries disaster export REST'), ('gidd-conflict-export-rest', 'Conflict export REST'), ('gidd-disaster-export-rest', 'Disaster export REST'), ('gidd-conflict', 'Gidd conflict'), ('gidd-disaster', 'Gidd disaster'), ('gidd-conflict-stat', 'Gidd conflict stat'), ('gidd-disaster-stat', 'Gidd disaster stat')], max_length=40),
        ),
    ]
