# Generated by Django 4.0 on 2023-06-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0024_alter_attachment_created_by_alter_client_created_by_and_more'),
        ('contrib', '0024_alter_clienttrackinfo_api_type'),
    ]

    operations = [
    ]
