# Generated by Django 3.2 on 2023-05-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    def update_is_active(apps, schema_editor):
        Client = apps.get_model('contrib', 'Client')
        Client.objects.update(is_active=True)

    dependencies = [
        ('contrib', '0024_client_is_active'),
    ]

    operations = [
        migrations.RunPython(update_is_active, reverse_code=migrations.RunPython.noop),
    ]
