# Generated by Django 3.2 on 2023-06-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0024_alter_clienttrackinfo_api_type'),
        ('contrib', '0026_alter_clienttrackinfo_api_type'),
    ]

    operations = [
    ]
