# Generated by Django 3.2 on 2023-12-12 11:43

import apps.contrib.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0028_alter_clienttrackinfo_api_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkApiOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('action', django_enumfield.db.fields.EnumField(enum=apps.contrib.models.BulkApiOperation.BULK_OPERATION_ACTION)),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='Filters')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Operation Payload')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.contrib.models.BulkApiOperation.BULK_OPERATION_STATUS)),
                ('success_count', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bulkapioperation', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
