# Generated by Django 3.2 on 2024-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0031_auto_20240326_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='revoked_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='revoked_by',
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Client Code'),
        ),
    ]
