# Generated by Django 3.2 on 2025-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0032_alter_clienttrackinfo_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded',
            field=models.BooleanField(default=True, verbose_name='Uploaded'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded',
            field=models.BooleanField(default=False, verbose_name='Uploaded'),
        ),
    ]
