# Generated by Django 3.2 on 2025-12-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0032_alter_clienttrackinfo_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='share_source',
            field=models.BooleanField(default=False, verbose_name='Share source?'),
        ),
    ]
