# Generated by Django 3.2 on 2026-01-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0033_auto_20251030_0925'),
        ('contrib', '0033_client_share_source'),
    ]

    operations = [
    ]
