# Generated by Django 3.2 on 2026-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0034_merge_20260102_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_website',
            field=models.URLField(blank=True, help_text='Client Contact Website: link to the website (IDMC application)', max_length=2000, null=True, verbose_name='Client Contact Website'),
        ),
    ]
