# Generated by Django 3.2 on 2026-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0035_alter_client_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='other_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
