# Generated by Django 3.2 on 2026-04-24 10:16

import apps.contrib.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0036_alter_client_other_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=django_enumfield.db.fields.EnumField(default=6, enum=apps.contrib.models.Client.CLIENT_TYPE),
        ),
    ]
