# Generated by Django 3.2 on 2026-04-27 03:40

from django.db import migrations
from django_enumfield import enum

class USE_CASE_TYPES(enum.Enum):
    ANTICIPATORY_ACTION = 0
    RESPONSE = 1
    PREVENTION = 2
    RESEARCH_DATA_ANALYSIS = 3
    MODELLING_FORECASTING = 4
    DATA_SHARING_EXTERNAL_REPOSITORIES = 5
    OTHER = 6


def migrate_notes_to_description(apps, schema_editor):
    Client = apps.get_model('contrib', 'Client')
    for obj in Client.objects.all():
        use_cases = obj.use_cases or []
        has_other = USE_CASE_TYPES.OTHER in use_cases

        if not has_other:
            continue

        if obj.other_notes:
            obj.description = obj.other_notes

        non_other = [x for x in use_cases if x != USE_CASE_TYPES.OTHER]
        if non_other:
            obj.use_cases = non_other
            obj.other_notes = None

        obj.save(update_fields=["description", "use_cases", "other_notes"])

class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0037_client_description'),
    ]

    operations = [
        migrations.RunPython(migrate_notes_to_description, reverse_code=migrations.RunPython.noop),
    ]
