# Generated by Django 3.2 on 2026-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0038_auto_20260427_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrackinfo',
            name='api_type',
            field=models.CharField(choices=[('idus', '/external-api/idus/last-180-days/'), ('idus-all', '/external-api/idus/all/'), ('idus-all-disaster', '/external-api/idus/all/disaster/'), ('idus-excel', '/external-api/idus/last-180-days-excel/'), ('idus-geojson', '/external-api/idus/last-180-days-geojson/'), ('idus-all-excel', '/external-api/idus/all-excel/'), ('idus-all-geojson', '/external-api/idus/all-geojson/'), ('idus-all-disaster-excel', '/external-api/idus/all/disaster-excel/'), ('idus-all-disaster-geojson', '/external-api/idus/all/disaster-geojson/'), ('gidd-country-rest', '/external-api/gidd/countries/'), ('gidd-conflict-rest', '/external-api/gidd/conflicts/'), ('gidd-disaster-rest', '/external-api/gidd/disasters/'), ('gidd-displacement-rest', '/external-api/gidd/displacements/'), ('gidd-disaster-export-rest', '/external-api/gidd/disasters/export/'), ('gidd-displacement-export-rest', '/external-api/gidd/displacements/export/'), ('gidd-public-figure-analysis-rest', '/external-api/gidd/public-figure-analyses/'), ('gidd-disaggregation-export-geojson-rest', '/external-api/gidd/disaggregations/disaggregated-geojson/'), ('gidd-disaggregation-export-xlsx-rest', '/external-api/gidd/disaggregations/disaggregated-export/'), ('gidd-conflict-graphql', 'query.giddPublicConflicts'), ('gidd-disaster-graphql', 'query.giddPublicDisasters'), ('gidd-displacement-data-graphql', 'query.giddPublicDisplacements'), ('gidd-public-figure-analysis-graphql', 'query.giddPublicFigureAnalysisList'), ('gidd-conflict-stat-graphql', 'query.giddPublicConflictStatistics'), ('gidd-disaster-stat-graphql', 'query.giddPublicDisasterStatistics'), ('gidd-hazard-type-graphql', 'query.giddPublicHazardTypes'), ('gidd-year-graphql', 'query.giddPublicYear'), ('gidd-event-graphql', 'query.giddPublicEvent'), ('gidd-combined-stat-graphql', 'query.giddPublicCombinedStatistics'), ('gidd-release-meta-data-graphql', 'query.giddPublicReleaseMetaData'), ('gidd-public-countries-graphql', 'query.giddPublicCountries')], max_length=40),
        ),
    ]
