# Generated by Django 3.2 on 2026-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0039_alter_clienttrackinfo_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldownload',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
