# Generated by Django 3.0.5 on 2020-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_accessed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed On'),
        ),
    ]
