# Generated by Django 3.0.5 on 2020-09-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20200901_0428_squashed_0004_contextualupdate_summary'),
        ('resource', '0002_resource_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='countries',
            field=models.ManyToManyField(related_name='_resource_countries_+', to='country.Country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resource.ResourceGroup', verbose_name='Resource Group'),
        ),
    ]
