# Generated by Django 3.0.5 on 2022-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20201231_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='URL'),
        ),
    ]
