# Generated by Django 4.0 on 2023-06-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_alter_contextualanalysis_created_by_and_more'),
        ('users', '0006_alter_user_first_name'),
        ('resource', '0004_auto_20220629_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='countries',
            field=models.ManyToManyField(related_name='+', to='country.Country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
    ]
