{{- if .Values.worker.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helix-backend.fullname" . }}-worker-beat
  labels:
    app: {{ include "helix-backend.fullname" . }}
    component: worker-beat
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1  # This should only 1
  selector:
    matchLabels:
      app: {{ include "helix-backend.fullname" . }}
      component: worker-beat
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print .Template.BasePath "/config/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print .Template.BasePath "/config/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "helix-backend.fullname" . }}
        component: worker-beat
    spec:
      containers:
        - name: worker-beat
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy:  {{ .Values.image.imagePullPolicy  }}
          command: ["celery", "-A", "helix", "beat", "-l", "INFO"]
          # TODO: livenessProbe
          resources:
            {{- toYaml .Values.worker.beat.resources | nindent 12 }}
          env:
            - name: DJANGO_APP_TYPE
              value: worker
          envFrom:
            - secretRef:
                name: {{ template "helix-backend.secretname" . }}
            - configMapRef:
                name: {{ template "helix-backend.envConfigMapName" . }}

{{- end }}
