# Generated by Django 3.0.5 on 2021-01-27 05:26

import apps.parking_lot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0007_auto_20210105_0431'),
        ('parking_lot', '0002_auto_20210119_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('title', models.TextField(verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.parking_lot.models.ParkedItem.PARKING_LOT_STATUS)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parked_items', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_items', to='country.Country', verbose_name='Country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parkeditem', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
