# Generated by Django 3.0.5 on 2021-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0002_auto_20201019_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='crisis',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
