# Generated by Django 3.0.5 on 2020-10-19 07:58

import apps.crisis.models
from django.db import migrations, models
import django.utils.timezone
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('version_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Version')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('crisis_type', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('crisis_narrative', models.TextField(verbose_name='Crisis Narrative/Summary')),
                ('countries', models.ManyToManyField(related_name='crises', to='country.Country', verbose_name='Countries')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
