# Generated by Django 3.0.5 on 2020-08-19 09:04

import apps.crisis.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_auto_20200819_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('crisis_type', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('crisis_narrative', models.TextField(verbose_name='Crisis Narrative/Summary')),
                ('countries', models.ManyToManyField(related_name='crises', to='country.Country', verbose_name='Countries')),
            ],
        ),
    ]
