# Generated by Django 3.2 on 2024-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0005_auto_20210330_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
