# Generated by Django 3.2 on 2026-06-20 06:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0006_alter_crisis_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crisis',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=True), name='crisis_created_at_desc_idx'),
        ),
    ]
