# Generated by Django 3.2 on 2023-04-17 07:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_fix_drought_and_cold_wave_data_migration'),
        ('gidd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='children_born_to_idps',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='children_born_to_idps_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='children_born_to_idps_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='cross_border_flight',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='cross_border_flight_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='cross_border_flight_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='idp_deaths',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='idp_deaths_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='idp_deaths_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='local_integration',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='local_integration_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='local_integration_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='new_displacement_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='new_displacement_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='resettlement',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='resettlement_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='resettlement_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='returns',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='returns_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='returns_source',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='total_displacement_since',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='total_displacement_source',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='country',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='glide_number',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='new_displacement_since',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='new_displacement_source',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='old_id',
        ),
        migrations.AddField(
            model_name='conflict',
            name='country_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='iso3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ISO3'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='country_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None, verbose_name='Country names'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gidd_figures', to='event.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='iso3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, null=True, size=None, verbose_name="Iso3's"),
        ),
    ]
