# Generated by Django 3.2 on 2023-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0003_giddlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_displacement', models.BigIntegerField(blank=True, null=True)),
                ('new_displacement', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField()),
                ('country_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('iso3', models.CharField(blank=True, max_length=5, null=True, verbose_name='ISO3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legacy conflict',
                'verbose_name_plural': 'Legacy conflicts',
            },
        ),
        migrations.CreateModel(
            name='DisasterLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField()),
                ('country_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('iso3', models.CharField(blank=True, max_length=5, null=True, verbose_name='ISO3')),
                ('event_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Event name')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_accuracy', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_accuracy', models.TextField(blank=True, null=True)),
                ('hazard_category', models.TextField(blank=True, null=True)),
                ('hazard_sub_category', models.TextField(blank=True, null=True)),
                ('hazard_sub_type', models.TextField(blank=True, null=True)),
                ('hazard_type', models.TextField(blank=True, null=True)),
                ('new_displacement', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legacy disaster',
                'verbose_name_plural': 'Legacy disasters',
            },
        ),
        migrations.AddField(
            model_name='disaster',
            name='event_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Event name'),
        ),
    ]
