# Generated by Django 3.2 on 2023-04-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0016_update_idmc_short_names'),
        ('event', '0031_fix_drought_and_cold_wave_data_migration'),
        ('gidd', '0007_alter_disaster_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='hazard_category_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disaster',
            name='hazard_sub_category_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disaster',
            name='hazard_sub_type_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disaster',
            name='hazard_type_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disasterlegacy',
            name='hazard_category_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disasterlegacy',
            name='hazard_sub_category_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disasterlegacy',
            name='hazard_sub_type_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='disasterlegacy',
            name='hazard_type_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_conflict', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='iso3',
            field=models.CharField(max_length=5, verbose_name='ISO3'),
        ),
        migrations.AlterField(
            model_name='conflictlegacy',
            name='country_name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='conflictlegacy',
            name='iso3',
            field=models.CharField(max_length=5, verbose_name='ISO3'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_disaster', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='country_name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gidd_events', to='event.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='event_name',
            field=models.CharField(max_length=256, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disasters', to='event.disastercategory', verbose_name='Hazard Category'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disasters', to='event.disastersubcategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disasters', to='event.disastersubtype', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disasters', to='event.disastertype', verbose_name='Hazard Type'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='iso3',
            field=models.CharField(max_length=5, verbose_name='ISO3'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='country_name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='event_name',
            field=models.CharField(max_length=256, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_disasters', to='event.disastercategory', verbose_name='Hazard Category'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_disasters', to='event.disastersubcategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_disasters', to='event.disastersubtype', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_disasters', to='event.disastertype', verbose_name='Hazard Type'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='iso3',
            field=models.CharField(max_length=5, verbose_name='ISO3'),
        ),
    ]
