# Generated by Django 3.2 on 2023-04-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_fix_drought_and_cold_wave_data_migration'),
        ('gidd', '0008_auto_20230425_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gidd_events', to='event.event', verbose_name='Event'),
        ),
    ]
