# Generated by Django 3.2 on 2023-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0009_alter_disaster_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='country_name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
