# Generated by Django 3.2 on 2023-04-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0010_alter_conflict_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasemetadata',
            options={'permissions': (('update_release_meta_data', 'Can update release meta data'),)},
        ),
    ]
