# Generated by Django 3.2 on 2023-04-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0011_alter_releasemetadata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasemetadata',
            options={'permissions': (('update_release_meta_data_gidd', 'Can update release meta data'),)},
        ),
        migrations.AlterModelOptions(
            name='statuslog',
            options={'permissions': (('update_gidd_data_gidd', 'Can update gidd data'),)},
        ),
    ]
