# Generated by Django 3.2 on 2023-04-28 07:31

import apps.crisis.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_fix_drought_and_cold_wave_data_migration'),
        ('country', '0016_update_idmc_short_names'),
        ('gidd', '0014_alter_disaster_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='total_displacement',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DisplacementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=5, verbose_name='ISO3')),
                ('country_name', models.CharField(max_length=256, verbose_name='Country name')),
                ('conflict_total_idps', models.BigIntegerField(null=True, verbose_name='Conflict total idps')),
                ('conflict_total_nd', models.BigIntegerField(null=True, verbose_name='Conflict total nd')),
                ('cause', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacements', to='country.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='DisasterByHazardSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=5, verbose_name='ISO3')),
                ('disaster_total_idps', models.BigIntegerField(null=True, verbose_name='Disaster total nds')),
                ('disaster_total_nd', models.BigIntegerField(null=True, verbose_name='Disaster total nd')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('displacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disasters', to='gidd.displacementdata', verbose_name='Displacements')),
                ('hazard_sub_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displacements', to='event.disastersubtype', verbose_name='Hazard Sub Type')),
            ],
        ),
    ]
