# Generated by Django 3.2 on 2023-04-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0013_publicfigureanalysis'),
        ('gidd', '0014_alter_disaster_event'),
    ]

    operations = [
    ]
