# Generated by Django 3.2 on 2023-04-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0052_alter_report_is_gidd_report'),
        ('gidd', '0015_merge_20230429_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfigureanalysis',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publicfigureanalysis',
            name='figures',
            field=models.IntegerField(null=True, verbose_name='Figures'),
        ),
        migrations.AlterField(
            model_name='publicfigureanalysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicfigureanalysis',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='report.report', verbose_name='Report'),
        ),
    ]
