# Generated by Django 3.2 on 2023-04-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0015_alter_statuslog_options'),
        ('gidd', '0016_auto_20230429_0947'),
    ]

    operations = [
    ]
