# Generated by Django 3.2 on 2023-04-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0015_auto_20230428_0731'),
        ('gidd', '0017_merge_20230429_1056'),
    ]

    operations = [
    ]
