# Generated by Django 3.2 on 2023-04-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0018_merge_20230429_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterbyhazardsubtype',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='disasterbyhazardsubtype',
            name='year',
        ),
    ]
