# Generated by Django 3.2 on 2023-04-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0019_auto_20230429_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictlegacy',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='disasterlegacy',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='disasterlegacy',
            name='hazard_category_name',
        ),
        migrations.RemoveField(
            model_name='disasterlegacy',
            name='hazard_sub_category_name',
        ),
        migrations.RemoveField(
            model_name='disasterlegacy',
            name='hazard_sub_type_name',
        ),
        migrations.RemoveField(
            model_name='disasterlegacy',
            name='hazard_type_name',
        ),
    ]
