# Generated by Django 3.2 on 2023-04-30 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0031_fix_drought_and_cold_wave_data_migration'),
        ('gidd', '0020_auto_20230430_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='hazard_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disasters', to='event.disastercategory', verbose_name='Hazard Category'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disasters', to='event.disastersubcategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disasters', to='event.disastersubtype', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='hazard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disasters', to='event.disastertype', verbose_name='Hazard Type'),
        ),
        migrations.AlterField(
            model_name='disasterbyhazardsubtype',
            name='hazard_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacements', to='event.disastersubtype', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_disasters', to='event.disastercategory', verbose_name='Hazard Category'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_disasters', to='event.disastersubcategory', verbose_name='Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_disasters', to='event.disastersubtype', verbose_name='Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='disasterlegacy',
            name='hazard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_disasters', to='event.disastertype', verbose_name='Hazard Type'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gidd_data_triggered_by', to='users.user', verbose_name='Triggered by'),
        ),
    ]
