# Generated by Django 3.2 on 2023-04-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0021_auto_20230430_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterbyhazardsubtype',
            name='displacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disasters', to='gidd.displacementdata', verbose_name='Displacements'),
        ),
    ]
