# Generated by Django 3.2 on 2023-05-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0022_alter_disasterbyhazardsubtype_displacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displacementdata',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='displacementdata',
            name='conflict_total_idps',
        ),
        migrations.RemoveField(
            model_name='displacementdata',
            name='conflict_total_nd',
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='conflict_new_displacement',
            field=models.BigIntegerField(null=True, verbose_name='Conflict total nd'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='conflict_total_displacement',
            field=models.BigIntegerField(null=True, verbose_name='Conflict total idps'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='disaster_new_displacement',
            field=models.BigIntegerField(null=True, verbose_name='Disaster total nd'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='disaster_total_displacement',
            field=models.BigIntegerField(null=True, verbose_name='Disaster total nds'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='total_internal_displacement',
            field=models.BigIntegerField(null=True, verbose_name='Total internal displacement'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='total_new_displacement',
            field=models.BigIntegerField(null=True, verbose_name='Total new displacement'),
        ),
        migrations.DeleteModel(
            name='DisasterByHazardSubType',
        ),
    ]
