# Generated by Django 3.2 on 2023-05-02 05:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0023_auto_20230501_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='glide_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Event Codes'), blank=True, default=list, null=True, size=None),
        ),
    ]
