# Generated by Django 3.2 on 2023-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0023_auto_20230501_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasemetadata',
            name='production_year',
        ),
        migrations.RemoveField(
            model_name='releasemetadata',
            name='staging_year',
        ),
        migrations.AddField(
            model_name='releasemetadata',
            name='pre_release_year',
            field=models.IntegerField(verbose_name='Pre Release year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releasemetadata',
            name='release_year',
            field=models.IntegerField(verbose_name='Release year'),
            preserve_default=False,
        ),
    ]
