# Generated by Django 3.2 on 2023-05-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0024_auto_20230502_0927'),
        ('gidd', '0024_disaster_glide_numbers'),
    ]

    operations = [
    ]
