# Generated by Django 3.2 on 2023-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0025_merge_20230502_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasemetadata',
            name='pre_release_year',
            field=models.IntegerField(verbose_name='Pre-Release year'),
        ),
    ]
