# Generated by Django 3.2 on 2023-05-04 09:37

import apps.crisis.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0016_update_idmc_short_names'),
        ('gidd', '0026_alter_releasemetadata_pre_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdpsSaddEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=5, verbose_name='ISO3')),
                ('country_name', models.CharField(max_length=256, verbose_name='Country name')),
                ('year', models.IntegerField()),
                ('sex', models.CharField(max_length=256, verbose_name='Country name')),
                ('cause', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('zero_to_one', models.IntegerField(null=True, verbose_name='0-1')),
                ('zero_to_four', models.IntegerField(null=True, verbose_name='0-4')),
                ('zero_to_forteen', models.IntegerField(null=True, verbose_name='0-14')),
                ('zero_to_sventeen', models.IntegerField(null=True, verbose_name='0-17')),
                ('zero_to_twenty_four', models.IntegerField(null=True, verbose_name='0-24')),
                ('five_to_elaven', models.IntegerField(null=True, verbose_name='5-11')),
                ('five_to_fourteen', models.IntegerField(null=True, verbose_name='5-14')),
                ('twelve_to_fourteen', models.IntegerField(null=True, verbose_name='12-14')),
                ('twelve_to_sixteen', models.IntegerField(null=True, verbose_name='12-16')),
                ('fifteen_to_seventeen', models.IntegerField(null=True, verbose_name='15-17')),
                ('fifteen_to_twentyfour', models.IntegerField(null=True, verbose_name='15-24')),
                ('twenty_five_to_sixty_four', models.IntegerField(null=True, verbose_name='25-64')),
                ('sixty_five_plus', models.IntegerField(null=True, verbose_name='65+')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipds_sadd_estimates', to='country.country', verbose_name='Country')),
            ],
        ),
    ]
