# Generated by Django 3.2 on 2023-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0026_alter_releasemetadata_pre_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='new_displacement_rounded',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='total_displacement_rounded',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disaster',
            name='new_displacement_rounded',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disaster',
            name='total_displacement_rounded',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='conflict_new_displacement_rounded',
            field=models.BigIntegerField(null=True, verbose_name='Conflict total nd'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='conflict_total_displacement_rounded',
            field=models.BigIntegerField(null=True, verbose_name='Conflict total idps'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='disaster_new_displacement_rounded',
            field=models.BigIntegerField(null=True, verbose_name='Disaster total nd'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='disaster_total_displacement_rounded',
            field=models.BigIntegerField(null=True, verbose_name='Disaster total nds'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='total_internal_displacement_rounded',
            field=models.BigIntegerField(null=True, verbose_name='Total internal displacement'),
        ),
        migrations.AddField(
            model_name='displacementdata',
            name='total_new_displacement_rounded',
            field=models.BigIntegerField(null=True, verbose_name='Total new displacement'),
        ),
    ]
