# Generated by Django 3.2 on 2023-05-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0027_auto_20230509_1226'),
        ('gidd', '0027_idpssaddestimate'),
    ]

    operations = [
    ]
