# Generated by Django 3.2 on 2024-01-03 06:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0028_auto_20230509_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='event_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Codes'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='disaster',
            name='event_code_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Code Types'), default=list, size=None),
        ),
    ]
