# Generated by Django 3.2 on 2023-05-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0028_merge_0027_auto_20230509_1226_0027_idpssaddestimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displacementdata',
            name='total_internal_displacement_rounded',
        ),
        migrations.RemoveField(
            model_name='displacementdata',
            name='total_new_displacement_rounded',
        ),
    ]
