# Generated by Django 3.2 on 2024-01-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0029_auto_20240103_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disaster',
            old_name='event_code',
            new_name='event_codes',
        ),
        migrations.RenameField(
            model_name='disaster',
            old_name='event_code_type',
            new_name='event_codes_type',
        ),
    ]
