# Generated by Django 3.2 on 2024-05-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0033_giddevent_giddfigure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='glide_numbers',
        ),
        migrations.RemoveField(
            model_name='giddevent',
            name='glide_numbers',
        ),
    ]
