# Generated by Django 3.2 on 2025-02-12 06:14

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0035_giddevent_giddfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='event_raw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddevent',
            name='event_raw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddfigure',
            name='entry_raw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddfigure',
            name='figure_raw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicfigureanalysis',
            name='report_raw_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
