# Generated by Django 3.2 on 2025-02-12 06:14

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0035_giddevent_giddfigure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disaster',
            old_name='event',
            new_name='event_reference',
        ),
        migrations.RenameField(
            model_name='giddevent',
            old_name='event',
            new_name='event_reference',
        ),
        migrations.RenameField(
            model_name='giddfigure',
            old_name='entry',
            new_name='entry_reference',
        ),
        migrations.RenameField(
            model_name='giddfigure',
            old_name='figure',
            new_name='figure_reference',
        ),
        migrations.RenameField(
            model_name='publicfigureanalysis',
            old_name='report',
            new_name='report_reference',
        ),
        migrations.AddField(
            model_name='disaster',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddevent',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddfigure',
            name='entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddfigure',
            name='figure_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicfigureanalysis',
            name='report_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]