# Generated by Django 3.2 on 2025-02-12 07 :14

from django.db import migrations, models


def set_default_values(apps, schema_editor):
    Disaster = apps.get_model('gidd', 'Disaster')
    Giddevent = apps.get_model('gidd', 'GiddEvent')
    GiddFigure = apps.get_model('gidd', 'GiddFigure')
    PublicFigureAnalysis = apps.get_model('gidd', 'PublicFigureAnalysis')

    Disaster.objects.update(
        event_raw_id=models.F('event_id')
    )
    Giddevent.objects.update(
        event_raw_id=models.F('event_id')
    )
    GiddFigure.objects.update(
        entry_raw_id=models.F('entry_id'),
        figure_raw_id=models.F('figure_id')
    )
    PublicFigureAnalysis.objects.update(
        report_raw_id=models.F('report_id')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('gidd', '0036_auto_20250212_0614'),
    ]

    operations = [
        migrations.RunPython(set_default_values, reverse_code=migrations.RunPython.noop),
    ]
