# Generated by Django 3.2 on 2026-08-19 04:06

import apps.crisis.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20260225_0529'),
        ('country', '0023_auto_20260603_0608'),
        ('gidd', '0038_disaster_event_name_trgm_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiddEventDisplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_raw_id', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=256, verbose_name='Event name')),
                ('iso3', models.CharField(max_length=5, verbose_name='ISO3')),
                ('country_name', models.CharField(max_length=256, verbose_name='Country name')),
                ('year', models.IntegerField()),
                ('cause', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Codes'), default=list, size=None)),
                ('violence_name', models.CharField(blank=True, max_length=256, null=True)),
                ('violence_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_category_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_sub_category_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('new_displacement', models.BigIntegerField(blank=True, null=True)),
                ('new_displacement_rounded', models.BigIntegerField(blank=True, null=True)),
                ('total_displacement', models.BigIntegerField(blank=True, null=True)),
                ('total_displacement_rounded', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gidd_event_displacements', to='country.country')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.event')),
                ('hazard_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastercategory')),
                ('hazard_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastersubcategory')),
                ('hazard_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastersubtype')),
                ('hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastertype')),
                ('violence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.violence')),
                ('violence_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.violencesubtype')),
            ],
            options={
                'verbose_name': 'GIDD Event Displacement',
                'verbose_name_plural': 'GIDD Event Displacements',
            },
        ),
        migrations.CreateModel(
            name='GiddDisplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=5, verbose_name='ISO3')),
                ('country_name', models.CharField(max_length=256, verbose_name='Country name')),
                ('year', models.IntegerField()),
                ('cause', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('violence_name', models.CharField(blank=True, max_length=256, null=True)),
                ('violence_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_category_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_sub_category_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hazard_sub_type_name', models.CharField(blank=True, max_length=256, null=True)),
                ('new_displacement', models.BigIntegerField(blank=True, null=True)),
                ('new_displacement_rounded', models.BigIntegerField(blank=True, null=True)),
                ('total_displacement', models.BigIntegerField(blank=True, null=True)),
                ('total_displacement_rounded', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gidd_displacements', to='country.country')),
                ('hazard_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastercategory')),
                ('hazard_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastersubcategory')),
                ('hazard_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastersubtype')),
                ('hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.disastertype')),
                ('violence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.violence')),
                ('violence_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event.violencesubtype')),
            ],
            options={
                'verbose_name': 'GIDD Disaggregated Displacement',
                'verbose_name_plural': 'GIDD Disaggregated Displacements',
            },
        ),
    ]
