# Generated by Django 3.2 on 2026-08-19 06:48

import apps.entry.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0039_add_gidd_displacement_and_event_displacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='giddeventdisplacement',
            name='displacement_occurred',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.DISPLACEMENT_OCCURRED), default=list, size=None),
        ),
        migrations.AddField(
            model_name='giddeventdisplacement',
            name='end_date_accuracy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giddeventdisplacement',
            name='event_codes_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Event Code Types'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='giddeventdisplacement',
            name='glide_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Glide Numbers'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='giddeventdisplacement',
            name='start_date_accuracy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
