# Generated by Django 3.2 on 2026-08-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0040_giddeventdisplacement_rest_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='country',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='event',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='hazard_category',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='hazard_sub_category',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='hazard_sub_type',
        ),
        migrations.RemoveField(
            model_name='disaster',
            name='hazard_type',
        ),
        migrations.DeleteModel(
            name='Conflict',
        ),
        migrations.DeleteModel(
            name='Disaster',
        ),
    ]
