# Generated by Django 3.2 on 2026-07-15 02:18

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("gidd", "0038_disaster_event_name_trgm_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaster",
            name="end_date_accuracy",
            field=utils.fields.UnbleachedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disaster",
            name="start_date_accuracy",
            field=utils.fields.UnbleachedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasterlegacy",
            name="end_date_accuracy",
            field=utils.fields.UnbleachedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasterlegacy",
            name="start_date_accuracy",
            field=utils.fields.UnbleachedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giddfigure",
            name="calculation_logic",
            field=utils.fields.UnbleachedTextField(blank=True, null=True, verbose_name="Analysis and Calculation Logic"),
        ),
        migrations.AlterField(
            model_name="giddfigure",
            name="excerpt_idu",
            field=utils.fields.UnbleachedTextField(blank=True, null=True, verbose_name="Excerpt for IDU"),
        ),
        migrations.AlterField(
            model_name="giddfigure",
            name="source_excerpt",
            field=utils.fields.UnbleachedTextField(blank=True, null=True, verbose_name="Excerpt from Source"),
        ),
        migrations.AlterField(
            model_name="publicfigureanalysis",
            name="description",
            field=utils.fields.UnbleachedTextField(null=True, verbose_name="Description"),
        ),
    ]
