# Generated by Django 3.2 on 2026-08-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gidd', '0041_remove_conflict_and_disaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConflictLegacy',
        ),
        migrations.RemoveField(
            model_name='displacementdata',
            name='country',
        ),
        migrations.DeleteModel(
            name='DisasterLegacy',
        ),
        migrations.DeleteModel(
            name='DisplacementData',
        ),
    ]
