apiVersion: v2
name: helix-backend-helm
description: "Helm Chart to deploy the IDMC Helix Backend"
type: application
version: 0.0.1-SET-BY-CICD
sources:
  - https://github.com/idmc-labs/helix-server

dependencies:
  - name: banjo-helm
    alias: app
    version: 0.3.0
    repository: oci://ghcr.io/toggle-corp
