# Generated by Django 3.2 on 2026-05-16 13:57

import apps.hulk.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_auto_20260225_0529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0107_auto_20260225_0529'),
        ('contrib', '0036_alter_client_other_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HulkBulkImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.hulk.models.HulkBulkImport.HULK_BULK_IMPORT_STATUS)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hulkbulkimport', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'permissions': (('bulk_import_hulkbulkimport', 'Can trigger hulk bulk import'),),
            },
        ),
        migrations.CreateModel(
            name='HulkSourcePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.sourcepreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HulkFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.figure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HulkEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HulkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HulkBulkImportDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', django_enumfield.db.fields.EnumField(enum=apps.hulk.models.HulkBulkImportDataset.HULK_BULK_IMPORT_DATASET_IMPORT_TYPE)),
                ('import_file', utils.fields.CachedFileField(max_length=2000, upload_to=apps.hulk.models.upload_dataset_import_file, verbose_name='Import JSONL')),
                ('success_file', utils.fields.CachedFileField(blank=True, max_length=2000, null=True, upload_to=apps.hulk.models.upload_dataset_success_file, verbose_name='Success JSONL')),
                ('failure_file', utils.fields.CachedFileField(blank=True, max_length=2000, null=True, upload_to=apps.hulk.models.upload_dataset_failure_file, verbose_name='Failure JSONL')),
                ('success_count', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='hulk.hulkbulkimport', verbose_name='Bulk Import')),
            ],
        ),
        migrations.CreateModel(
            name='HulkAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='hulkbulkimportdataset',
            constraint=models.UniqueConstraint(fields=('bulk_import', 'import_type'), name='hulk_dataset_unique_type_per_bulk'),
        ),
    ]
