# Generated by Django 3.2 on 2026-01-15 09:45

import apps.hulk.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0104_auto_20250331_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='HulkBulkImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('payload', utils.fields.CachedFileField(max_length=2000, upload_to=apps.hulk.models.bulk_operation_payload, verbose_name='Import data snapshot')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.hulk.models.HulkBulkImport.HULK_BULK_IMPORT_STATUS)),
                ('success_count', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(blank=True, null=True)),
                ('success_dataset', utils.fields.CachedFileField(max_length=2000, upload_to=apps.hulk.models.bulk_operation_payload, verbose_name='Success data snapshot')),
                ('failure_dataset', models.JSONField(default=list)),
                ('snapshot', utils.fields.CachedFileField(blank=True, max_length=2000, null=True, upload_to=apps.hulk.models.bulk_operation_snapshot, verbose_name='Existing data snapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hulkbulkimport', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='HulkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.entry')),
            ],
        ),
    ]
