# Generated by Django 3.2 on 2026-01-21 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_auto_20240326_0824'),
        ('hulk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HulkEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
