# Generated by Django 3.2 on 2026-01-21 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0105_externalapidump_include_sources'),
        ('hulk', '0002_hulkevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HulkFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.figure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
