# Generated by Django 3.2 on 2026-03-13 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0035_alter_client_contact_website'),
        ('hulk', '0003_hulkfigure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hulkentry',
            old_name='entry',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='hulkevent',
            old_name='event',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='hulkfigure',
            old_name='figure',
            new_name='entity',
        ),
        migrations.CreateModel(
            name='HulkSourcePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.sourcepreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HulkAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hulk.hulkbulkimport')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
