# Generated by Django 3.2 on 2026-05-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0036_alter_client_other_notes'),
        ('entry', '0107_auto_20260225_0529'),
        ('event', '0002_auto_20260225_0529'),
        ('hulk', '0003_rename_bulk_import_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hulkattachment',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contrib.attachment'),
        ),
        migrations.AlterField(
            model_name='hulkentry',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.entry'),
        ),
        migrations.AlterField(
            model_name='hulkevent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='hulkfigure',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.figure'),
        ),
        migrations.AlterField(
            model_name='hulksourcepreview',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contrib.sourcepreview'),
        ),
    ]
