# Generated by Django 3.2 on 2026-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hulk', '0005_hulk_dataset_skip_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hulkbulkimport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
