# Generated by Django 3.0.5 on 2020-08-28 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_squashed_0005_auto_20200826_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
