# Generated by Django 3.0.5 on 2020-08-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_squashed_0005_auto_20200826_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='entry/documents', verbose_name='document'),
        ),
    ]
