# Generated by Django 3.0.5 on 2020-08-28 09:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('entry', '0003_auto_20200828_0833'), ('entry', '0004_auto_20200828_0913')]

    dependencies = [
        ('entry', '0002_figure_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='age_json',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Age'), blank=True, null=True, size=None, verbose_name='Age Disaggregation'),
        ),
        migrations.AddField(
            model_name='figure',
            name='conflict',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conflict/Conflict'),
        ),
        migrations.AddField(
            model_name='figure',
            name='conflict_communal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conflict/Violence-Communal'),
        ),
        migrations.AddField(
            model_name='figure',
            name='conflict_criminal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conflict/Violence-Criminal'),
        ),
        migrations.AddField(
            model_name='figure',
            name='conflict_other',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='figure',
            name='conflict_political',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conflict/Violence-Political'),
        ),
        migrations.AddField(
            model_name='figure',
            name='is_disaggregated',
            field=models.BooleanField(default=False, verbose_name='Is disaggregated'),
        ),
        migrations.AddField(
            model_name='figure',
            name='strata_json',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Stratum'), blank=True, null=True, size=None, verbose_name='Strata Disaggregation'),
        ),
        migrations.AddField(
            model_name='figure',
            name='displacement_rural',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Displacement/Rural'),
        ),
        migrations.AddField(
            model_name='figure',
            name='displacement_urban',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Displacement/Urban'),
        ),
        migrations.AddField(
            model_name='figure',
            name='location_camp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Location/Camp'),
        ),
        migrations.AddField(
            model_name='figure',
            name='location_non_camp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Location/Non-Camp'),
        ),
        migrations.AddField(
            model_name='figure',
            name='sex_female',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sex/Female'),
        ),
        migrations.AddField(
            model_name='figure',
            name='sex_male',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sex/Male'),
        ),
    ]
