# Generated by Django 3.0.5 on 2020-10-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20201019_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepreview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Pdf URL'),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Error Reason'),
        ),
        migrations.AddField(
            model_name='sourcepreview',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Token'),
        ),
    ]
