# Generated by Django 3.0.5 on 2020-08-31 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_entry_document'),
        ('entry', '0003_auto_20200828_0833_squashed_0004_auto_20200828_0913'),
    ]

    operations = [
    ]
