# Generated by Django 3.0.5 on 2020-10-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20201030_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcepreview',
            name='pdf_url',
        ),
    ]
