# Generated by Django 3.0.5 on 2020-09-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20200902_0704'),
        ('entry', '0004_merge_20200831_0304'),
    ]

    operations = [
    ]
