# Generated by Django 3.0.5 on 2020-11-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_auto_20201106_0834'),
        ('entry', '0006_remove_entry_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contrib.Attachment', verbose_name='Attachment'),
        ),
    ]
