# Generated by Django 3.0.5 on 2020-12-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20201105_0537'),
        ('entry', '0018_auto_20201209_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='country.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='figure',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
