# Generated by Django 3.0.5 on 2020-12-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_auto_20201228_0441'),
        ('entry', '0017_auto_20201210_0438'),
    ]

    operations = [
    ]
