# Generated by Django 3.0.5 on 2020-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_merge_20201228_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='sources',
        ),
        migrations.AddField(
            model_name='figure',
            name='geo_locations',
            field=models.ManyToManyField(related_name='_figure_geo_locations_+', to='entry.OSMName', verbose_name='Geo Locations'),
        ),
    ]
