# Generated by Django 3.0.5 on 2020-12-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_auto_20201228_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='household_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Household Size'),
        ),
    ]
