# Generated by Django 3.0.5 on 2021-01-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_auto_20201230_0426'),
        ('entry', '0019_auto_20201231_0707'),
    ]

    operations = [
    ]
