# Generated by Django 3.0.5 on 2021-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_auto_20210104_0947'),
        ('entry', '0024_merge_20210104_0911'),
    ]

    operations = [
    ]
