# Generated by Django 3.0.5 on 2021-01-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_auto_20210108_0646'),
        ('entry', '0025_merge_20210106_0651'),
    ]

    operations = [
    ]
