# Generated by Django 3.0.5 on 2021-01-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_merge_20210112_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurecategory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
