# Generated by Django 3.0.5 on 2021-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0027_auto_20210112_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='District(s)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='town',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Town/Village'),
        ),
    ]
