# Generated by Django 3.0.5 on 2021-01-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0003_auto_20210127_0526'),
        ('entry', '0029_auto_20210122_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='associated_parked_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry', to='parking_lot.ParkedItem'),
        ),
    ]
