# Generated by Django 3.0.5 on 2021-02-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_auto_20210129_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osmname',
            name='reported_name',
        ),
        migrations.AddField(
            model_name='figure',
            name='is_housing_destruction',
            field=models.BooleanField(default=False, verbose_name='Housing destruction (recommended estimate for this entry)'),
        ),
    ]
