# Generated by Django 3.0.5 on 2021-02-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_entry_associated_parked_item'),
        ('entry', '0031_auto_20210202_0517'),
    ]

    operations = [
    ]
