# Generated by Django 3.0.5 on 2021-03-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_auto_20210305_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisaggregatedAgeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
            ],
        ),
    ]
