# Generated by Django 3.0.5 on 2021-03-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_auto_20210305_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='term',
        ),
        migrations.CreateModel(
            name='FigureTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_housing_related', models.BooleanField(default=False, verbose_name='Is housing related')),
                ('identifier', models.CharField(max_length=32, verbose_name='Identifier')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='figure',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entry.FigureTerm', verbose_name='Figure term'),
        ),
    ]
