# Generated by Django 3.0.5 on 2021-03-24 05:33

import apps.contrib.commons
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_auto_20210319_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='end_date_accuracy',
            field=django_enumfield.db.fields.EnumField(enum=apps.contrib.commons.DATE_ACCURACY, null=True),
        ),
    ]
