# Generated by Django 3.0.5 on 2021-03-30 09:05

import apps.contrib.commons
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_auto_20210324_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='end_date_accuracy',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.contrib.commons.DATE_ACCURACY, null=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='start_date_accuracy',
            field=django_enumfield.db.fields.EnumField(blank=True, default=0, enum=apps.contrib.commons.DATE_ACCURACY, null=True),
        ),
    ]
