# Generated by Django 3.0.5 on 2021-03-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_auto_20210324_0533'),
        ('entry', '0037_disaggregatedagecategory'),
    ]

    operations = [
    ]
