# Generated by Django 3.0.5 on 2021-03-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_merge_20210328_1132'),
        ('entry', '0039_auto_20210330_0905'),
    ]

    operations = [
    ]
