# Generated by Django 3.0.5 on 2021-04-13 09:29

import apps.entry.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0041_auto_20210331_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='displacement_occured',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.DISPLACEMENT_OCCURRED, null=True),
        ),
        migrations.AddField(
            model_name='figureterm',
            name='displacement_occur',
            field=models.BooleanField(default=False, verbose_name='Displacement can occur?'),
        ),
    ]
