# Generated by Django 3.0.5 on 2021-04-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_merge_20210329_0936'),
        ('entry', '0041_auto_20210331_0519'),
    ]

    operations = [
    ]
