# Generated by Django 3.0.5 on 2021-04-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0042_merge_20210413_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='geo_locations',
            field=models.ManyToManyField(related_name='figures', to='entry.OSMName', verbose_name='Geo Locations'),
        ),
    ]
