# Generated by Django 3.0.5 on 2021-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0042_merge_20210413_0527'),
        ('entry', '0042_auto_20210413_0929'),
    ]

    operations = [
    ]
