# Generated by Django 3.0.5 on 2021-05-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0043_merge_20210422_0632'),
        ('entry', '0043_auto_20210421_0538'),
    ]

    operations = [
    ]
