# Generated by Django 3.0.5 on 2021-05-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0044_merge_20210505_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='disaggregation_strata_json',
        ),
    ]
