# Generated by Django 3.0.5 on 2021-05-21 11:30

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0044_merge_20210505_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='review_status',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.EntryReviewer.REVIEW_STATUS, null=True),
        ),
        migrations.AlterField(
            model_name='entryreviewer',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.entry.models.EntryReviewer.REVIEW_STATUS),
        ),
    ]
