# Generated by Django 3.0.5 on 2021-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0046_auto_20210527_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmname',
            name='country_code',
            field=models.CharField(max_length=8, null=True, verbose_name='Country Code'),
        ),
    ]
