# Generated by Django 3.0.5 on 2021-06-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0047_entry_document_url'),
        ('entry', '0047_auto_20210616_1212'),
    ]

    operations = [
    ]
