# Generated by Django 3.0.5 on 2021-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0048_merge_20210623_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='start_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['event'], name='entry_entry_event_i_3f84f2_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['start_date'], name='entry_figur_start_d_d1f3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['end_date'], name='entry_figur_end_dat_ce6b16_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['country'], name='entry_figur_country_9bbef5_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['category'], name='entry_figur_categor_4ded9b_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['role'], name='entry_figur_role_7d7cda_idx'),
        ),
    ]
