# Generated by Django 3.0.5 on 2021-07-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0047_auto_20210623_0846'),
        ('entry', '0048_merge_20210623_0858'),
    ]

    operations = [
    ]
