# Generated by Django 3.0.5 on 2021-07-26 06:11

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0049_merge_20210702_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='idmc_analysis',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='IDMC Analysis'),
        ),
    ]
