# Generated by Django 3.0.5 on 2021-07-21 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0049_merge_20210702_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='osmname',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, verbose_name='UUID'),
        ),
    ]
