# Generated by Django 3.0.5 on 2021-07-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0050_auto_20210721_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='idmc_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='IDMC Analysis'),
        ),
    ]
