# Generated by Django 3.0.5 on 2021-09-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0051_auto_20210726_0611'),
        ('entry', '0049_auto_20210629_1101'),
    ]

    operations = [
    ]
