# Generated by Django 3.0.5 on 2021-09-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0052_merge_20210901_1520'),
        ('entry', '0052_auto_20210824_0416'),
    ]

    operations = [
    ]
