# Generated by Django 3.0.5 on 2021-09-28 07:47

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0053_merge_20210920_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article_title',
            field=utils.fields.BleachedTextField(verbose_name='Event Title'),
        ),
    ]
