# Generated by Django 3.0.5 on 2021-09-13 05:30

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0053_merge_20210920_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='calculation_logic',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='caveats',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
        migrations.AddField(
            model_name='figure',
            name='calculation_logic',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='Calculation Logic'),
        ),
        migrations.AddField(
            model_name='figure',
            name='caveats',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='Caveats'),
        ),
        migrations.AddField(
            model_name='figure',
            name='tags',
            field=models.ManyToManyField(blank=True, to='entry.FigureTag'),
        ),
    ]
