# Generated by Django 3.0.5 on 2021-09-30 13:12

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0053_merge_20210920_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article_title',
            field=utils.fields.BleachedTextField(verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='household_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Household Size'),
        ),
    ]
