# Generated by Django 3.0.5 on 2021-10-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0054_auto_20210913_0530'),
        ('entry', '0054_auto_20210930_1312'),
    ]

    operations = [
    ]
