# Generated by Django 3.0.5 on 2021-09-30 11:26

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0054_auto_20210913_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='source_excerpt',
        ),
        migrations.AddField(
            model_name='figure',
            name='source_excerpt',
            field=utils.fields.BleachedTextField(blank=True, null=True, verbose_name='Excerpt from Source'),
        )
    ]
