# Generated by Django 3.0.5 on 2021-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0055_merge_20211007_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article_title',
            field=models.TextField(verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='idmc_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Trends and patterns of displacement to be highlighted'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='calculation_logic',
            field=models.TextField(blank=True, null=True, verbose_name='Analysis and Calculation Logic'),
        ),
    ]
