# Generated by Django 3.0.5 on 2021-10-19 07:01

import apps.entry.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0058_auto_20211009_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='disaggregation_age_json',
        ),
        migrations.CreateModel(
            name='DisaggregatedAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', django_enumfield.db.fields.EnumField(enum=apps.common.enums.GENDER_TYPE)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, verbose_name='UUID')),
                ('value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Value')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disaggregated_age_category', to='entry.DisaggregatedAgeCategory', verbose_name='Disaggregated age category')),
            ],
        ),
        migrations.AddField(
            model_name='figure',
            name='disaggregation_age',
            field=models.ManyToManyField(blank=True, related_name='entry_figure_related', to='entry.DisaggregatedAge', verbose_name='Disaggregated age'),
        ),
    ]
