# Generated by Django 3.0.5 on 2021-11-12 04:36

import apps.entry.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0036_auto_20211112_0436'),
        ('extraction', '0027_auto_20211112_0436'),
        ('entry', '0059_auto_20211019_0701'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='figure',
            name='entry_figur_categor_4ded9b_idx',
        ),
        migrations.AlterField(
            model_name='figure',
            name='category',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES, null=True),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['category'], name='entry_figur_categor_522cc9_idx'),
        ),
        migrations.DeleteModel(
            name='FigureCategory',
        ),
    ]
