# Generated by Django 3.0.5 on 2022-04-07 06:51

import apps.entry.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0026_auto_20220407_0651'),
        ('report', '0035_auto_20220407_0651'),
        ('entry', '0059_auto_20211019_0701'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='figure',
            name='entry_figur_categor_4ded9b_idx',
        ),
        migrations.AlterField(
            model_name='figure',
            name='category',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES),
        ),
        migrations.AlterField(
            model_name='figure',
            name='term',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_TERMS),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['category'], name='entry_figur_categor_522cc9_idx'),
        )
    ]
