# Generated by Django 3.0.5 on 2022-04-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_ignore_qa'),
        ('entry', '0059_auto_20211019_0701'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entry',
            name='entry_entry_event_i_3f84f2_idx',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='event',
        ),
        migrations.AddField(
            model_name='figure',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='event.Event', verbose_name='Event'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['event'], name='entry_figur_event_i_576559_idx'),
        ),
    ]
