# Generated by Django 3.0.5 on 2022-04-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0060_auto_20220407_0651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FigureCategory',
        ),
        migrations.DeleteModel(
            name='FigureTerm',
        ),
    ]
