# Generated by Django 3.0.5 on 2021-11-16 04:51

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_auto_20211116_0451'),
        ('extraction', '0028_auto_20211116_0451'),
        ('entry', '0060_auto_20211112_0436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FigureTerm',
        ),
        migrations.AlterField(
            model_name='figure',
            name='term',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_TERMS, null=True),
        ),
    ]
