# Generated by Django 3.0.5 on 2022-04-07 11:07

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0061_auto_20220407_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='category',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES, null=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='term',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.Figure.FIGURE_TERMS, null=True),
        ),
    ]
