# Generated by Django 3.0.5 on 2022-04-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0060_auto_20220408_0337'),
        ('entry', '0062_auto_20220407_1107'),
    ]

    operations = [
    ]
