# Generated by Django 3.0.5 on 2022-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20220415_0544'),
        ('entry', '0063_merge_20220412_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='context_of_violence',
            field=models.ManyToManyField(blank=True, related_name='figures', to='event.ContextOfViolence', verbose_name='Context of violence'),
        ),
    ]
