# Generated by Django 3.0.5 on 2022-05-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_ignore_qa'),
        ('entry', '0063_merge_20220412_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='event.Event', verbose_name='Event'),
        ),
    ]
