# Generated by Django 3.0.5 on 2022-05-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0064_auto_20220520_1003'),
        ('entry', '0064_figure_context_of_violence'),
    ]

    operations = [
    ]
