# Generated by Django 3.0.5 on 2022-04-18 05:50

import apps.crisis.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20220418_0455'),
        ('entry', '0064_figure_context_of_violence'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='disaster_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterCategory', verbose_name='Figure Disaster Category'),
        ),
        migrations.AddField(
            model_name='figure',
            name='disaster_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterSubCategory', verbose_name='Figure Disaster Sub Category'),
        ),
        migrations.AddField(
            model_name='figure',
            name='disaster_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterSubType', verbose_name='Figure Disaster Sub Type'),
        ),
        migrations.AddField(
            model_name='figure',
            name='disaster_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterType', verbose_name='Figure Disaster Type'),
        ),
        migrations.AddField(
            model_name='figure',
            name='figure_cause',
            field=django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='figure',
            name='osv_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.OsvSubType', verbose_name='Figure OSV sub type'),
        ),
        migrations.AddField(
            model_name='figure',
            name='violence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.Violence', verbose_name='Figure Violence'),
        ),
        migrations.AddField(
            model_name='figure',
            name='violence_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.ViolenceSubType', verbose_name='Figure Violence Sub Type'),
        ),
    ]
