# Generated by Django 3.0.5 on 2022-05-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0065_merge_20220524_0404'),
        ('entry', '0065_auto_20220418_0550'),
    ]

    operations = [
    ]
