# Generated by Django 3.0.5 on 2022-05-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20220530_1013'),
        ('entry', '0066_merge_20220524_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='other_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.OtherSubType', verbose_name='Other sub type'),
        ),
    ]
