# Generated by Django 3.0.5 on 2022-05-25 10:15

import apps.common.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0066_merge_20220524_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='other_sub_type',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.common.enums.EVENT_OTHER_SUB_TYPE, null=True),
        ),
    ]
