# Generated by Django 3.0.5 on 2022-06-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0067_auto_20220530_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='caveats',
        ),
    ]
