# Generated by Django 3.0.5 on 2022-05-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0067_figure_other_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='caveats',
        ),
    ]
