# Generated by Django 3.0.5 on 2022-07-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0071_externalapidump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapidump',
            name='api_type',
            field=models.CharField(choices=[('idus', 'Idus'), ('idus-all', 'Idus all')], max_length=40),
        ),
    ]
