# Generated by Django 3.0.5 on 2022-07-21 09:45

import apps.entry.models
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0071_externalapidump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapidump',
            name='dump_file',
            field=utils.fields.CachedFileField(blank=True, null=True, upload_to=apps.entry.models.dump_file_upload_to, verbose_name='Dump file'),
        ),
        migrations.AlterField(
            model_name='externalapidump',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')]),
        ),
    ]
