# Generated by Django 3.0.5 on 2022-07-25 10:17

import apps.entry.models
from django.db import migrations
import helix.storages
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0071_externalapidump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapidump',
            name='dump_file',
            field=utils.fields.CachedFileField(blank=True, null=True, storage=helix.storages.FileSystemExternalMediaStorage, upload_to=apps.entry.models.dump_file_upload_to, verbose_name='Dump file'),
        ),
    ]
