# Generated by Django 3.0.5 on 2022-11-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0074_auto_20220823_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
