# Generated by Django 3.0.5 on 2022-11-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0076_auto_20221103_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figure',
            options={'permissions': (('qa_approve_figure', 'Can approve figure'), ('qa_unapprove_figure', 'Can un-approve figure'))},
        ),
    ]
