# Generated by Django 3.0.14 on 2023-02-09 10:21

from django.db import migrations


class Migration(migrations.Migration):
    def create_source_preview_and_clear_url(apps, schema_editor):
        from django.db.models import Q

        Entry = apps.get_model('entry', 'Entry')
        SourcePreview = apps.get_model('contrib', 'SourcePreview')

        # Create source preview with failed status
        entries_with_urls_but_no_source_previews =  Entry.objects.filter(
            Q(url__isnull=False) &
            ~Q(url='') &
            Q(preview_id__isnull=True) &
            Q(document_id__isnull=True) &
            Q(old_id__isnull=False)
        )
        for entry in entries_with_urls_but_no_source_previews:
            source_preview = SourcePreview.objects.create(
                url=entry.url, status=2 # SourcePreview.PREVIEW_STATUS.FAILED
            )
            entry.preview = source_preview
            entry.save()

        # Update entries
        Entry.objects.filter(
            Q(url__isnull=False) & Q(document_id__isnull=False)
        ).update(url=None)

    dependencies = [
        ('entry', '0077_auto_20221114_0425'),
    ]

    operations = [
        migrations.RunPython(create_source_preview_and_clear_url, reverse_code=migrations.RunPython.noop),
    ]
