# Generated by Django 3.0.14 on 2023-02-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20230216_0726'),
        ('entry', '0079_fix_is_disaggregated_household_size_displacement_occurred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='disaster_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterCategory', verbose_name='Figure Hazard Category'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='disaster_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterSubCategory', verbose_name='Figure Hazard Sub Category'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='disaster_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterSubType', verbose_name='Figure Hazard Sub Type'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='disaster_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='event.DisasterType', verbose_name='Figure Hazard Type'),
        ),
    ]
