# Generated by Django 3.0.14 on 2023-03-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    def update_violence_using_violence_sub_type(apps, schema_editor):
        from django.db.models import Subquery, OuterRef
        Figure = apps.get_model('entry', 'Figure')

        Figure.objects.filter(
            violence_sub_type__isnull=False
        ).update(
            violence=Subquery(
                Figure.objects.filter(pk=OuterRef('pk')).values('violence_sub_type__violence')[:1]
            )
        )

    dependencies = [
        ('entry', '0081_fix_total_figures_after_round_half_up'),
    ]

    operations = [
        migrations.RunPython(update_violence_using_violence_sub_type, reverse_code=migrations.RunPython.noop),
    ]
