# Generated by Django 3.0.14 on 2023-03-22 14:10

import csv
from io import StringIO
from django.db import migrations

CSV_DATE = '''
figure_old_id,event_old_id
62,62  # EXAMPLE PLEASE REMOVE THIS
'''

def update_figure_event_data(apps, _):
    Figure = apps.get_model('entry', 'Figure')
    Event = apps.get_model('event', 'Event')
    reader = csv.DictReader(
        StringIO(CSV_DATE),
        fieldnames=('figure_old_id', 'event_old_id',),
    )
    next(reader)  # Skip header
    for row in reader:
        # NOTE: old_id can have multiple result so doing this one by one for now
        Figure.objects.filter(old_id=row['figure_old_id']).update(
            event=Event.objects.get(pk=row['event_old_id']),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0082_regenerate_hazards_and_violences_of_event_and_figures'),
        ('event', '0031_fix_drought_and_cold_wave_data_migration'),
    ]

    operations = [
        migrations.RunPython(
            update_figure_event_data,
            reverse_code=migrations.RunPython.noop
        ),
    ]
