# Generated by Django 3.2 on 2023-04-04 04:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0083_update_figures_events_2023_03_22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='disaggregation_strata_json',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(verbose_name='Stratum'), blank=True, null=True, size=None, verbose_name='Strata Disaggregation'),
        ),
    ]
