# Generated by Django 3.2 on 2023-05-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0088_alter_externalapidump_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapidump',
            name='api_type',
            field=models.CharField(choices=[('idus', 'Idus'), ('idus-all', 'Idus all'), ('idus-all-disaster', 'Idus all disaster'), ('gidd-disaster-export-rest', 'Disaster export REST'), ('gidd-displacement-export-rest', 'Displacement export REST'), ('gidd-conflict', 'GIDD conflict'), ('gidd-disaster', 'GIDD disaster'), ('gidd-displacement-data', 'GIDD displacement data'), ('gidd-public-figure-analysis', 'GIDD public figure analysis'), ('gidd-conflict-stat', 'GIDD conflict stat'), ('gidd-disaster-stat', 'GIDD disaster stat'), ('gidd-hazard-type', 'GIDD hazard type'), ('gidd-year', 'GIDD year'), ('gidd-event', 'GIDD event'), ('gidd-combined-stat', 'GIDD combined stat'), ('gidd-release-meta-data', 'GIDD release meta data'), ('gidd-public-countries', 'GIDD public countries')], max_length=40),
        ),
    ]
