# Generated by Django 3.2 on 2023-05-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0088_alter_externalapidump_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapidump',
            name='api_type',
            field=models.CharField(choices=[('idus', 'Idus'), ('idus-all', 'Idus all'), ('idus-all-disaster', 'Idus all disaster'), ('gidd-disaster-export-rest', 'Disaster export REST'), ('gidd-displacement-export-rest', 'Displacement export REST'), ('gidd-conflict-graphql', 'GIDD conflict Graphql'), ('gidd-disaster-graphql', 'GIDD disaster Graphql'), ('gidd-displacement-data-graphql', 'GIDD displacement data Graphql'), ('gidd-public-figure-analysis-graphql', 'GIDD public figure analysis Graphql'), ('gidd-conflict-stat-graphql', 'GIDD conflict stat Graphql'), ('gidd-disaster-stat-graphql', 'GIDD disaster stat Graphql'), ('gidd-hazard-type-graphql', 'GIDD hazard type Graphql'), ('gidd-year-graphql', 'GIDD year Graphql'), ('gidd-event-graphql', 'GIDD event Graphql'), ('gidd-combined-stat-graphql', 'GIDD combined stat Graphql'), ('gidd-release-meta-data-graphql', 'GIDD release meta data Graphql'), ('gidd-public-countries-graphql', 'GIDD public countries Graphql')], max_length=40),
        ),
    ]
