# Generated by Django 4.0 on 2023-06-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_first_name'),
        ('entry', '0091_alter_externalapidump_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='entryreviewer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='externalapidump',
            name='api_type',
            field=models.CharField(choices=[('idus', 'HELIX idus last 180 days'), ('idus-all', 'HELIX idus all'), ('idus-all-disaster', 'HELIX idus all disasters'), ('gidd-country-rest', 'GIDD countries'), ('gidd-conflict-rest', 'GIDD conflicts'), ('gidd-disaster-rest', 'GIDD disasters'), ('gidd-displacement-rest', 'GIDD displacements'), ('gidd-disaster-export-rest', 'GIDD disasters export'), ('gidd-displacement-export-rest', 'GIDD displacements export'), ('gidd-public-figure-analysis-rest', 'GIDD public figure analyses'), ('gidd-conflict-graphql', 'GIDD conflicts [graphql]'), ('gidd-disaster-graphql', 'GIDD disasters [graphql]'), ('gidd-displacement-data-graphql', 'GIDD displacements [graphql]'), ('gidd-public-figure-analysis-graphql', 'GIDD public figure analyses [graphql]'), ('gidd-conflict-stat-graphql', 'GIDD conflict statistics [graphql]'), ('gidd-disaster-stat-graphql', 'GIDD disaster statistics [graphql]'), ('gidd-hazard-type-graphql', 'GIDD hazard types [graphql]'), ('gidd-year-graphql', 'GIDD year [graphql]'), ('gidd-event-graphql', 'GIDD event [graphql]'), ('gidd-combined-stat-graphql', 'GIDD combined statistics [graphql]'), ('gidd-release-meta-data-graphql', 'GIDD release metadata [graphql]'), ('gidd-public-countries-graphql', 'GIDD public countries [graphql]')], max_length=40),
        ),
        migrations.AlterField(
            model_name='figure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='disaggregation_age',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='entry.DisaggregatedAge', verbose_name='Disaggregated age'),
        ),
        migrations.AlterField(
            model_name='figuretag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to='users.user', verbose_name='Created By'),
        ),
    ]
