# Generated by Django 4.0 on 2023-06-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0092_alter_entry_created_by_and_more'),
        ('entry', '0092_alter_externalapidump_api_type'),
    ]

    operations = [
    ]
