# Generated by Django 3.2 on 2023-10-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0094_auto_20230712_0528'),
        ('entry', '0094_bulk_update_figure_hazard_typologies'),
    ]

    operations = [
    ]
