# Generated by Django 3.2 on 2024-03-06 10:04

import gzip
import os
import csv
from django.db import migrations
from helix.managers import BulkUpdateManager


def update_figure_created_by(apps, schema_editor):
    Figure = apps.get_model('entry', 'Figure')

    correct_data_file_path = os.path.join(
        os.path.dirname(__file__),
        'correct_figures_created_by_data.csv.gz',
    )
    figures_to_update = []
    figures_id_to_update = []
    with gzip.open(correct_data_file_path, 'rt', encoding='utf-8') as fp:
        csv_reader = csv.DictReader(fp, fieldnames=['figure_id', 'created_by_id'])

        next(csv_reader)  # Skip headers
        for row in csv_reader:
            figures_id_to_update.append(int(row['figure_id']))
            figures_to_update.append(
                Figure(
                    pk=int(row['figure_id']),
                    created_by_id=row['created_by_id'],
                )
            )

    figures_available_to_update_set = set(
        Figure.objects.filter(
            id__in=figures_id_to_update,
        ).values_list('id', flat=True)
    )

    print(f'Updating {len(figures_available_to_update_set)} out of {len(figures_to_update)}', end=' ')

    bulk_mgr = BulkUpdateManager(['created_by_id'], chunk_size=1000)
    for figure in figures_to_update:
        if figure.pk in figures_available_to_update_set:
            bulk_mgr.add(figure)
    bulk_mgr.done()
    print('Bulk update summary:', bulk_mgr.summary())


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0096_bulk_update_figure_hazard_typologies_two'),
    ]

    operations = [
        migrations.RunPython(update_figure_created_by, reverse_code=migrations.RunPython.noop),
    ]
