# Generated by Django 3.2 on 2024-04-05 06:03

from django.db import migrations
from decimal import Decimal

from utils.common import round_half_up


UNIT = {
    'PERSON': 0,
    'HOUSEHOLD': 1
}

ROLE = {
    'RECOMMENDED': 0,
    'TRIANGULATION': 1
}


def calculate_total_figure(fig, household_size):
    total_figures = round_half_up(fig.reported * Decimal(str(household_size)))
    return total_figures


def update_average_household_data(apps, _):
    Figure = apps.get_model('entry', 'Figure')
    HouseholdSize = apps.get_model('country', 'HouseholdSize')

    household_ids = [  # FIXME: Update this ids when we get the real data.
        # {"iso3": "IND", "year": 2016, "size": 1.5},
        # {"iso3": IND, year: 2024, "size": 1.2},
    ]
    updated_figure_ids = []
    if not household_ids == []:
        for household in household_ids:
            household_size = HouseholdSize.objects.get(
                country__iso3=household["iso3"],
                year=household["year"]
            )
            if household_size.size == household['size']:
                continue
            household_size.size = household['size']
            household_size.save()

            figures = Figure.objects.filter(
                country__iso3=household['iso3'],
                unit=UNIT['HOUSEHOLD'],
                role=ROLE['TRIANGULATION'],
                end_date__year=household['year']
            )

            for fig in figures:
                total_figure = calculate_total_figure(fig, household['size'])
                fig.total_figures = total_figure
                fig.save()
                updated_figure_ids.append(fig.id)

    print("Figures count:", len(updated_figure_ids))

    raise Exception("Testing")


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0097_fix_figure_created_by'),
    ]

    operations = [
        migrations.RunPython(update_average_household_data, reverse_code=migrations.RunPython.noop),
    ]
