# Generated by Django 3.2 on 2025-03-26 04:48

import logging
from django.db import migrations, models

logger = logging.getLogger(__name__)

class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0099_alter_externalapidump_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmname',
            name='geocoder_metadata',
            field=models.JSONField(default=dict),
        ),

        migrations.RunSQL(
            sql='''
            UPDATE entry_osmname
            SET geocoder_metadata = (
                SELECT row_to_json((
                    SELECT t FROM (
                        SELECT
                            wikipedia,
                            rank,
                            street,
                            wiki_data as wikidata,
                            country_code,
                            osm_id,
                            house_numbers as housenumbers,
                            city,
                            display_name,
                            lon,
                            state,
                            bounding_box as boundingbox,
                            type,
                            importance,
                            lat,
                            class_name as class,
                            name,
                            country,
                            name_suffix,
                            osm_type,
                            place_rank,
                            alternative_names
                    WHERE entry_osmname.id = id
                    ) t
                ))
            );
            ''',
        )
    ]
