# Generated by Django 3.2 on 2025-03-26 04:48

import logging
from django.db import migrations, models

from apps.entry.serializers import OSMNameSerializer
from helix.managers import BulkUpdateManager

logger = logging.getLogger(__name__)

class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0099_alter_externalapidump_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmname',
            name='geocoder_metadata',
            field=models.JSONField(default=dict),
        ),

        migrations.RunSQL(
            sql='''
            UPDATE entry_osmname
            SET geocoder_metadata = (
                SELECT row_to_json((
                    SELECT t FROM (
                        SELECT 
                            id,
                            uuid,
                            wikipedia,
                            rank,
                            country,
                            country_code,
                            street,
                            wiki_data,
                            osm_id,
                            osm_type,
                            house_numbers,
                            identifier,
                            city,
                            display_name,
                            lon,
                            lat,
                            state,
                            bounding_box,
                            type,
                            importance,
                            class_name,
                            name,
                            name_suffix,
                            place_rank,
                            alternative_names,
                            accuracy,
                            moved
                        LIMIT 1
                    ) t
                ))
            );
            ''',
        )
    ]
