# Generated by Django 3.2 on 2025-03-27 04:37

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0100_osmname_geocoder_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OSMName',
            new_name='FigureLocation',
        ),
        migrations.AlterField(
            model_name='figure',
            name='geo_locations',
            field=models.ManyToManyField(related_name='figures', to='entry.FigureLocation', verbose_name='Geo Locations'),
        ),
    ]
