# Generated by Django 3.2 on 2025-03-27 09:34

import django_enumfield.db.fields
import apps.entry.models

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20240326_0824'),
        ('entry', '0100_osmname_geocoder_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OSMName',
            new_name='FigureLocation',
        ),
        migrations.AlterField(
            model_name='figure',
            name='geo_locations',
            field=models.ManyToManyField(related_name='figures', to='entry.FigureLocation', verbose_name='Geo Locations'),
        ),
        migrations.AddField(
            model_name='figurelocation',
            name='geocoder',
            field=django_enumfield.db.fields.EnumField(default=1, enum=apps.entry.models.FigureLocation.GEOCODER),
        ),
    ]
