# Generated by Django 3.2 on 2025-03-27 06:00

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0101_figurelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurelocation',
            name='geocoder',
            field=django_enumfield.db.fields.EnumField(default=3, enum=apps.entry.models.FigureLocation.GEOCODER),
        ),
    ]
