# Generated by Django 3.2 on 2025-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0102_alter_figurelocation_geocoder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurelocation',
            name='osm_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='OSM Id'),
        ),
        migrations.AlterField(
            model_name='figurelocation',
            name='osm_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='OSM Type'),
        ),
    ]
