# Generated by Django 3.2 on 2025-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0103_auto_20250331_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurelocation',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='figurelocation',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
