# Generated by Django 3.2 on 2025-12-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0104_auto_20250331_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapidump',
            name='include_sources',
            field=models.BooleanField(default=True),
        ),
    ]
