# Generated by Django 3.2 on 2025-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0105_externalapidump_include_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapidump',
            name='format',
            field=models.IntegerField(choices=[(0, 'Json'), (1, 'Geojson'), (2, 'Excel')], default=0),
        ),
    ]
