# Generated by Django 3.2 on 2026-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0106_update_figure_role_calculation_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['start_date_accuracy'], name='entry_figur_start_d_ae9c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['end_date_accuracy'], name='entry_figur_end_dat_dc3b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='figurelocation',
            index=models.Index(fields=['name'], name='entry_figur_name_175cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='figurelocation',
            index=models.Index(fields=['display_name'], name='entry_figur_display_9b8529_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['publish_date'], name='entry_entry_publish_6dc760_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['review_status'], name='entry_entry_review__700223_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['figure_cause'], name='entry_figur_figure__298cac_idx'),
        ),
    ]
