# Generated by Django 3.2 on 2026-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0107_auto_20260225_0529'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['publish_date'], name='entry_entry_publish_6dc760_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['review_status'], name='entry_entry_review__700223_idx'),
        )
    ]
