# Generated by Django 3.2 on 2026-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0107_auto_20260225_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapidump',
            name='format',
            field=models.IntegerField(choices=[(0, 'Json'), (1, 'Geojson'), (2, 'Excel')], default=0),
        ),
    ]
