# Generated by Django 3.2 on 2026-06-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0108_auto_20260611_0631'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externalapidump',
            constraint=models.UniqueConstraint(fields=('format', 'include_sources', 'api_type'), name='unique_for_format_type_and_include_sources'),
        ),
    ]
