# Generated by Django 3.2 on 2026-06-20 04:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0109_externalapidump_unique_for_format_type_and_include_sources'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=True), name='figure_created_at_desc_idx'),
        ),
    ]
