# Generated by Django 3.2 on 2026-06-20 05:08

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0110_figure_figure_created_at_desc_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=True), name='entry_created_at_desc_idx'),
        ),
    ]
