# Generated by Django 3.2 on 2026-06-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0111_entry_entry_created_at_desc_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='figure',
            name='entry_figur_country_9bbef5_idx',
        ),
        migrations.RemoveIndex(
            model_name='figure',
            name='entry_figur_event_i_576559_idx',
        ),
    ]
