# Generated by Django 3.2 on 2026-06-22 01:31

import apps.entry.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0112_remove_figure_duplicate_fk_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='category',
            field=django_enumfield.db.fields.EnumField(enum=apps.entry.models.Figure.FIGURE_CATEGORY_TYPES),
        ),
    ]
