# Generated by Django 3.2 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0113_figure_category_not_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(
                condition=models.Q(('role', 0)),
                fields=['event', 'category', 'end_date'],
                name='figure_event_cat_role_rec_idx',
            ),
        ),
    ]
