# Generated by Django 3.2 on 2026-08-13 08:55

import apps.entry.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0115_pg_trgm_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurelocation',
            name='pcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='P-Code'),
        ),
        migrations.AddField(
            model_name='figurelocation',
            name='pcode_accuracy',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.entry.models.FigureLocation.PCODE_ACCURACY, null=True),
        ),
        migrations.AddField(
            model_name='figurelocation',
            name='pcode_source',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='P-Code Source'),
        ),
    ]
