# Generated by Django 3.2 on 2026-08-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0117_figure_uuid_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(fields=["category", "start_date"], name="entry_figur_categor_26279f_idx"),
        ),
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(fields=["category", "end_date"], name="entry_figur_categor_885feb_idx"),
        ),
    ]
