# Generated by Django 3.2 on 2026-08-25 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0116_figurelocation_pcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='figurelocation',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, verbose_name='UUID'),
        ),
    ]
