# Generated by Django 3.2 on 2026-08-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0117_figure_category_date_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(
                condition=models.Q(role=0),
                fields=["country", "category", "end_date"],
                include=("total_figures",),
                name="figure_ctry_cat_end_rec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(
                condition=models.Q(role=0),
                fields=["country", "category", "start_date"],
                include=("total_figures",),
                name="figure_ctry_cat_start_rec_idx",
            ),
        ),
    ]
