# Generated by Django 3.2 on 2026-08-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entry", "0118_figure_aggregation_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="figure",
            name="figure_event_cat_role_rec_idx",
        ),
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(
                condition=models.Q(role=0),
                fields=["event", "category", "end_date"],
                include=("total_figures",),
                name="figure_event_cat_role_rec_idx",
            ),
        ),
    ]
