# Generated by Django 3.2 on 2026-08-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0120_alter_externalapidump_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapidump',
            name='api_type',
            field=models.CharField(choices=[('idus', '/external-api/idus/last-180-days/'), ('idus-excel', '/external-api/idus/last-180-days-excel/'), ('idus-geojson', '/external-api/idus/last-180-days-geojson/'), ('idus-all', '/external-api/idus/all/'), ('idus-all-excel', '/external-api/idus/all-excel/'), ('idus-all-geojson', '/external-api/idus/all-geojson/'), ('idus-all-disaster', '/external-api/idus/all/disaster/'), ('idus-all-disaster-excel', '/external-api/idus/all/disaster-excel/'), ('idus-all-disaster-geojson', '/external-api/idus/all/disaster-geojson/'), ('idu-references', '/external-api/idus/references/'), ('gidd-country-rest', '/external-api/gidd/countries/'), ('gidd-conflict-rest', '/external-api/gidd/conflicts/'), ('gidd-disaster-rest', '/external-api/gidd/disasters/'), ('gidd-displacement-rest', '/external-api/gidd/displacements/'), ('gidd-disaster-export-rest', '/external-api/gidd/disasters/disaster-export/'), ('gidd-displacement-export-rest', '/external-api/gidd/displacements/displacement-export/'), ('gidd-public-figure-analysis-rest', '/external-api/gidd/public-figure-analyses/'), ('gidd-disaggregation-export-geojson-rest', '/external-api/gidd/disaggregations/disaggregation-geojson/'), ('gidd-disaggregation-export-xlsx-rest', '/external-api/gidd/disaggregations/disaggregation-export/'), ('gidd-conflict-graphql', 'query.giddPublicConflicts'), ('gidd-disaster-graphql', 'query.giddPublicDisasters'), ('gidd-displacement-data-graphql', 'query.giddPublicDisplacements'), ('gidd-public-figure-analysis-graphql', 'query.giddPublicFigureAnalysisList'), ('gidd-conflict-stat-graphql', 'query.giddPublicConflictStatistics'), ('gidd-disaster-stat-graphql', 'query.giddPublicDisasterStatistics'), ('gidd-hazard-type-graphql', 'query.giddPublicHazardTypes'), ('gidd-year-graphql', 'query.giddPublicYear'), ('gidd-event-graphql', 'query.giddPublicEvent'), ('gidd-combined-stat-graphql', 'query.giddPublicCombinedStatistics'), ('gidd-release-meta-data-graphql', 'query.giddPublicReleaseMetaData'), ('gidd-public-countries-graphql', 'query.giddPublicCountries'), ('gidd-new-events-graphql', 'query.giddPublicDisplacementEvents'), ('gidd-country-displacement-graphql', 'query.giddPublicCountryDisplacements'), ('gidd-country-year-displacement-graphql', 'query.giddPublicCountryYearDisplacements'), ('gidd-violence-sub-types-graphql', 'query.giddPublicViolenceSubTypes')], max_length=40),
        ),
    ]
