name: CI

on:
  pull_request:

jobs:
  _:
    uses: toggle-corp/banjo-action/.github/workflows/pipeline.yml@v0.2.0
    permissions:
      contents: read
      packages: write
      pull-requests: read
    with:
      # Job: Docker
      docker__wait_cmd: "./manage.py wait_for_resources --db --cache --minio"
      docker__migration_dummy_test: "helix.tests.FakeTest"
      docker__run_graphql_check: true
      docker__compose_file: "docker-compose.yml:gh-docker-compose.yml"
      docker__compose_service_name: "server"
      docker__compose_test_cmd: "/code/run_tests.sh"
      # Extra step - TODO: Use pre step?
      docker__post_test__extra_step_01: "🕮 Validate pyhelix constants are in sync with helix-server enums."
      docker__post_test__extra_step_01_command: "docker compose run --rm server ./manage.py update_pyhelix_constants --check"
      # Job: Helm
      helm__chart_directory: "./helm"
