name: Flake8 Lint

on:
  push:
    branches:
      - 'develop'
      - 'project/**'
  pull_request:
    branches:
      - 'develop'
      - 'project/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flake8
        run: |
          pip install flake8
      - name: Run Linters
        run: |
          flake8
