name: Pre-commit

on:
  push:
    branches:
      - 'develop'
      - 'project/**'
  pull_request:
    branches:
      - 'develop'
      - 'project/**'

jobs:
  pre_commit_checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup uv python environment
        run: uv venv

      - name: uv lock check
        run: uv lock --locked --offline

      - name: uv sync
        run: uv sync --all-extras

      - uses: pre-commit/action@main
