name: Django Test Runner

on:
  push:
    branches:
      - 'develop'
      - 'release'
      - 'project/**'
  pull_request:

env:
  GITHUB_WORKFLOW: true
  COMPOSE_FILE: docker-compose.yml:gh-docker-compose.yml
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: true

      - name: 🐳 Prepare Docker
        id: prep
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        run: |
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

          BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed 's|:|-|' | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g' | cut -c1-100 | sed 's/-*$//' | sed 's|/|-|g')
          GIT_HASH="$(echo $GITHUB_SHA | head -c7)"
          TAG="$BRANCH_NAME.c$(echo $GIT_HASH)"

          echo "tagged_image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "tagged_image=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT
          echo "::notice::Tagged docker image: ${IMAGE_NAME}:${TAG}"

      - name: 🐳 Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: 🐳 Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: worker
          push: false # This would be set to true in a real world deployment scenario.
          load: true
          tags: ${{ steps.prep.outputs.tagged_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start app resources
        timeout-minutes: 1
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker compose run --rm server ./manage.py wait_for_resources --all || {
            echo 'Failed to wait for the resources';
            exit 1;
          }

      - name: 🕮 Validate latest graphql schema.
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker compose run --rm server ./manage.py graphql_schema --out schema-latest.graphql &&
          cmp --silent schema.graphql schema-latest.graphql || {
            echo 'The schema.graphql is not up to date with the latest changes. Please update and push latest';
            diff schema.graphql schema-latest.graphql;
            exit 1;
          }

      - name: 🕮 Validate if there are no pending django migrations.
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker compose run --rm server python3 manage.py makemigrations --check --dry-run || {
            echo 'There are some changes to be reflected in the migration. Make sure to run makemigrations';
            exit 1;
          }

      - name: 🤞 Run Test 🧪
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker compose run --rm server /code/run_tests.sh
          echo '## Test Coverage Report' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '<details>' >> $GITHUB_STEP_SUMMARY
          echo '<summary>Table</summary>' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          cat ./test-coverage.md >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY

  validate_helm:
    name: Validate Helm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: true

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: 🐳 Helm dependency
        run: |
          yq --indent 0 '.dependencies | map(select(.repository | test("^oci:") | not)) | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' ./helm/Chart.lock | sh --
          helm dependency build ./helm

      - name: 🐳 Helm template (snapshot)
        run: ./helm/update-snapshots.sh --check-diff-only
