name: Django Test Runner

on:
  push:
    branches:
      - 'develop'
      - 'project/**'
  pull_request:
    branches:
      - 'develop'
      - 'project/**'

env:
  GITHUB_WORKFLOW: true

jobs:
  build:
    name: CI
    uses: toggle-corp/toggle-django-action/.github/workflows/django-docker-ci.yml@main
    with:
      compose_file: "docker-compose.yml:gh-docker-compose.yml"
      service_name: "server"
      chart_directory: "./helm"
      test_target: "/code/run_tests.sh"
