# Generated by Django 3.0.5 on 2020-08-20 11:52

import apps.crisis.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('country', '0002_auto_20200819_0628'),
        ('crisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='event.DisasterCategory', verbose_name='Disaster Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('disaster_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='event.DisasterSubCategory', verbose_name='Disaster Sub Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolenceSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('violence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='event.Violence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriggerSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='event.Trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='event.DisasterType', verbose_name='Disaster Sub Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Event Name')),
                ('event_type', django_enumfield.db.fields.EnumField(enum=apps.crisis.models.Crisis.CRISIS_TYPE)),
                ('glide_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Glide Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('event_narrative', models.TextField(blank=True, null=True, verbose_name='Event Narrative')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.Actor', verbose_name='Actors')),
                ('countries', models.ManyToManyField(blank=True, related_name='events', to='country.Country', verbose_name='Countries')),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crisis.Crisis', verbose_name='Crisis')),
                ('disaster_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterCategory', verbose_name='Disaster Category')),
                ('disaster_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterSubCategory', verbose_name='Disaster Sub-Type')),
                ('disaster_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterSubType', verbose_name='Disaster Sub-Type')),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.DisasterType', verbose_name='Disaster Type')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.Trigger', verbose_name='Trigger')),
                ('trigger_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.TriggerSubType', verbose_name='Trigger Sub-Type')),
                ('violence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.Violence', verbose_name='Violence')),
                ('violence_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.ViolenceSubType', verbose_name='Violence Sub-Type')),
            ],
        ),
    ]
