# Generated by Django 3.0.5 on 2020-11-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0002_auto_20201019_0758'),
        ('event', '0004_auto_20201102_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='crisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crisis.Crisis', verbose_name='Crisis'),
        ),
    ]
