# Generated by Django 3.0.5 on 2021-02-02 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_auto_20210202_0517'),
        ('event', '0008_merge_20210105_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='country.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='torg',
            field=models.CharField(max_length=10, null=True, verbose_name='Torg'),
        ),
    ]
